### ISSUE TITLE
Add a review

### ISSUE THREAD

**Issue by shartlordyt** [3kh0/3kh0.github.io#100]
### Name

Shartlord (S.T)

### Review

This site is really cool! If i had to say, it is the definitive unblocked games site! 3kh0's site has inspired me to make some of my projects. The search function is nice and there really isn't any games that are objectively bad (i.e, glitches, low effort flash stuff) and there's (almost) everything i'd want on a site like this. Proxies are also cool. Best feature is the fact that the source is on git so you can make a repl out of it super easy. I miss the v2 home page, may it rest in peace.

420/69

### Profile picture

![Screenshot 2022-10-07 12 37 52 PM](https://user-images.githubusercontent.com/115052495/194640636-6c139eae-f049-4537-84aa-ae8e196f6b9c.png)

**Comment by 3kh0** [comment]
I had to cut your review in some places so it would be inside the box.

```
If i had to say, it is the best unblocked games site! 3kh0's site has inspired me to make my own projects. Proxies are cool, the source is open, the search function, and quality games. I miss the v2 home page, RIP.
```

**Comment by shartlordyt** [comment]
alright! :)
