### ISSUE TITLE
Website blocked, maybe add heroku support

### ISSUE THREAD

**Issue by Lhinger** [3kh0/3kh0.github.io#100]
**Please describe what happened**

It says "connection reset."

**How is the site being blocked?**

The page goes to a google error screen and says "connection reset"

**Which of the websites are blocked for you?**

Put an x in the brackets if it is blocked, like this: [X]

- [x] https://3kh0.github.io
- [x] https://3kh0.vercel.app/
- [x] https://3kh0.netlify.app/

**Additional context**

Possibly add heroku compatibility so if its blocked for anyone, they can deploy to heroku and have their own site.

**Comment by 3kh0** [comment]
https://3kh0.bitbucket.io/
