### ISSUE TITLE
Applications for repo maintainers

### ISSUE THREAD

**Issue by 3kh0** [3kh0/3kh0.github.io#101]
The title says it all, click the link below.

https://bit.do/3kh0-github

Have you gave this repo a :star: yet?

**Comment by 3kh0** [comment]
Full link: https://docs.google.com/forms/d/e/1FAIpQLScC6RMq2MNO3nEVqMadHvE6LKvMzvho9OsThNb-r5bkiBmNgQ/viewform

**Comment by Piplup7575** [comment]
woops

**Comment by 3kh0** [comment]
> woops

😑
