### ISSUE TITLE
Learn to fly 2 doesn't function

### ISSUE THREAD

**Issue by 192279VANSD** [3kh0/3kh0.github.io#101]
### Check these boxes to make sure you did everything right!

- [X] I have made sure that this issue does not already exist
- [X] I have submitted screenshots of the error
- [X] You are not using the website on any clones (you are using 3kh0.github.io and nothing else)
- [x] I just checked all of these boxes without reading the labels

### What browser are you using?

Google Chrome

### What device are you using?

Windows Laptop (or any device running Windows)

### Please explain the issue

When i start learn to fly, it works until you have to take off the first time. Then your character doesn't move, but just hovers there.

**Comment by Russell2259** [comment]
We'll look into it

**Comment by Russell2259** [comment]
Do you have a screenshot?

**Comment by 192279VANSD** [comment]
Not yet. Im currently busy with other things, will try to do.

**Comment by Russell2259** [comment]
Ok

**Comment by mc201288813** [comment]
Learn to fly 2 is known to not work on ruffle emulator, no fixes

**Comment by aeiea** [comment]
@Russell2259 pls close
