### ISSUE TITLE
Add a review

### ISSUE THREAD

**Issue by broimtiredpleasae** [3kh0/3kh0.github.io#103]
### Name

i hate my life

### Review

Hey everybody, today we're going to show you how to decorate a birthday cake. Happy birthday! Now it's time to decorate the cake. Nobody else is gonna do it for you because nobody's coming over to celebrate your birthday with you. They would'nt dare. They wouldn't want to be around you and even if they did they wouldn't risk it. What if everybody in class found out that they were hanging out with you? They'd be a laughing stock! They'd be chastised and brutalized and shunned. You understand how that feels. You wouldn't want anybody else to feel so alone and isolated and hated as you do. So you don't even bother invited anybody to your birthday anymore. In fact, you don't even really celebrate anymore. You just make yourself a subpar cake and decorate it yourself, alone. In the dark. Alone. Completely alone. To decorate a birthday cake spread some goo on it and make it into a design. Who cares? Why do I even bother doing this every year? I don't even like cake. I used to think it would cheer me up but it doesn't.. nothing does. I hate birthdays, I hate myself... I hate calenders

### Profile picture

![image](https://user-images.githubusercontent.com/111049092/194782733-2d068ae5-4276-4712-a708-d07648667a70.png)

**Comment by 3kh0** [comment]
@broimtiredpleasae Your review is too long, do you want me to cut it off to the following:
> Hey everybody, today we're going to show you how to decorate a birthday cake. Happy birthday! Now it's time to decorate the cake. Nobody else is gonna do it for you because nobody's coming over to celebrate your birthday with you.
