### ISSUE TITLE
Add a review

### ISSUE THREAD

**Issue by ROnaldMcd0nald** [3kh0/3kh0.github.io#105]
### Name

Jeffrey

### Review

10/10, my dad approves and likes the games

### Profile picture

![unnamed](https://user-images.githubusercontent.com/98975741/194946847-c7acb8fe-02d6-40fb-a456-15f50df5ab63.jpg)

**Comment by 3kh0** [comment]
![2022_10_10_0s4_Kleki](https://user-images.githubusercontent.com/58097612/194950602-78b2eabc-bef5-4bfd-8fa7-c95db552747a.png)

@ROnaldMcd0nald You sure you want your profile looking like this?

**Comment by 3kh0** [comment]
Guess so you want it like that
