### ISSUE TITLE
Add a review

### ISSUE THREAD

**Issue by Backyardschool** [3kh0/3kh0.github.io#106]
### Name

The schoolkid

### Review

10/10 I would die without these unblocked games. Very good site. Highly reccomended

### Profile picture

my profile pic

**Comment by 3kh0** [comment]
![2022_10_11_0f7_Kleki](https://user-images.githubusercontent.com/58097612/195099222-3b55ead4-21a3-47a6-9406-9847475d427a.png)

This is just for me to remember your profile pic
