### ISSUE TITLE
Add a review

### ISSUE THREAD

**Issue by eatingcak** [3kh0/3kh0.github.io#108]
### Name

3kh0

### Review

10/10 i love echo he is the best person ever yes he is so cool uwu

### Profile picture

no comment
![Disimba](https://user-images.githubusercontent.com/115575532/195146456-e7274ba6-4188-44e6-8366-1e931ece1260.jpeg)

**Comment by 3kh0** [comment]
Haha, funny name! 😉 I put your name as eatingcak, let me know if you want to change it to something OTHER than my name.
