### ISSUE TITLE
Add Terraria

### ISSUE THREAD

**Issue by Terrafool** [3kh0/3kh0.github.io#109]
### What is this request?

New game

### If you said other in the dropdown above, please specify what below

Add Game

### Please describe the new feature here

Add terraria pls

**Comment by Russell2259** [comment]
@Terrafool Do you have a link?

**Comment by Russell2259** [comment]
Ima add [Scratcharia](https://scratch.mit.edu/projects/46587498). lol

**Comment by 3kh0** [comment]
hey it works!

**Comment by Terrafool** [comment]
Thakns

**Comment by Russell2259** [comment]
@Terrafool Unfortunately I can't add the real terraria, but I added scratcharia a remake of terraria on scratch.mit.edu
