### ISSUE TITLE
retro bowl is not working anymore

### ISSUE THREAD

**Issue by Aquakcola** [3kh0/3kh0.github.io#109]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**
Please add any screenshots to help explain your problem.

**System information**

Operating system (eg ChromeOS or Windows):
Browser:

**Additional context**

**Comment by Piplup7575** [comment]
Are you using 3kh0.github.io/projects/retro-bowl/index.html ?
It works fine for me
![image](https://user-images.githubusercontent.com/88395302/156358808-b9cc5368-be35-4c9c-9a92-3eeabf1ddd2c.png)

**Comment by 3kh0** [comment]
Closing because not enough info

**Comment by Aquakcola** [comment]
Yeah it does now I think it was my chromebook I just reset it and it worked
