### ISSUE TITLE
automated "add review" process

### ISSUE THREAD

**Issue by RuralAnemone** [3kh0/3kh0.github.io#109]
### What is this request?

New feature

### Please describe the new feature here

seeing as there are a heck of a lot of new "hey 3kh0 add my review" issues (and those are the only new issues),
I've kind of been thinking of a way to have a "submit your review" form on the site

see [this cool form I made](https://forms.gle/Tb7QLz8GGBw493Y76) for reference
<br>
<br>
I might even make a bot to append the latest review to `/index.html`...

**Comment by RuralAnemone** [comment]
👍

**Comment by 3kh0** [comment]
Stale
