### ISSUE TITLE
heres a cool game

### ISSUE THREAD

**Issue by 432233333** [3kh0/3kh0.github.io#111]
[https://abw.blue/index_en.php](url)
![67537t](https://user-images.githubusercontent.com/80704713/156369775-696fa753-e70e-4400-be45-1db313b57a2f.jpg)
it's called a better world and i made a thumbnail for it to make it a little easier (also thanks for adding solitaire)

**Comment by 3kh0** [comment]
Hello @432233333, 

I have contacted the developer, for permission on re hosting this game, if they say yes then I can make it.

**Comment by 432233333** [comment]
thats cool thanks for looking
