### ISSUE TITLE
Website blocked (Relay, Github only)

### ISSUE THREAD

**Issue by Erisfiregamer1** [3kh0/3kh0.github.io#112]
**Please describe what happened**

The github.io site was blocked by relay as **games**. Ouch.

**How is the site being blocked?**

Extension, Relay.

**Which of the websites are blocked for you?**

Put a x in the brackets if it is blocked, like this: [X]

- [X] https://3kh0.github.io
- [ ] https://3kh0.vercel.app/
- [ ] https://3kh0.netlify.app/

**Additional context**

Check https://archive.lightspeedsystems.com for checking if the site got blocked... again.

**Comment by 3kh0** [comment]
Hello @Erisfiregamer1,

I have submitted the site for a review and hopefully they change it. For now, you can use the different domains we have!
