### ISSUE TITLE
Why did you not except my comment

### ISSUE THREAD

**Issue by coolman3289** [3kh0/3kh0.github.io#114]
It asked for approval and I don’t see it.

**Comment by hudstir** [comment]
idk, maybe it takes a while?

**Comment by Piplup7575** [comment]
Reload the page, if you attached a image it may take a while to approve

**Comment by coolman3289** [comment]
I did link

**Comment by coolman3289** [comment]
I submit a day ago

**Comment by 3kh0** [comment]
I am the only one that approves comments and sometimes it take a while
