### ISSUE TITLE
Add Rick roll generator

### ISSUE THREAD

**Issue by landehdb** [3kh0/3kh0.github.io#115]
### What is this request?

New feature

### Please describe the new feature here

ps add a Rick Roll generator \
take a look at my review

**Comment by 3kh0** [comment]
What do you mean by Rick roll generator?

**Comment by RuralAnemone** [comment]
*also note that anything like that would either have to be completely frontend or a proxied link

**Comment by nicolasog12** [comment]
add a "perchance" system (like the splash text) that has different links to "Never Gonna Give You Up" aka the rickroll

**Comment by 3kh0** [comment]
@landehdb There are already many of these, no need to reinvent the wheel if there already is one.
