### ISSUE TITLE
Add Sonic robo blast 2

### ISSUE THREAD

**Issue by retrobro** [3kh0/3kh0.github.io#115]
the game is blocked for me so can you port it or something?
here is the link---->https://srb2web.surge.sh/
or ---->https://srb2webbeta.netlify.app/

**Comment by videoconsole** [comment]
the surge one for me isnt blocked but it doesnt load

**Comment by coolman3289** [comment]
Same

**Comment by Piplup7575** [comment]
I get this error on the seccond link, but will look into it!
![image](https://user-images.githubusercontent.com/88395302/158671445-3d9988ab-8410-4894-b2e1-6b4ac1fef31b.png)

**Comment by 3kh0** [comment]
Is this game a flash game?

**Comment by retrobro** [comment]
No

**Comment by 3kh0** [comment]
I can work on adding this tomorrow, hopefully I can add this as well as many other games tomorrow! Stay tuned @retrobro!

**Comment by retrobro** [comment]
Awesome I cant wait!!

**Comment by 3kh0** [comment]
Hmm, on the surge link (https://srb2web.surge.sh/), it gets stuck on the loading screen: 

![image](https://user-images.githubusercontent.com/58097612/159045202-85750f9e-5bd5-4eb3-ad1f-cf78742f72df.png)

Can you try finding another version of the game @retrobro?

**Comment by retrobro** [comment]
I’ll do my best!

**Comment by 3kh0** [comment]
Thnaks!
