### ISSUE TITLE
about:blank not working

### ISSUE THREAD

**Issue by DiscipleOfJava** [3kh0/3kh0.github.io#116]
### Check these boxes to make sure you did everything right!

- [X] I have made sure that this issue does not already exist
- [X] I have submitted screenshots of the error
- [X] You are not using the website on any clones (you are using 3kh0.github.io and nothing else)
- [ ] I just checked all of these boxes without reading the labels

### What browser are you using?

Google Chrome

### What device are you using?

Macbook (or any device running macOS)

### Please explain the issue

Alright, so I've tested this issue a few times.
The about:blank bookmarklet only works on 3kh0's website, and not on any other websites linking to 3kh0.github.io
I did test the feature on a clone, and the website was half-loaded, or not working at all.
Please fix this issue on about:blank bookmarklets.
<img width="1416" alt="Screen Shot 2023-02-16 at 4 57 23 pm" src="https://user-images.githubusercontent.com/111937732/219492045-b7b5c6b8-9623-434c-9b91-fb1c262c6db4.png">
<img width="1416" alt="Screen Shot 2023-02-16 at 4 57 17 pm" src="https://user-images.githubusercontent.com/111937732/219492143-a0e8d7b1-49a7-4b52-ba25-a28fffa72dc0.png">
This image is when loading 3kh0's website, using the about blank bookmarklet, when not on the website eg.  minecraft.net or apple.com

**Comment by Russell2259** [comment]
Currently sub-path clones are not supported due to an issue with service workers. @Russell2259 is working on an alternative solution. See error #95 for more information.

I will look into the about:blank issue.

**Comment by Russell2259** [comment]
@DiscipleOfJava Actually it's not the problem with the about:blank embeder, it is the problem with the website clone. Like I said above service workers don't work with sub-path clones.

**Comment by DiscipleOfJava** [comment]
I was thinking as much, thank you for looking into it.

**Comment by Russell2259** [comment]
Your welcome
