### ISSUE TITLE
Add a review

### ISSUE THREAD

**Issue by sheriffksel** [3kh0/3kh0.github.io#116]
### Name

Sheriffskel

### Review

this is really cool and it cant get blocked, over all 7/6

### Profile picture

![image](https://user-images.githubusercontent.com/114105276/195623453-8c0beddc-30ce-4249-838a-ac14c06e2a87.png)

**Comment by nicolasog12** [comment]
I will try and work on this

**Comment by 3kh0** [comment]
Done in #119
