### ISSUE TITLE
It won’t work unless I use safari or private mode on chrome

### ISSUE THREAD

**Issue by Gamerjames11** [3kh0/3kh0.github.io#117]
### Check these boxes to make sure you did everything right!

- [X] I have made sure that this issue does not already exist
- [X] I have submitted screenshots of the error
- [X] You are not using the website on any clones (you are using 3kh0.github.io and nothing else)
- [ ] I just checked all of these boxes without reading the labels

### What browser are you using?

Google Chrome

### What device are you using?

iPad

### Please explain the issue

Won’t work

**Comment by 3kh0** [comment]
Might be your browser's security settings blocking the service worker

**Comment by Russell2259** [comment]
Could you send a screenshot?

**Comment by Russell2259** [comment]
@Gamerjames11 Might be fixed because of the new game-loading system. Re-open if the problem persists.

**Comment by Gamerjames11** [comment]
It’s fixed
