### ISSUE TITLE
can you add plants vs zombies or the original super Mario bros?

### ISSUE THREAD

**Issue by Tetra789** [3kh0/3kh0.github.io#121]
**Is your feature request related to a problem? Please describe.**
 I like the  games and this is as far as I've gotten for the game request(its a bit confusing the first time)
**Describe the solution you'd like**
them to be added

**Describe alternatives you've considered**
literally any game i like everything you have put on here so far(except the zombies royal as that dosent work for my computer)

.

**Comment by Tetra789** [comment]
maybe Could you add actual mine craft maybe?(if thats not to much to ask)

**Comment by Piplup7575** [comment]
Actual minecraft is not possible, lol.

I'm working on porting mario bros right now, hopefully its added soon.

**Comment by Piplup7575** [comment]
Mario done!
#189
