### ISSUE TITLE
just a few requests

### ISSUE THREAD

**Issue by Tetra789** [3kh0/3kh0.github.io#122]
could you add an emulator or apps(ex.youtube)(im still new so i have no idea if you've dont this already btw)(also i know i already made a request but my friend doent want an account so asked me to ask you. Also could you add fanf games and duck life?

**Comment by Piplup7575** [comment]
I can add duck life!
For the "emulators" you talked about, go under the proxys tab under miscellaneous, and find one that is unblocked, they should all support youtube.
