### ISSUE TITLE
Add Swordbattle.io

### ISSUE THREAD

**Issue by coolguy564738** [3kh0/3kh0.github.io#124]
### What is this request?

New game

### Please describe the new feature here

Pls add swordbattle.io cuz the main link is blocked and the source code is https://github.com/codergautam/swordbattle.io and i don't know how to use it

**Comment by nicolasog12** [comment]
this should be easy enough :)

**Comment by nicolasog12** [comment]
#129

**Comment by 3kh0** [comment]
@coolguy564738 For this game, you will need a server, but those can be blocked pretty easily. So I don't think I will be adding this.

**Comment by coolguy564738** [comment]
sad :(
