### ISSUE TITLE
More Games

### ISSUE THREAD

**Issue by ghost** [3kh0/3kh0.github.io#125]
### What is this request?

New game

### Please describe the new feature here

There's this website that has really cool games and it recently got blocked by my school https://whitespider.netlify.app and yall should put them on ur website. Source codes are https://github.com/ruochenjia/whitespider

**Comment by 3kh0** [comment]
@nicolasog12 I guess all of the games that are on there. If you want to give it a shot, use https://download-directory.github.io/ to download just the games

**Comment by coolguy564738** [comment]
> What game do you want to add tho

whatever games work ig

**Comment by nicolasog12** [comment]
Ill save this as something for ideas for games

**Comment by 3kh0** [comment]
Stale
