### ISSUE TITLE
[Bug] 3kh0 not being deployed to cyclic

### ISSUE THREAD

**Issue by BountyInfinity** [3kh0/3kh0.github.io#125]
### Check these boxes to make sure you did everything right!

- [X] I have made sure that this issue does not already exist
- [X] I have submitted screenshots of the error
- [X] You are not using the website on any clones (you are using 3kh0.github.io and nothing else)
- [ ] I just checked all of these boxes without reading the labels

### What browser are you using?

Google Chrome

### What device are you using?

Other (please note in text field below)

### If you said other above, please specify which device you use

PC on linux

### Please explain the issue

I can't submit a screen shot for some reason. Sorry for not contributing lately, my school district blocked github.io and all of github.

**Comment by Russell2259** [comment]
@BountyInfinity Cyclic actually only supports NodeJS and React applications idk why there is a button there. Try using a different platform to host 3kh0.
