### ISSUE TITLE
Bit life and tab cloak does not work

### ISSUE THREAD

**Issue by coolman3289** [3kh0/3kh0.github.io#126]
**To Reproduce**
1.turn on cloak
2. Does not work

**Expected behavior**
The icon to chnage across the whole website. It only changed on the cloak page

**Screenshots**
Please add any screenshots to help explain your problem.

**System information**

Operating system (eg ChromeOS or Windows):iOS 
Browser:safari

**Additional context**
But life loads forever

**Comment by Piplup7575** [comment]
Works for me on chrome

https://user-images.githubusercontent.com/88395302/157316938-8c5a7e39-ec59-4e59-9981-5cc8a7661fa5.mp4

**Comment by coolman3289** [comment]
Hi, started working, but now it gives me a time limit

**Comment by 3kh0** [comment]
Kinda a duplicate of #118
