### ISSUE TITLE
Add a review

### ISSUE THREAD

**Issue by Darkspeed0** [3kh0/3kh0.github.io#126]
### Name

AgentCube

### Review

I've seen a lot of game sites and 3kh0.github.io definitely stands out it is very easy to navigate, it has a large selection of games,  the ads don't ruin the experience nor get in the way, it has a good amount of tools, it gets updated almost daily and there are new games always being added it's just great.

### Profile picture

![652a3369d93b1affec2cc721a193a8e3](https://user-images.githubusercontent.com/115009467/196061304-8e3e0ed5-edce-4b02-b658-535fa8a8e109.jpg)

**Comment by nicolasog12** [comment]
i will try to work on this (dont tell my teacher :>)

**Comment by Darkspeed0** [comment]
AgentCube* not ancientcube lol

**Comment by nicolasog12** [comment]
whoooops
