### ISSUE TITLE
BITLIFE NOT WORKING!

### ISSUE THREAD

**Issue by LugCentral** [3kh0/3kh0.github.io#127]
**Describe the bug**
When you play bitlife you can play for 20 mins then this pops up and its blocked.

![Screenshot 2022-03-08 14 21 07](https://user-images.githubusercontent.com/99853162/157309982-1675efb3-46db-4493-b627-7c22cd02e6cc.png)

**Comment by coolman3289** [comment]
For me loads forever

**Comment by Piplup7575** [comment]
Works for me

**Comment by LugCentral** [comment]
Yeah Strange.. It is able to load for me but after 20 minutes or so it says limit reached. i will try to troubleshoot aka like clearing cookies to see if that works.

**Comment by 3kh0** [comment]
Duplicate of #118
