### ISSUE TITLE
Couple of games request

### ISSUE THREAD

**Issue by Darkspeed0** [3kh0/3kh0.github.io#127]
### What is this request?

New game

### Please describe the new feature here

I have a couple of game ideas you could add to 3kh0.github.io
Crossy Road Html5 Edition
Apple Knight WebAssembly Edition
Fruit Ninja WebAssembly Edition
Jetpack Joyride Html5 Edition
Angry Birds Chrome Edition
Om Nom Run
I have seen all these games on other websites and think they would be a great addition.

**Comment by 3kh0** [comment]
@Darkspeed0 Can you please send links to some of these?

**Comment by nicolasog12** [comment]
crossy road link: https://now.gg/play/hipster-whale/7870/crossy-road
apple knight?: https://yell0wsuit.page/html5-games/games/apple-knight/
fruit ninja: https://www.agame.com/game/fruit-ninja
jetpackjoyride: https://www.gamepix.com/play/jetpack-joyride
angry birds: could not find anything
om nom run: https://omnomrun.com/

**Comment by Darkspeed0** [comment]
here are the links I found
crossy road: https://yell0wsuit.page/html5-games/games/crossy-road
apple knight: https://yell0wsuit.page/html5-games/games/apple-knight
fruit ninja (source code): https://github.com/ruochenjia/whitespider/tree/main/html5-games/fruit-ninja
jetpack joyride: https://play.famobi.com/jetpack-joyride/A1000-10
angry birds: https://yell0wsuit.page/html5-games/games/angry-birds-chrome
om nom run: https://omnomrun.com/

**Comment by 3kh0** [comment]
### Updated list

- apple knight: [yell0wsuit.page/html5-games/games/apple-knight](https://yell0wsuit.page/html5-games/games/apple-knight)
- fruit ninja (source code): [ruochenjia/whitespider@main/html5-games/fruit-ninja](https://github.com/ruochenjia/whitespider/tree/main/html5-games/fruit-ninja?rgh-link-date=2022-10-17T18%3A32%3A20Z)
- jetpack joyride: [play.famobi.com/jetpack-joyride/A1000-10](https://play.famobi.com/jetpack-joyride/A1000-10)
- angry birds: [yell0wsuit.page/html5-games/games/angry-birds-chrome](https://yell0wsuit.page/html5-games/games/angry-birds-chrome)

**Comment by 3kh0** [comment]
I split this issue to 3 others ones, that make it easier to track
