### ISSUE TITLE
Bitlife is not working and this is the only game that is fun

### ISSUE THREAD

**Issue by kenken277** [3kh0/3kh0.github.io#128]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**
Please add any screenshots to help explain your problem.

**System information**

Operating system (eg ChromeOS or Windows):
Browser:

**Additional context**

**Comment by Piplup7575** [comment]
Screenshots please

**Comment by boomboomaladirt** [comment]
bitlife is mid

**Comment by kenken277** [comment]
> Screenshots please
[Note Mar 10, 2022.pdf](https://github.com/3kh0/3kh0.github.io/files/8228335/Note.Mar.10.2022.pdf)

**Comment by 3kh0** [comment]
Duplicate of #118
