### ISSUE TITLE
Bitlife was working but now it’s done

### ISSUE THREAD

**Issue by kenken277** [3kh0/3kh0.github.io#129]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**
Please add any screenshots to help explain your problem.

**System information**

Operating system (eg ChromeOS or Windows):
Browser:

**Additional context**

**Comment by kenken277** [comment]
I didn’t even get to play

**Comment by Piplup7575** [comment]
Screenshots please?
It works fine for me.

**Comment by kenken277** [comment]
> Screenshots please?
> It works fine for me.
[Note Mar 10, 2022.pdf](https://github.com/3kh0/3kh0.github.io/files/8228322/Note.Mar.10.2022.pdf)

**Comment by 3kh0** [comment]
Duplicate of #118
