### ISSUE TITLE
I got a new game idea!

### ISSUE THREAD

**Issue by Osaka-Classified** [3kh0/3kh0.github.io#13]
you should add ZombsRoyale.io it’s a very popular game that people play!

**Comment by 3kh0** [comment]
> you should add ZombsRoyale.io it’s a very popular game that people play!

Is it a multiplayer game?

**Comment by Osaka-Classified** [comment]
Yeah

**Comment by 3kh0** [comment]
> Yeah

Then that will be very hard due to the servers I have to setup, Have you tried using my proxies? I do not know if ZombsRoyale.io work on them but you could try

**Comment by Osaka-Classified** [comment]
Let’s me see

**Comment by Osaka-Classified** [comment]
With the proxies nah

**Comment by 3kh0** [comment]
> With the proxies nah

Its replit.com unblocked?

**Comment by Osaka-Classified** [comment]
yeah

**Comment by 3kh0** [comment]
> yeah

darn...
