### ISSUE TITLE
Add Super Auto Pets

### ISSUE THREAD

**Issue by Cloduddhjs** [3kh0/3kh0.github.io#130]
### What is this request?

New game

### If you said other in the dropdown above, please specify what below

Add Super Auto Pets to 3kh0

### Please describe the new feature here

The game is “Super Auto Pets”, this website allows you to play it within the browser “https://teamwood.itch.io/super-auto-pets” if you could make it the same way so people can play super auto pets that would be amazing by incorporating it into 3kh0!

**Comment by Rahib777-7** [comment]
ill try this

**Comment by Nebelung-Dev** [comment]
I agree cool game

**Comment by aeiea** [comment]
it already added by @Rahib777-7
