### ISSUE TITLE
Game Request

### ISSUE THREAD

**Issue by 3L33tmakersUnited** [3kh0/3kh0.github.io#130]
I would like to ask if you can find and add an unblocked flash emulator if it isn't hard for you to do. It's fine if you cannot but it would make the site more interesting. BTW ruffle is blocked for my school.

**Comment by Piplup7575** [comment]
How do you even block ruffle?
It's set up so it can run naively, but I'll look into it.

**Comment by 3L33tmakersUnited** [comment]
Ok so to explain, the main ruffle site is blocked so I can't use anything linked to it. I mean I can run it but the main site doesn't work. Thanks for looking into this.
