### ISSUE TITLE
Bitlife not working

### ISSUE THREAD

**Issue by 6942-0** [3kh0/3kh0.github.io#132]
**Describe the bug**
After playing bitlife for about 30 minutes, it says limit reached. You cannot play anymore even after restarting.

**To Reproduce**
1. Go to 'Bitlife'
2. Play for a while
3. See error

**Expected behavior**
Keep on playing like normal
**Screenshots**
Please add any screenshots to help explain your problem.

**System information**
IOS 15 
Safari
Operating system (eg ChromeOS or Windows):
Browser:

**Additional context**

**Comment by coolman3289** [comment]
I played for like 5 when t his happend
