### ISSUE TITLE
Add a review

### ISSUE THREAD

**Issue by YeeticusPrimed** [3kh0/3kh0.github.io#132]
### Name

Xx_ToeLick_xX

### Review

10/10. This is one of the best game websites. It has hundreds of games like subway surfers. Websites like ubg100 do not come close to the amounts of games. This website also has a great UI.

### Profile picture

![PhotoFunia-1663344858](https://user-images.githubusercontent.com/80295356/196280094-53b92c07-2f1c-4410-b2aa-92089fd35a94.jpg)

**Comment by 3kh0** [comment]
I will add it soon





P.S. the owner of ubg100 likes your comment :)

![image](https://user-images.githubusercontent.com/58097612/196317146-142723b5-97ca-495b-a0c8-9d68603d23c3.png)
