### ISSUE TITLE
Add a logo, light mode, and new background

### ISSUE THREAD

**Issue by nicolasog12** [3kh0/3kh0.github.io#133]
### What is this request?

Something else

### If you said other in the dropdown above, please specify what below

fancy styling for the website

### Please describe the new feature here

Basically just Add something in the top saying "3kh0," and maybe change the font, or make it an svg, or do something fancy with it, add it to index.html and projects.html (and any other high importance page), and have it be a sticky element so it will stick to the top. It would add a little charm to the design of the website. Also make the background something like the v2 background, with the little nodes bouncing around.

I don't know if you want to take this into consideration, but it would add some ❇️ bootiful ❇️  to the site.

Also maybe add a light mode for any crazy people out there

if you want me to _attempt_ to do this go ahead and assign me
also looking for any website bootifulizers out there

-  Add logo (DONE)
-  Light mode 
-  Node background

**Comment by nicolasog12** [comment]
![image](https://user-images.githubusercontent.com/99337184/196292618-457df6ac-5b03-4d29-a83c-3d2ab3186c61.png)
Yes i know its cringe and all but something like this (but looks more imaginative)

**Comment by nicolasog12** [comment]
@RuralAnemone 
what

**Comment by nicolasog12** [comment]
do you know how to 'bootifulize'?

**Comment by nicolasog12** [comment]
or add a light mode ig honestly if you can do anything please do it

**Comment by RuralAnemone** [comment]
idk I think dark mode is fine
we could potentially do a poll to see if people actually want light mode but tbh since nobody's explicitly requested it,
it isn't a big deal

**Comment by 3kh0** [comment]
leak of 3kh0.github.io light mode
![2022_10_18_0h8_Kleki](https://user-images.githubusercontent.com/58097612/196457072-08d1ebb0-8292-4f7e-abcb-1c475d5dc33c.png)

**Comment by nicolasog12** [comment]
do you know the color code of the current version's background

**Comment by nicolasog12** [comment]
i have two minutes before i switch and probably wont have my next period to do this since its a "paper period"

**Comment by nicolasog12** [comment]
![image](https://user-images.githubusercontent.com/99337184/196457891-816d2fb6-eb98-4daa-85d4-487fa5e60b1f.png)

**Comment by RuralAnemone** [comment]
ooh nice

**Comment by RuralAnemone** [comment]
> do you know the color code of the current version's background

#1c1c1c

**Comment by nicolasog12** [comment]
ok thanks

**Comment by nicolasog12** [comment]
alr gotta i will work on this when i can

**Comment by nicolasog12** [comment]
can we set this labeled to "help wanted"

**Comment by nicolasog12** [comment]
any updates?

**Comment by 3kh0** [comment]
The logo is nice, light mode, idk if we will do it

**Comment by Bennebotix** [comment]
* We Could Add Some Stuff In "./js/main.js" (which is in all pages right?) Which Could Change Some CSS Or Like Invert Some Things With CSS Invert.

**Comment by 3kh0** [comment]
@Bennebotix yes we can, make sure the user can toggle the setting on the settings page. refer to how I did the Google analytics opt out option.

**Comment by Bennebotix** [comment]
Maybe Something Like This:
```JavaScript
if (window.localStorage.getItem('lm')) {
  document.body.style.backgroundColor = '#eeeeee';
  document.body.style.color = '{Some Color}';
} else {
  document.body.style.backgroundColor = '#1c1c1c';
  document.body.style.color = '{Some Color}';
}
```

**Comment by RuralAnemone** [comment]
maybe something like
```js
if (!window.location.pathname.startsWith("/projects/")) {
  if (window.localStorage.getItem('lm')) {
    document.body.style.backgroundColor = '#eeeeee';
    document.body.style.color = '{Some Color}';
  } else {
    document.body.style.backgroundColor = '#1c1c1c';
    document.body.style.color = '{Some Color}';
  }
}
```

**Comment by Bennebotix** [comment]
* Sure!

**Comment by Bennebotix** [comment]
* Although Of The Page "/projects" I Should Be Light Mode

**Comment by RuralAnemone** [comment]
what

**Comment by RuralAnemone** [comment]
this code just checks if it's on a game page (since all game page paths start with `/projects/`) and if it isn't on a game page then do the dark/light mode code

**Comment by RuralAnemone** [comment]
so if it's a game page it doesn't even get changed to dark mode

**Comment by Bennebotix** [comment]
Well What About The Page With The List Of All The Games On It.
That Should Have Dark/Light Mode.

**Comment by Bennebotix** [comment]
But Yeah.

**Comment by RuralAnemone** [comment]
yea
but that's `/projects.html` so it'll still have dark/light mode
(note it doesn't have the second slash in `/projects/`)

**Comment by Bennebotix** [comment]
Ok.

**Comment by Bennebotix** [comment]
Is There Some Main Css File That Is In All Of The Pages?

I Have Something Like This In ```/css/dump.css``` With The Setting Toggle And All But It Is Not In All Pages:
```CSS
body {
  font-family: Arial, Helvetica, sans-serif;
}
body.darkMode {
  background-color: #1c1c1c;
  color: #eeeeee;
}
body.lightMode {
  background-color: #eeeeee;
  color: #1c1c1c;
}
```

**Comment by Bennebotix** [comment]
Not Totally Done With CSS Tho.

**Comment by RetroWonder** [comment]
> ![image](https://user-images.githubusercontent.com/99337184/196457891-816d2fb6-eb98-4daa-85d4-487fa5e60b1f.png) with background
> 
> ![image](https://user-images.githubusercontent.com/99337184/196458151-da0651ed-d8d9-4743-ae90-f428fad4e229.png) without background

My version ![image](https://media.discordapp.net/attachments/964333717218795520/1038625445513531392/1667697984236.png?width=951&height=549)
