### ISSUE TITLE
Bit life

### ISSUE THREAD

**Issue by Topdawg0015** [3kh0/3kh0.github.io#135]
**Describe the bug**
After a bit the website says limit reached
**To Reproduce**

**Expected behavior**

**Screenshots**
Please add any screenshots to help explain your problem.

**System information**

Operating system (eg ChromeOS or Windows):
Browser:

**Additional context**

**Comment by Piplup7575** [comment]
yEs wE kNoW

**Comment by 3kh0** [comment]
Duplicate of #118
