### ISSUE TITLE
Copy of 3kh0 is not working

### ISSUE THREAD

**Issue by DeveloperJoshua14** [3kh0/3kh0.github.io#135]
### Check these boxes to make sure you did everything right!

- [X] I have made sure that this issue does not already exist
- [ ] I just checked all of these boxes without reading the labels
- [X] I have submitted screenshots of the error
- [X] You are not using the website on any clones (you are using 3kh0.github.io and nothing else)

### What browser are you using?

Google Chrome

### What device are you using?

Chromebook

### Please explain the issue

A lot of things when you "click" them, it just go to the 404 page. I Kind-of fixed it by editing the files and changing the links from "./projects" to "./projects.html"...  Also ALL games don't work? The Blog is broken.... Idk. I am on a Chromebook right now, but I can look at stuff better at home later. 

![image](https://user-images.githubusercontent.com/85973108/220923872-e3d41e86-a495-45a1-9ea5-b2da1e9a9c84.png)
[Screen recording 2023-02-23 8.40.31 AM.webm](https://user-images.githubusercontent.com/85973108/220923932-aee635ea-0458-481a-916c-b65c0195589b.webm)

**Comment by Russell2259** [comment]
@DeveloperJoshua14 It looks like you are not using [3kh0.github.io](https://3kh0.github.io) try updating your fork and copy to the latest version.

**Comment by Russell2259** [comment]
@DeveloperJoshua14 It also looks like your server does not support html files without the `.html`.

You can easily fix this by using an nodejs server with express. You can use the code below and all you need to do is put your copy of 3kh0 in the static folder.

```javascript
const express = require('express');
const path = require('node:path');

app.use(express.static(path.join(__dirname, './static/'), { extensions: ['html'] }));
app.use((req, res) => {
    res.status(404).sendFile('./static/404.html');
});

app.listen(2000, () => console.log('Your 3kh0 server is running'));
```

**Comment by DeveloperJoshua14** [comment]
@Russell2259, I am running all of it on an Nginx Server, you are suggesting a NodeJS Server instead?

I am also _newish_ to webservers/hosting.

**Comment by DeveloperJoshua14** [comment]
@Russell2259, I got it. Thanks!

**Comment by Russell2259** [comment]
@DeveloperJoshua14 It depends I don't know much about Nginx. If you can find a way to run .html files without the .html that would work too.
