### ISSUE TITLE
a BloonsTD colection would be pretty cool, can you add that

### ISSUE THREAD

**Issue by GodTierTrash69** [3kh0/3kh0.github.io#136]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by retrobro** [comment]
i dont think that would work out

**Comment by retrobro** [comment]
cuz they are flash games and flash is not supported anymore.

**Comment by 3L33tmakersUnited** [comment]
well, I think it could work because of Ruffle but I donno.

**Comment by 3kh0** [comment]
We try to make it so that most games do not use ruffle or anything like that so yeah,

**Comment by Piplup7575** [comment]
Currently, the only game using Ruffle is Duck Life, but Ruffle isn't always the best due to the fact that it can only run ActionScript1 and 2 games, while most Flash games are ActionScript3, so until they fix that a lot of games won't be runable through Ruffle.
