### ISSUE TITLE
Can you please add this Cuphead Fan-Game

### ISSUE THREAD

**Issue by boomboomaladirt** [3kh0/3kh0.github.io#138]
I was browsing on the internet and stumbled upon this game, [Cupead: Brothers In Arms](https://omega-glitch.itch.io/cuphead-brothers-in-arms-fan-game) 
And I thought that it would be fun to play it in class. 
If you can, please add it!
Thank you!

**Comment by 3kh0** [comment]
it does not even load lol, sorry
