### ISSUE TITLE
found some more games for you!

### ISSUE THREAD

**Issue by boomboomaladirt** [3kh0/3kh0.github.io#139]
these are all unblocked, for me..

[super Mario 64](https://sm64web.clambam10.repl.co/f.html)

[Shell Shockers](https://shellshock.clambam10.repl.co/)

[Sort The Court](https://sortthecourt.clambam10.repl.co/)

[Crossyroad](https://crossy-road.cyquna.repl.co/)

------------------------------------------------------------------------------------------------------------------------------------------------------------------------

Maybe consider adding them? 

Edit: they are now blocked for me :(

**Comment by Pepperoni-png** [comment]
mario 64 would be really fun.
