### ISSUE TITLE
After going through bitlife very fast it will give you and error screen telling you to go to their website.

### ISSUE THREAD

**Issue by RainBoi666** [3kh0/3kh0.github.io#141]
**Describe the bug**
It will leave you with a screen redirecting to their website saying that the limit was reached,it seems like a shady link.
**To Reproduce**
1. go to the bitlife project
2. start a life and just very quickly age till death
3. start a new life
4. it should give you the screen

**Expected behavior**
It will give you a screen redirecting you to the games "webpage".

**Screenshots**
![Screenshot 2022-03-14 12 15 30 PM](https://user-images.githubusercontent.com/101582571/158214888-d6047208-946d-4f39-bc9b-085ae406308f.png)

**System information**

Operating system (eg ChromeOS or Windows):Acer chromebook
Browser:Google Chrome

**Additional context**

**Comment by Piplup7575** [comment]
Yeah we know, working on it
