### ISSUE TITLE
Add a review

### ISSUE THREAD

**Issue by Morinkash** [3kh0/3kh0.github.io#141]
### Name

3kh0

### Review

Hy can you show me how to code and make games

### Profile picture

nh

**Comment by Morinkash** [comment]
HEllo

**Comment by Morinkash** [comment]
can you show me how to code

**Comment by 3kh0** [comment]
@Morinkash You can use freecodecamp or youtube, that is how I learned.

**Comment by Morinkash** [comment]
thanks
