### ISSUE TITLE
Google snake looks broken.

### ISSUE THREAD

**Issue by coolman3289** [3kh0/3kh0.github.io#142]
**Describe the bug**
When clicking on the updated Google snake, it is too the side and broken (see attached pictures)

**Screenshots**
Below

**System information**

Operating system (eg ChromeOS or Windows):iOS 
Browser:chrome and safari

**Additional context**
Issues are diff on both chrome and safari

**Comment by coolman3289** [comment]
![1169522D-4E13-4C95-AEAC-04C25E5C5D65](https://user-images.githubusercontent.com/64605756/158604195-5146829e-ac6e-426d-9cdd-0361540cf82c.png)
![A4EF24EF-7E09-44B3-A761-38D736C58E49](https://user-images.githubusercontent.com/64605756/158604202-403baec8-0248-404d-ab1f-4bc219da7d1d.png)

these are safari

**Comment by coolman3289** [comment]
![8F33779E-98E5-486A-B7DE-6AAF1AE3D312](https://user-images.githubusercontent.com/64605756/158604261-fbf986ef-bc93-47a2-bf2d-96e3a5d105aa.png)
This is chrome

**Comment by Pepperoni-png** [comment]
It doesn't look broken, just has a bit of white area around it. What I'm confused about is why you can't just google the snake game in google search? is it blocked for you?

**Comment by coolman3289** [comment]
No, but like, it’s still broken.

**Comment by 3L33tmakersUnited** [comment]
I think you have found the special God mode version of snake. It is for people who think regular snake is too easy.

**Comment by 3kh0** [comment]
No there is no “God” mode, Google snake does not work that well on iPads, but we are looking into a fix for it
