### ISSUE TITLE
Add BioBit

### ISSUE THREAD

**Issue by UltraWyatt** [3kh0/3kh0.github.io#144]
### What is this request?

New game

### Please describe the new feature here

There is a game on replit called BioBit. It's Basically Agar.io but unblocked. The Link is https://biobit.bigfatgrub.repl.co/ and the repl is linked at https://replit.com/@bigfatgrub/BioBit It's Fun And Would Be A Great Edition To The Library!

          -UltraWyatt

**Comment by Russell2259** [comment]
@UltraWyatt We can't add this game to 3kh0 because it requires a server that we cannot and will not host.

**Comment by UltraWyatt** [comment]
I Know The Owner Of And Am An Admin If You Need A Host

**Comment by Russell2259** [comment]
@UltraWyatt The problem with that is that it will not work for all users because their organizations and schools may block the server.
