### ISSUE TITLE
Add a review for UltraWyatt

### ISSUE THREAD

**Issue by UltraWyatt** [3kh0/3kh0.github.io#145]
### Name

UltraWyatt

### Review

9.5/10 Has Great Games And There Are So Many Links So It Always Comes Back! Would Recommend! Better Than V3

### Profile picture

old.ultrawyatt.com/favicon.ico

**Comment by Russell2259** [comment]
@UltraWyatt Please send a bigger picture.

**Comment by UltraWyatt** [comment]
https://old.ultrawyatt.com/android-chrome-512x512.png
