### ISSUE TITLE
Madalin Stunt Cars 2 

### ISSUE THREAD

**Issue by urmomheeheheha12345** [3kh0/3kh0.github.io#145]
wasd and arrow keys don't work in madalin stunt cars; I cannot move it says on the accelerator that the speed is going up but the car isn't moving
@3kh0  help

**Comment by Piplup7575** [comment]
works for me

**Comment by 3L33tmakersUnited** [comment]
Are you sure that you do not have the gear for manual in Neutral or N. That will stop the car from moving. You can solve it by checking if there is MG or AG in the speedometer or thingy with the speeds.

**Comment by 3kh0** [comment]
It works for me, please include what device you are using next time!
