### ISSUE TITLE
Please add Now.gg Roblox

### ISSUE THREAD

**Issue by ezez2009lol** [3kh0/3kh0.github.io#148]
Just a quick suggestion, can you please add now.gg roblox that actually loads and doesn't say every single time "Something went wrong".

(Now.gg roblox is roblox but mobile it still works on any device)

**Comment by Piplup7575** [comment]
no

**Comment by 3kh0** [comment]
@ezez2009lol we do not support roblox and never will. If you are wondering why, this might explain it: https://www.youtube.com/watch?v=_gXlauRB1EQ

**Comment by ezez2009lol** [comment]
Most proxies don't work but thanks ig.

**Comment by RuralAnemone** [comment]
from my experience uv works just fine for now.gg
