### ISSUE TITLE
Add Bread and Fred

### ISSUE THREAD

**Issue by Alcach0fa** [3kh0/3kh0.github.io#149]
### What is this request?

New game

### Please describe the new feature here

I would like to play Bread and Fred, please do it posible

**Comment by 3kh0** [comment]
Please provide links to the game.

**Comment by SipSup3314** [comment]
man wants to play a steam desktop game on 3kh0.github.io

**Comment by Russell2259** [comment]
Is this possible?

**Comment by SipSup3314** [comment]
no. its a desktop game

**Comment by Russell2259** [comment]
Ok
