### ISSUE TITLE
Comments are broken.

### ISSUE THREAD

**Issue by Pepperoni-png** [3kh0/3kh0.github.io#150]
**Describe the bug**
The comments section does not load

**To Reproduce**
1. Go to 3kh0.github.io
2. Click on Comments
3. See error

**Expected behavior**
Viewing a list of comments.

**Screenshots**
In Comments

**System information**

Operating system:ChromeOS
Browser:Chrome

**Additional context**
None

**Comment by Pepperoni-png** [comment]
![image](https://user-images.githubusercontent.com/101728754/159025419-f218ff67-852f-4cb9-b1a6-4b132ca9c301.png)

**Comment by 3kh0** [comment]
Yes, this is a issue we are looking into. This is not on our side, but the server hosting. We can not do anything to fix that, sorry!

**Comment by Pepperoni-png** [comment]
Oh ok.
