### ISSUE TITLE
Why click the play button

### ISSUE THREAD

**Issue by 3kh0** [3kh0/3kh0.github.io#151]
### What is this request?

New feature

### Please describe the new feature here

When going to play a game, you click on the title, then you have to click play, why is that

**Comment by SipSup3314** [comment]
That's just Ruffle. I think you can set an autoplay parameter in the js to bypass that.

**Comment by 3kh0** [comment]
No, this is on all games

**Comment by SipSup3314** [comment]
ohhhhh lemme check

**Comment by SipSup3314** [comment]
yea probably some random whatchacallit that you implemented when making v4 and forgot to remove.

**Comment by Russell2259** [comment]
I added it.

**Comment by SipSup3314** [comment]
cool problem solved
