### ISSUE TITLE
Update Retro Bowl to its current version 

### ISSUE THREAD

**Issue by Osaka-Classified** [3kh0/3kh0.github.io#151]
### What is this request?

New game

### Please describe the new feature here

Please Update Retro Bowl to its current version please I am just so bored with the current version that the site has

The current version on the site is v1.4.9.3, upgrade it to v1.5.5.7

**Comment by 3kh0** [comment]
There is a new version???

**Comment by Piplup7575** [comment]
@3kh0 send me the link i'll update it

**Comment by Osaka-Classified** [comment]
Find it on Poki website

**Comment by 3kh0** [comment]
![image](https://user-images.githubusercontent.com/58097612/206942955-1a7a2002-fa3f-4b62-ae76-7f3021643b5e.png)

pain

**Comment by 3kh0** [comment]
Done! 1e5fdabf5c36bd7c6d338f06be316f8b8ee07e65
