### ISSUE TITLE
Add a review

### ISSUE THREAD

**Issue by GDSlatherycGithub** [3kh0/3kh0.github.io#152]
### Name

3xion

### Review

10/10 great website. Echo is adding games like daily and I've used this basically every day since discovering it, which, now that I think about it, is probably not a good thing. Nevertheless, this is genuinely one of the best game websites you'll ever find. Sincerely, 3xion (Exion)

### Profile picture

![untitled (1)](https://user-images.githubusercontent.com/88562716/197190406-7096fbca-7aff-4236-bb21-9c9ecef7fade.png)

**Comment by 3kh0** [comment]
Your review has been trimmed a little to make it fit in the box
