### ISSUE TITLE
Add WebXash

### ISSUE THREAD

**Issue by ThatSanicOfficial** [3kh0/3kh0.github.io#153]
### What is this request?

New game

### Please describe the new feature here

Is it possible to add WebXash to the website. It is a really great game that can allow you to play near replicas of GoldSrc games. I would really like to play Half-Life: Uplink during class!

Link: [WebXash](https://x8bitrain.github.io/webXash/)

**Comment by Rahib777-7** [comment]
ill try this after run 2 is added

**Comment by nicolasog12** [comment]
https://x8bitrain.github.io/webXash/

**Comment by 3kh0** [comment]
Github https://github.com/x8BitRain/webXash

**Comment by Russell2259** [comment]
Added by @Rahib777-7
