### ISSUE TITLE
plz add stickman fighter epic battle

### ISSUE THREAD

**Issue by TheEliteSlothie** [3kh0/3kh0.github.io#155]
Add Stickman Fighter: Epic Battle please! Thanks!

**Comment by 3kh0** [comment]
Please submit a link to a existing page

**Comment by 3kh0** [comment]
Inactivy

**Comment by TheEliteSlothie** [comment]
> Please submit a link to a existing page

https://poki.com/en/g/stickman-fighter-epic-battle
