### ISSUE TITLE
Add Krunker

### ISSUE THREAD

**Issue by Zikun1234** [3kh0/3kh0.github.io#156]
### What is this request?

New game

### Please describe the new feature here

pls add krunker and more driving games

**Comment by 3kh0** [comment]
Please submit links

**Comment by retrobro** [comment]
here is krunker > https://krunker.io/

**Comment by Piplup7575** [comment]
This may not the possible, due to the multiplayer functionality.
Try using a proxy, there are a ton on the proxies page.

**Comment by 3kh0** [comment]
@Piplup7575 we could try and host it on replit...
