### ISSUE TITLE
add some random dating sim or p#$n site to the 3kh0 as a joke

### ISSUE THREAD

**Issue by GodTierTrash69** [3kh0/3kh0.github.io#158]
### What is this request?

New feature

### Please describe the new feature here

just add something stupidly inapropriate like HuniePop, or a proxy that only go to P#rnHub, i know you probably wont do this, but you could maybe do it on april 1st as a joke, thank you! bye.

**Comment by retrobro** [comment]
u need god or Jesus.

**Comment by Piplup7575** [comment]
No.

**Comment by 3kh0** [comment]
Yeahhhhh no
