### ISSUE TITLE
Website blocked (Securly/FortiGuard)

### ISSUE THREAD

**Issue by Pepperoni-png** [3kh0/3kh0.github.io#160]
### Check these boxes to make sure you did everything right!

- [X] I have made sure that this issue does not already exist
- [X] I have submitted screenshots of the error
- [X] You are not using the website on any clones (you are using 3kh0.github.io and nothing else)
- [ ] I just checked all of these boxes without reading the labels

### What browser are you using?

Google Chrome

### What device are you using?

Chromebook

### Please explain the issue

My device uses 2 kinds of blockers. "Securly" which is a chrome extension, and "FortiGuard/FortiNet" which I think is linked to the school router or something. I open the website today to find it got blocked by the fortiguard one! Please fix ths if you can D: 

![image](https://user-images.githubusercontent.com/101728754/159250949-19105b87-c02e-40e4-add1-f2c4248ea83e.png)

**Comment by Pepperoni-png** [comment]
Note, the entire 3kh0 site got blocked meaning anything on or from it is also blocked (like the changelog)

**Comment by Piplup7575** [comment]
Try using a proxy to access the site!
https://github.com/binary-person/womginx

**Comment by Pepperoni-png** [comment]
Oh, thanks!!! :O

**Comment by Pepperoni-png** [comment]
Update, that's blocked too :/
![image](https://user-images.githubusercontent.com/101728754/159255114-48bb0f32-9f43-4149-bdac-007c49187f0a.png)

**Comment by Pepperoni-png** [comment]
update, that's blocked too :/
![Screenshot 2022-03-21 7 46 56 AM](https://user-images.githubusercontent.com/101728754/159255374-16730cbd-a1f4-4aaa-a584-2901b3615f98.png)

**Comment by Pepperoni-png** [comment]
Okay so I figured out I had a bookmark with womginx in it, but that keeps sending deceptive site errors every time I try to enter 3kh0 site with no "continue anyway" option..

**Comment by Pepperoni-png** [comment]
Update 2, for some reason its unblocked again! Woohoo! Idk how its unblocked but I'll take it
![image](https://user-images.githubusercontent.com/101728754/159262946-baa84bc2-fdf5-4e31-98fe-858aaf6346a7.png)

**Comment by Piplup7575** [comment]
Yay!
