### ISSUE TITLE
mind if i can be a contributor

### ISSUE THREAD

**Issue by Aspaceman527** [3kh0/3kh0.github.io#161]
### What is this request?

Something else

### If you said other in the dropdown above, please specify what below

look at title

### Please describe the new feature here

plz re-label this. I know basic js and HTML. I also go on Codecademy way too much. I also want to make a lot of unblocked games and can't make people go on my site. I won't make too many changes but I will do the best I can.
(you may close this once you read this)

**Comment by Piplup7575** [comment]
Yeah!
I was made one because I added a bunch of games through pull requests, figure out how they work and make a few and 3kh0 may add you!
https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/about-pull-requests

**Comment by 3kh0** [comment]
@Aspaceman527, if you want to help, you can make Pull requests that get merged, but asking just like that will not help, plus you have never contributed to the repo.
