### ISSUE TITLE
Game Requests

### ISSUE THREAD

**Issue by 1mBounty** [3kh0/3kh0.github.io#165]
### What is this request?

New game

### Please describe the new feature here

Can you add the best of the games of the following websites.
https://lichgames.s3.amazonaws.com/index.html
https://s3.amazonaws.com/crazygames-unblocked/index.html
https://www.learn4good.com/games/play-mobile-games-online8.html
https://coolmathgames.com

**Comment by 3kh0** [comment]
@1mBounty Please just tell us the games you want to add, not the website
