### ISSUE TITLE
Game Request

### ISSUE THREAD

**Issue by ThatOneMexican** [3kh0/3kh0.github.io#166]
### What is this request?

New game

### If you said other in the dropdown above, please specify what below

How About a Country Ball Game

### Please describe the new feature here

Dictators:No Peace, i do not have any links to the game, highly sorry. But i would love for you and your team to add this game into well your game

**Comment by Piplup7575** [comment]
Any links?

**Comment by 3kh0** [comment]
uhhh @ThatOneMexican we can not figure out what game you want
