### ISSUE TITLE
love web sight you should add ark survivle evovled  

### ISSUE THREAD

**Issue by humanaaaa** [3kh0/3kh0.github.io#168]
### Name

the carman123

### Review

9/10 love web sight you should add ark survivle evovled  

### Profile picture

idk

**Comment by 3kh0** [comment]
Hope you are fine with this as your profile picture

![ezgif com-gif-maker (1)](https://user-images.githubusercontent.com/58097612/197659189-7796436b-f017-47cc-a438-850f50cf2eb9.gif)
