### ISSUE TITLE
[Bug] Github page is down 

### ISSUE THREAD

**Issue by 17847814871842** [3kh0/3kh0.github.io#168]
### Check these boxes to make sure you did everything right!

- [X] I have made sure that this issue does not already exist
- [X] I have submitted screenshots of the error
- [X] You are not using the website on any clones (you are using 3kh0.github.io and nothing else)
- [ ] I just checked all of these boxes without reading the labels

### What browser are you using?

Google Chrome

### What device are you using?

Chromebook

### Please explain the issue

Site not found (404 error)
![image](https://user-images.githubusercontent.com/123099221/223117007-d9dfb79c-8a65-4ddd-a0f1-04883016d9fe.png)

**Comment by 3kh0** [comment]
Working on fixing this

**Comment by 3kh0** [comment]
Done
