### ISSUE TITLE
Main website is not working

### ISSUE THREAD

**Issue by VillainsRule** [3kh0/3kh0.github.io#169]
### Check these boxes to make sure you did everything right!

- [ ] I have made sure that this issue does not already exist
- [X] I have submitted screenshots of the error
- [X] You are not using the website on any clones (you are using 3kh0.github.io and nothing else)
- [ ] I just checked all of these boxes without reading the labels

### What browser are you using?

Google Chrome

### What device are you using?

Chromebook

### Please explain the issue

The site displays a 404 page.
![image](https://user-images.githubusercontent.com/101288516/223186379-09e8654e-6fc0-4335-95ed-1c5056e09d4a.png)

is index.html healthy?

**Comment by Hunter2023gg** [comment]
same mine says the same thing

**Comment by Russell2259** [comment]
It's probably a problem with how github pages is setup.

**Comment by Hunter2023gg** [comment]
what

**Comment by Russell2259** [comment]
nvm

**Comment by 17847814871842** [comment]
it says site not found, it has been on and off all day

**Comment by Russell2259** [comment]
You can use an alternative site for the time being.

**Comment by ggsdfff** [comment]
My singleplay & multiplayer are chrashed, can you please give me a list on how to fix them?? I mostly want my singleplayer back. Please help. It has been like this for around a month and i have been trying to find somebody to help me. could you help me?? i dont understand videos and related, it would help me if i get a list on how to fix it, ty

**Comment by Russell2259** [comment]
You can use mine also: [https://russell2259.github.io/3kh0.github.io/](https://russell2259.github.io/3kh0.github.io/)

**Comment by ggsdfff** [comment]
the links you send are restricted btw

**Comment by Russell2259** [comment]
@ggsdfff You will have to wait for the site to be back up for you to get your singleplayer world.

**Comment by ggsdfff** [comment]
oh, okay. when do you think it will be back up?? lol

**Comment by Russell2259** [comment]
@ggsdfff I have no idea. Just waiting on Echo to troubleshoot the problem as I can't do anything.

**Comment by ggsdfff** [comment]
okay, Thanks

**Comment by ggsdfff** [comment]
> > the links you send are restricted btw
> 
> https://anno.villainsrule.xyz/games/3kh0 is really restricted? belief fail.

lol, yeah.

**Comment by Russell2259** [comment]
@VillainsRule .xyz domain endings aren't usually trustworthy.

**Comment by ggsdfff** [comment]
> i mean it's my personal shit so like fucking blockers

yeah, i have school, so all the teachers are brutal, lol. a lot of the app that say "unblocked" are not for schools, it is so dumb.

**Comment by Russell2259** [comment]
This issue already exists but it was closed... I'll keep it open for now.

**Comment by ggsdfff** [comment]
> This issue already exists but it was closed... I'll keep this open for now.

lol okay. ik it exists lol.😁

**Comment by ggsdfff** [comment]
ill be back tommorow. Thanks for the info abou eaglercraft 1.52!! i did not know it was not on. Ty

**Comment by 3kh0** [comment]
This is a constant issue we are working to fix

**Comment by 3kh0** [comment]
Fixed

**Comment by ggsdfff** [comment]
wdym

**Comment by ggsdfff** [comment]
> Fixed

wdym? btw, i cant go on eaglercraft rn

**Comment by 3kh0** [comment]
that is a issue we are aware of

**Comment by ggsdfff** [comment]
> that is a issue we are aware of

okay

**Comment by imranplayz-dev** [comment]
Fork another copy. It should auto deploy
