### ISSUE TITLE
Hollow Knight

### ISSUE THREAD

**Issue by CookieBoyo** [3kh0/3kh0.github.io#170]
### What is this request?

New game

### Please describe the new feature here

That would be absolutely FANTASTIC! Any kind of demo, remake, or anything of Hollow Knight would be amazing!

**Comment by 3kh0** [comment]
I looked into the game, Hollow Knight. It costs around 15$ on steam. I would not be able to add this due to the fact that it is paid and I make it, it would be a ripoff and the devs for the original game would try and sue me. Sorry!
