### ISSUE TITLE
Epic Review

### ISSUE THREAD

**Issue by DAPOKEDOOD** [3kh0/3kh0.github.io#170]
### Name

Pokeboy

### Review

oh my god very educational site best education games, lets go.

### Profile picture

![7d8aaece38d063c45f116aac5de55e1c](https://user-images.githubusercontent.com/104868958/197661730-4619c9eb-e6c7-4bbd-800a-00517cbc7003.jpg)

**Comment by 3kh0** [comment]
![2022_10_25_0f3_Kleki](https://user-images.githubusercontent.com/58097612/197780297-f5afbb79-54c4-47bb-a5c8-d4d3c96cb7b8.png)

your profile pic will look like this
