### ISSUE TITLE
some of the pokemon games would be cool to add

### ISSUE THREAD

**Issue by GodTierTrash69** [3kh0/3kh0.github.io#171]
### What is this request?

New game

### Please describe the new feature here

ive been using the HolyUnblocker for a lot of games, but the pokemon roms they have dont have working saves, you can get the entirety of FireRed, Crystal, and Emerald on the EmuLibrary page of HU, but the saves dont work on any of them. this makes them really hard to play, i dont really know how to code, (if i did i would just copy paste the games i want and add working saves) but if you could add some of these games with working saves, that would be pretty cool!

**Comment by 3kh0** [comment]
i see, i will look into it

**Comment by GodTierTrash69** [comment]
thanks m8!
