### ISSUE TITLE
Add Stickman Hook

### ISSUE THREAD

**Issue by Bountylnfinity** [3kh0/3kh0.github.io#174]
### What is this request?

New game

### Please describe the new feature here

Stickman Hook.
https://github.com/StickmanHook/StickmanHook.github.io

**Comment by 3kh0** [comment]
If anyone else can do this, please do. If you can't, I will do it

**Comment by 1mBounty** [comment]
I can do it on the weekend.

**Comment by 3kh0** [comment]
I will do it today

**Comment by 3kh0** [comment]
I can't figure it out, if someone else is willing to, please comment below!

**Comment by 1mBounty** [comment]
I’ll try to do it on the weekend.

**Comment by Bountylnfinity** [comment]
@3kh0 I also am having problems, I think we should stop trying to put this on the website.

**Comment by 3kh0** [comment]
Ok i did it d6c2ffec960c62b3167ffa7a4f9a5d3e04e55143
