### ISSUE TITLE
Blocked 3kh0 website

### ISSUE THREAD

**Issue by smileman51** [3kh0/3kh0.github.io#176]
### What is this request?

Something else

### If you said other in the dropdown above, please specify what below

Blocked 3kh0 website

### Please describe the new feature here

At our school, this thing called iboss blocked the 3kh0 website. If you can, can you make copies of your website on other links so people at our school can access it? Thanks a ton - smileman51

**Comment by derinpilge** [comment]
nvm ur not

**Comment by smileman51** [comment]
@derinpilge the new link you gave me "3kh0.github.io." also doesn't work because the iboss extension blocks anything starting with 3kh0

**Comment by Piplup7575** [comment]
Have you tried all of the links?
Join the [Discord](https://discord.gg/44yAbMWbHb), there are more links there for you to use

**Comment by smileman51** [comment]
> Have you tried all of the links? Join the [Discord](https://discord.gg/44yAbMWbHb), there are more links there for you to use

The discord link is expired

**Comment by 3kh0** [comment]
> > Have you tried all of the links? Join the [Discord](https://discord.gg/44yAbMWbHb), there are more links there for you to use
> 
> The discord link is expired

https://discord.gg/fpRK7Qve

**Comment by smileman51** [comment]
> > > Have you tried all of the links? Join the [Discord](https://discord.gg/44yAbMWbHb), there are more links there for you to use
> > 
> > 
> > The discord link is expired
> 
> https://discord.gg/fpRK7Qve

That one is also expired. Sorry

**Comment by 3kh0** [comment]
- https://discord.gg/6d2MNXWVmV

**Comment by smileman51** [comment]
> * https://discord.gg/6d2MNXWVmV

thanks
