### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by GodTierTrash69** [3kh0/3kh0.github.io#177]
### Check these boxes to make sure you did everything right!

- [X] I have made sure that this issue does not already exist
- [X] I have submitted screenshots of the error
- [X] You are not using the website on any clones (you are using 3kh0.github.io and nothing else)
- [X] I just checked all of these boxes without reading the labels

### What browser are you using?

Google Chrome

### What device are you using?

Chromebook

### Please explain the issue

in the slope game, theirs a glicth that happens every now and then, that makes it so that the road thing the ball slides on dosnt generate, and you die, theirs also a glicth that makes you phase through walls sometimes, and tons others, it a really buggy game in general, can you fix that?

**Comment by 3kh0** [comment]
yes, this is a issue with unity itself and we can not fix it, just try reloading the page.
