### ISSUE TITLE
Add Mutilate A Doll 2

### ISSUE THREAD

**Issue by Haxnstuff** [3kh0/3kh0.github.io#179]
### What is this request?

New game

### Please describe the new feature here

Mutilate A Doll 2 (MAD2)

**Comment by Piplup7575** [comment]
Do you have the blocked link?

**Comment by Haxnstuff** [comment]
Sure, here you go

<goog_384246131>
https://potatoinmypocket.weebly.com/mutilate-a-doll-2.html

**Comment by 3kh0** [comment]
It is flash, @Piplup7575 can you work on this?

**Comment by Haxnstuff** [comment]
yeah, sure!

**Comment by Piplup7575** [comment]
Yeah let me find the sbf

**Comment by Piplup7575** [comment]
Woops, not currently possible due to ruffle limitations.
![image](https://user-images.githubusercontent.com/88395302/164074535-d97059d9-61cb-4a47-92d0-ed37f1a49f3a.png)
