### ISSUE TITLE
Add OVO

### ISSUE THREAD

**Issue by WizardCraft112** [3kh0/3kh0.github.io#180]
### What is this request?

New game

### Please describe the new feature here

This game is OVO. It's a 2d platformer made by DedraGames. Here is the link:
https://dedragames.com/games/ovo/1.4/

**Comment by 1mBounty** [comment]
I can do it tomorrow

**Comment by Bennebotix** [comment]
Hey Bodhi.
The Other Issue Has The Code.

**Comment by 1mBounty** [comment]
I already have a fork

**Comment by 3kh0** [comment]
Code: https://github.com/Bennebotix/hereisovo

**Comment by 1mBounty** [comment]
sorry there was a bug so i will do it tomorrow.

**Comment by 1mBounty** [comment]
also the hover bot arena error
