### ISSUE TITLE
Add Deepest Sword

### ISSUE THREAD

**Issue by Adithr123** [3kh0/3kh0.github.io#184]
Hello echo! I was just wondering if you could add Deepest Sword to the website. Here is the itch.io link -> https://cosmicadventuresquad.itch.io/deepest-sword. Thanks for your time!

**Comment by 3kh0** [comment]
Iframed game: https://v6p9d9t4.ssl.hwcdn.net/html/4017918/index.html

**Comment by SipSup3314** [comment]
@3kh0 you can actually download the itch desktop client and download the web files without ripping the site.

**Comment by Adithr123** [comment]
Echo, can you add it to the website? The iframe is blocked at school.

**Comment by 3kh0** [comment]
@SipSup3314 That works??? I am going to have to try that.

**Comment by 3kh0** [comment]
[deepest-sword.zip](https://github.com/3kh0/3kh0.github.io/files/10945440/deepest-sword.zip)

if anyone can upload this, you get contributer lol

**Comment by 3kh0** [comment]
Done by @Russell2259
