### ISSUE TITLE
Move games.json to 3kh0/3kh0-Assets?

### ISSUE THREAD

**Issue by aeiea** [3kh0/3kh0.github.io#189]
### What is this request?

Something else

### If you said other in the dropdown above, please specify what below

Should we move games.json to 3kh0/3kh0-Assets?

### Please describe the new feature here

If we moved it, then we wouldn't need to manually update our Gitlab/Bitbucket mirrors to host on Vercel/Cloudflare pages.

**Comment by Russell2259** [comment]
Not really a good idea, the games.json file is pretty light in terms of storage space plus if the cdn were to be blocked the games would not show up.

**Comment by SipSup3314** [comment]
Dude's got a point. Also, having a central server for json files would just create one more thing to get blocked.

**Comment by Russell2259** [comment]
You could use my [3kh0-CDN](https://github.com/Russell2259/3kh0-CDN) that serves the games.json file proxied from 3kh0 and just change the URL it fetches games from.

**Comment by aeiea** [comment]
My reason: 
I host my own instances(not naming in fear they get blocked), and because GitHub is broken for me on my school Chromebook(can't sync), I have to manually delete the games.json file and replace it(GitHub used to work... but not anymore)
It would also have some logistics benefits if we were to merge it with 3kh0/3kh0-Assets, as we wouldn't need to create 2 pull requests(one for the assets repo and one for the main site).

**Comment by Russell2259** [comment]
@aeiea If syncing is a problem for you, you could use my [3kh0-CDN](https://github.com/Russell2259/3kh0-CDN) nodejs server that automatically syncs with the official games.json file. All you would need to do to use it in your self-hosted instance is change the URL where the games.json fetches from, to your server URL.

**Comment by Russell2259** [comment]
I am going to close this for now.
