### ISSUE TITLE
[Bug] Discord invite link expired

### ISSUE THREAD

**Issue by nicolasog12** [3kh0/3kh0.github.io#193]
### Check these boxes to make sure you did everything right!

- [X] I have made sure that this issue does not already exist
- [X] I have submitted screenshots of the error
- [X] You are not using the website on any clones (you are using 3kh0.github.io and nothing else)
- [ ] I just checked all of these boxes without reading the labels

### What browser are you using?

Google Chrome

### What device are you using?

Chromebook

### Please explain the issue

The discord invite link is expired or we do not permission to join the discord.
![image](https://user-images.githubusercontent.com/99337184/161777009-9f505d1d-af05-4ad1-bc9d-4ef3bb2f9b23.png)

**Comment by Piplup7575** [comment]
Which link are you using?

**Comment by 3kh0** [comment]
Can you send me the link?

**Comment by 3kh0** [comment]
what link are you using?

**Comment by 3kh0** [comment]
Use this link: https://discord.gg/6d2MNXWVmV
