### ISSUE TITLE
Add Smash Karts 

### ISSUE THREAD

**Issue by legofrog** [3kh0/3kh0.github.io#196]
### What is this request?

New game

### Please describe the new feature here

Please add the game [https://smashkarts.io](url)

**Comment by 3kh0** [comment]
Fixed URL: https://smashkarts.io

I will work on this!

**Comment by legofrog** [comment]
Thanks!

**Comment by legofrog** [comment]
Found an open git of it https://github.com/peytonplayz585/SmashKarts

**Comment by legofrog** [comment]
Found a link to the code! https://github.com/peytonplayz585/SmashKarts

**Comment by Piplup7575** [comment]
Looking into this rn

**Comment by Piplup7575** [comment]
Added!
