### ISSUE TITLE
Add Shogun Showdown

### ISSUE THREAD

**Issue by 3kh0** [3kh0/3kh0.github.io#197]
### What is this request?

New game

### Please describe the new feature here

![image](https://user-images.githubusercontent.com/58097612/224414887-e7262ea0-dd6f-43cc-a754-d82448f41f9e.png)

itch.io link: https://roboatino.itch.io/shogunshowdown

Zip file to upload: [ShogunShowdown_WebGL.zip](https://github.com/3kh0/3kh0.github.io/files/10945521/ShogunShowdown_WebGL.zip)

**Comment by DapperLS-Bot-Dev** [comment]
I could do it if you want, I'll open a pull request tonight.

**Comment by DapperLS-Bot-Dev** [comment]
Im getting error "Unable to load file Build/ShogunShowdown_WebGL.framework.js.gz! Check that the file exists on the remote server. (also check browser Console and Devtools Network tab to debug)."
I have no clue what I'm doing when it comes to WebGL, so I'm staying out of this one.

**Comment by Russell2259** [comment]
Same

**Comment by 3kh0** [comment]
Yeah, I am also trying to figure out what is going on.

**Comment by DapperLS-Bot-Dev** [comment]
it might just be a bug when the creator exported the game

**Comment by DapperLS-Bot-Dev** [comment]
By the way, can I have collaborator so I can approve pull requests for games on 3kh0 and 3kh0Assets repos?

**Comment by 3kh0** [comment]
Hmm, I will see if I can convert it so this does not happen

**Comment by DapperLS-Bot-Dev** [comment]
I googled it, and it said to rebuild the game, or use a .htaccess file. GitHub Pages does not support this, so the only way to get it to work is to turn off Strict MIME type checking. This is not safe, and not possible on school chromebooks. I think we have to close this as not planned.

**Comment by 3kh0** [comment]
I will keep on playing with this to see what i can do

**Comment by SipSup3314** [comment]
I can decompile the exe and export it correctly in Unity. It will take a while but I might be able to

**Comment by DapperLS-Bot-Dev** [comment]
If there is a decompiler in python, you can use Google collab with a Jupiter notebook to do it quickly.

**Comment by SipSup3314** [comment]
I'll just do what I plan on doing and I don't know what I plan on doing yet. That is a possibility

**Comment by Russell2259** [comment]
It got added
