### ISSUE TITLE
Add Fancy Pants Adventures And Riddle Schools

### ISSUE THREAD

**Issue by 1mBounty** [3kh0/3kh0.github.io#197]
### What is this request?

New game

### Please describe the new feature here

I remember when Fancy Pants adventures was on the site but now it is gone, same with the Riddle Schools. Were they removed because of licensing issues? Just wondering. Me and my friends are big fans of Fancy Pants and would appreciate it to see it on the website again.

**Comment by 3kh0** [comment]
@1mBounty Please see if you can find any surviving copies of this game.

**Comment by 1mBounty** [comment]
https://poki.com/en/g/fancy-pants

**Comment by 1mBounty** [comment]
https://armorgames.com/play/301/fancy-pants-adventures

**Comment by 1mBounty** [comment]
idk if they work since my school blocked them

**Comment by 1mBounty** [comment]
why was Fancy Pants removed?

**Comment by Repsicoder** [comment]
There is one on crazygames.

**Comment by Repsicoder** [comment]
https://www.crazygames.com/game/fancy-pants-adventure-world

**Comment by 1mBounty** [comment]
@Repsicoder I am going to add OvO tomorrow

**Comment by Repsicoder** [comment]
Ok
