### ISSUE TITLE
Zombs Royale Doesn't Work

### ISSUE THREAD

**Issue by THEBEST1278** [3kh0/3kh0.github.io#197]
### Check these boxes to make sure you did everything right!

- [X] I have made sure that this issue does not already exist
- [X] I have submitted screenshots of the error
- [X] You are not using the website on any clones (you are using 3kh0.github.io and nothing else)
- [ ] I just checked all of these boxes without reading the labels

### What browser are you using?

Google Chrome

### What device are you using?

Chromebook

### Please explain the issue

I Went On Zombs Royale and it said "the link" couldn't connect
![Screenshot 2022-04-08 7 08 43 PM](https://user-images.githubusercontent.com/99035705/162548357-02745a6c-c155-4a0d-a43b-0035765d2463.png)

**Comment by legofrog** [comment]
Been doing the same for me!

**Comment by 3kh0** [comment]
zombs royale has been having issues and we are aware of it
