### ISSUE TITLE
Add OvO

### ISSUE THREAD

**Issue by Bennebotix** [3kh0/3kh0.github.io#202]
### What is this request?

New game

### Please describe the new feature here

I Have The Code To OvO:
https://github.com/Bennebotix/hereisovo

If Any One Could Add It I Am Not Very Available I Am Working On Light Mode.

**Comment by 1mBounty** [comment]
If you looked at the other issues then you would see that i’m doing it tomorrow.

**Comment by 3kh0** [comment]
Duplicate of #180
