### ISSUE TITLE
Cloning repository is huge - 3.8gb

### ISSUE THREAD

**Issue by CaedenPH** [3kh0/3kh0.github.io#203]
### What is this request?

Something else

### If you said other in the dropdown above, please specify what below

Cloning the repository is 3.8gb

### Please describe the new feature here

As the title says, when cloning this repository, the source code is small, sub 50mb, but the `.git` directory contains 3.8gb of objects which I assume are what used to be the games - 
I'm not entirely sure how, but I think something should be purged in order to fix the .git objects

**Comment by 3kh0** [comment]
Hmm, the games are not stored on this repo, I am looking for ways to condense the code even more.

**Comment by CaedenPH** [comment]
> Hmm, the games are not stored on this repo, I am looking for ways to condense the code even more.

No, I believe that the reason the repository is so large is because it contains all the previous commits which stored all the games, and therefore the `.git/objects` acts as the entire projects directory. Not sure how to get around this without purging the commit history of this repository before the projects directory was moved.

The size of the current commit source code is perfectly fine, it just has a bit of a messy layout

**Comment by Russell2259** [comment]
@CaedenPH I think it is because of all the review images.

**Comment by Russell2259** [comment]
@CaedenPH I moved all of the review images to the 3kh0-Assets repo, we could try fetching all the review images from a CDN hopefully that would reduce repo size.

**Comment by Russell2259** [comment]
It's the review images

**Comment by Russell2259** [comment]
Hopefuly #210 helps with repo size.
