### ISSUE TITLE
Ads On Tunnel Rush

### ISSUE THREAD

**Issue by legofrog** [3kh0/3kh0.github.io#204]
### Check these boxes to make sure you did everything right!

- [X] I have made sure that this issue does not already exist
- [X] I have submitted screenshots of the error
- [X] You are not using the website on any clones (you are using 3kh0.github.io and nothing else)
- [ ] I just checked all of these boxes without reading the labels

### What browser are you using?

Other

### If you said other above, please specify which browser you use

Samsung Internet

### What device are you using?

Other (please note in text field below)

### If you said other above, please specify which device you use

Samsung Galaxy S10

### Please explain the issue

![Screenshot_20220414-175444_Samsung Internet](https://user-images.githubusercontent.com/103226378/163501009-68e6a30d-1d05-4da0-b932-ea06a9d31631.jpg)
Tunnel Rush has ads when all other games don't, tried on a laptop with firefox, a Chromebook, and my phone. Hasn't changed for about a week

**Comment by Piplup7575** [comment]
Intresting.
I have an ad blocker, so i never have seen this, but will look into it!

**Comment by legofrog** [comment]
I do too, but at school I don't 😂

**Comment by 3kh0** [comment]
Works for me, i am going to close this now!
