### ISSUE TITLE
need links

### ISSUE THREAD

**Issue by Erlhyenaplays** [3kh0/3kh0.github.io#208]
Does anyone have some links to the unblocked site?

**Comment by boomboomaladirt** [comment]
- [https://3kh0.github.io/](https://w.goodsciencehelp.com/main/mp_/https://3kh0.github.io/) (main link)
- [https://3kh0.vercel.app/](https://w.goodsciencehelp.com/main/mp_/https://3kh0.vercel.app/)
- [https://3kh0-github-io.vercel.app/](https://w.goodsciencehelp.com/main/mp_/https://3kh0-github-io.vercel.app/)
- [https://3kh0-3kh0.vercel.app/](https://w.goodsciencehelp.com/main/mp_/https://3kh0-3kh0.vercel.app/)
- [https://3kh0-git-main-3kh0.vercel.app/](https://w.goodsciencehelp.com/main/mp_/https://3kh0-git-main-3kh0.vercel.app/)
- [https://english-explorers.vercel.app/](https://w.goodsciencehelp.com/main/mp_/https://english-explorers.vercel.app/)
- [https://english-explorers-3kh0.vercel.app/](https://w.goodsciencehelp.com/main/mp_/https://english-explorers-3kh0.vercel.app/)
- [https://english-explorers-git-main-3kh0.vercel.app/](https://w.goodsciencehelp.com/main/mp_/https://english-explorers-git-main-3kh0.vercel.app/)
- [https://3kh0.netlify.app/](https://w.goodsciencehelp.com/main/mp_/https://3kh0.netlify.app/)
- [https://playful-granita-730d8d.netlify.app/](https://w.goodsciencehelp.com/main/mp_/https://playful-granita-730d8d.netlify.app/)
- [https://dapper-yeot-14837f.netlify.app/](https://w.goodsciencehelp.com/main/mp_/https://dapper-yeot-14837f.netlify.app/)
- [https://helpful-madeleine-e44848.netlify.app/](https://w.goodsciencehelp.com/main/mp_/https://helpful-madeleine-e44848.netlify.app/)
- [https://zesty-dusk-7d6a72.netlify.app/](https://w.goodsciencehelp.com/main/mp_/https://zesty-dusk-7d6a72.netlify.app/)
- [https://history-learners.vercel.app/](https://w.goodsciencehelp.com/main/mp_/https://history-learners.vercel.app/)
- [https://history-learners-3kh0.vercel.app/](https://w.goodsciencehelp.com/main/mp_/https://history-learners-3kh0.vercel.app/)
- [https://history-learners-git-main-3kh0.vercel.app/](https://w.goodsciencehelp.com/main/mp_/https://history-learners-git-main-3kh0.vercel.app/)
- [https://mining-away.vercel.app/](https://w.goodsciencehelp.com/main/mp_/https://mining-away.vercel.app/)
- [https://mining-away-piplup7575.vercel.app/](https://w.goodsciencehelp.com/main/mp_/https://mining-away-piplup7575.vercel.app/)
- [https://mining-away-git-main-piplup7575.vercel.app/](https://w.goodsciencehelp.com/main/mp_/https://mining-away-git-main-piplup7575.vercel.app/)
- [https://idiot-idiot-idiot.vercel.app/](https://w.goodsciencehelp.com/main/mp_/https://idiot-idiot-idiot.vercel.app/)
- [https://idiot-idiot-idiot-piplup7575.vercel.app/](https://w.goodsciencehelp.com/main/mp_/https://idiot-idiot-idiot-piplup7575.vercel.app/)
- [https://idiot-idiot-idiot-git-main-piplup7575.vercel.app/](https://w.goodsciencehelp.com/main/mp_/https://idiot-idiot-idiot-git-main-piplup7575.vercel.app/)
- [https://echorocks.netlify.app/](https://w.goodsciencehelp.com/main/mp_/https://echorocks.netlify.app/)
-

**Comment by 3kh0** [comment]
More links are on the discord
