### ISSUE TITLE
Some Games

### ISSUE THREAD

**Issue by legofrog** [3kh0/3kh0.github.io#211]
### What is this request?

New game

### Please describe the new feature here

Here's just a list of open source games you could add, https://github.com/leereilly/games#user-content-browser-based

**Comment by 3kh0** [comment]
Yeah, I know, but most of the owners had said no

**Comment by legofrog** [comment]
Oh, well!

**Comment by legofrog** [comment]
.(try and get hextris maybe if they say ok?
