### ISSUE TITLE
[Bug] Proxy issue

### ISSUE THREAD

**Issue by 6942-0** [3kh0/3kh0.github.io#212]
### Check these boxes to make sure you did everything right!

- [X] I have made sure that this issue does not already exist
- [X] I have submitted screenshots of the error
- [X] You are not using the website on any clones (you are using 3kh0.github.io and nothing else)
- [ ] I just checked all of these boxes without reading the labels

### What browser are you using?

Apple Safari

### What device are you using?

iPad

### Please explain the issue

The proxy page just has a bunch of links that used to work but are either blocked or don’t work. I don’t know about other schools but they blocked all of the links. Are there other proxy websites you could add?

**Comment by 3kh0** [comment]
Join the discord

- https://discord.gg/6d2MNXWVmV

**Comment by boomboomaladirt** [comment]
try [this proxy](w.goodsciencehelp.com) its the proxy I use in lausd
