### ISSUE TITLE
Add Sans Fight

### ISSUE THREAD

**Issue by AxelMal71** [3kh0/3kh0.github.io#215]
### What is this request?

New game

### Please describe the new feature here

Bad Time Simulator/Sans Fight
[link here!](https://jcw87.github.io/c2-sans-fight)

**Comment by Piplup7575** [comment]
We were just talking about adding this :)
I'm asking jcw87 but i don't think they'll let us

**Comment by Aspaceman527** [comment]
Piplup7575 haven't you done this thing before?

**Comment by Piplup7575** [comment]
@AxelMal71 Looks like no sans fight, but you could probably download and run yourself.
https://github.com/Jcw87/c2-sans-fight/issues/127

@Aspaceman527 idk what you mean
