### ISSUE TITLE
Snoring Dad Tiktok sound effect on the sound board

### ISSUE THREAD

**Issue by valenissius** [3kh0/3kh0.github.io#216]
### What is this request?

New feature

### Please describe the new feature here

search it up on outube

**Comment by boomboomaladirt** [comment]
AAAAAAAAAAAAAAAAAAAAAAAAAAUUUUUUGGGGHHHHHHHHH......... HAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAUUUUUUUUGHGGHHHHHHH

**Comment by 3kh0** [comment]
Just use this form: https://forms.gle/sMqM2wpRtu1oTU9A8
