### ISSUE TITLE
Readymade Tab Cloak not accurate

### ISSUE THREAD

**Issue by airtag8892** [3kh0/3kh0.github.io#224]
### Check these boxes to make sure you did everything right!

- [X] I have made sure that this issue does not already exist
- [X] I have submitted screenshots of the error
- [X] You are not using the website on any clones (you are using 3kh0.github.io and nothing else)
- [ ] I just checked all of these boxes without reading the labels

### What browser are you using?

Google Chrome

### What device are you using?

Chromebook

### Please explain the issue

The readymade tab cloaks are not accurate.

Examples: 
1. The "Google Search" tab cloak has the right Google search logo but the tab name is "Google Search" when it should be "Google".
2. The "Google Drive" tab cloak has the right logo (close enough ig) but the tab name is "Google Drive" when it should be something like "My Drive - Google Drive".
3. The Gmail tab cloak has the right Gmail logo but the tab name is different for every student and district.

There's more that are wrong but you get the point, they're not accurate.

**Comment by Russell2259** [comment]
@airtag8892 You can open a pull request and modify the tab titles. They are located the reviews.js file.

**Comment by airtag8892** [comment]
fixed some

but idk what to do with google calendar or gmail bc the tab title changes depending on different things
