### ISSUE TITLE
Add Grindcraft

### ISSUE THREAD

**Issue by THEBEST1278** [3kh0/3kh0.github.io#225]
### What is this request?

New game

### Please describe the new feature here

Grindcraft

All the links i know of are blocked :(

**Comment by Aspaceman527** [comment]
still give me them

**Comment by Piplup7575** [comment]
Links?

**Comment by THEBEST1278** [comment]
https://grindcraft.fbrq.io/grindcraft/index.html

**Comment by THEBEST1278** [comment]
theres one

**Comment by 3kh0** [comment]
Added
