### ISSUE TITLE
Add review for Moose

### ISSUE THREAD

**Issue by RubberNosedSwampDonkey** [3kh0/3kh0.github.io#226]
### Name

Moose

### Review

100/10 everyone is going on it. It never get's blocked so we always are on it. I honestly give the games a 1000/10. Best games that everyone loves. I will always be playing the goofy games on this website.

### Profile picture

![DancingBaby](https://user-images.githubusercontent.com/127911291/225185419-f87914d5-c2a3-4d3d-8e98-404ba2250209.gif)

**Comment by DapperLS-Bot-Dev** [comment]
i got this

**Comment by DapperLS-Bot-Dev** [comment]
I did it, now just wait for Echo to approve the pull request.
