### ISSUE TITLE
Butterminecart's review

### ISSUE THREAD

**Issue by butterminecart** [3kh0/3kh0.github.io#23]
### Name

butterminecart

### Review

420/69 best site ever I play on it when I procrastinate and there is so many cool games like minecraft, roblox, and fortnite. I highly recommend this site to anyone even my dog who also plays on this site somehow. Anyways I look forward to the future of this site.

### Profile picture

https://yt3.googleusercontent.com/9r1z-FzuV21qZ3SkrnTU7st50sd_fc5cpAAx_BgmElrMcj3ZO6I8XWnHdSLimhRtXvB7rUazAfI=s900-c-k-c0x00ffffff-no-rj

**Comment by Nebelung-Dev** [comment]
Added!
