### ISSUE TITLE
Fix Fullscreen Support for iPad

### ISSUE THREAD

**Issue by BountyInfinity** [3kh0/3kh0.github.io#230]
### What is this request?

New feature

### Please describe the new feature here

On the computer the full screen works, on iPad and mobile it does not.

**Comment by Russell2259** [comment]
@BountyInfinity Are you accessing 3kh0 with safari?

**Comment by Rahib777-7** [comment]
> @BountyInfinity Are you accessing 3kh0 with safari?
all browsers on ios are webkit based but with something extra...

**Comment by BountyInfinity** [comment]
Yes I am using safari.

**Comment by Russell2259** [comment]
Have you tried on a different browser?

**Comment by Rahib777-7** [comment]
> @BountyInfinity Have you tried on a different browser?
all browsers are safari based on ios so they wont work

**Comment by Nebelung-Dev** [comment]
You need to use `webkitRequestFullscreen` as a fallback to `requestFullscreen`.

Here is an example way of doing it I found on the internet.
```html
var elem = document.getElementById("element");
if (elem.requestFullscreen) {
  elem.requestFullscreen();
} else if (elem.msRequestFullscreen) {
  elem.msRequestFullscreen();
} else if (elem.mozRequestFullScreen) {
  elem.mozRequestFullScreen();
} else if (elem.webkitRequestFullscreen) {
  elem.webkitRequestFullscreen();
}
```

**Comment by Nebelung-Dev** [comment]
Update ios 16.4 should fix this issue
https://webkit.org/blog/13966/webkit-features-in-safari-16-4/#:~:text=safari%2016.4%20now%20supports%20the%20updated%20and%20unprefixed%20fullscreen%20api%20on%20macos%20and%20ipados.

**Comment by aeiea** [comment]
should i close?

**Comment by aeiea** [comment]
ill just close
