### ISSUE TITLE
Add Fran Bow

### ISSUE THREAD

**Issue by SomeMiddleSchooler** [3kh0/3kh0.github.io#232]
### What is this request?

New game

### Please describe the new feature here

Would you guys please add fran bow or another horror game to this. First I want to say that this is what gets me through the school day but I really want horror games. One horror game I have never played but want to play is fran bow and I think my friends who use this would enjoy this to. Some other horror games could be some of the chillas art games. Sadly I do not have any links to either of them but I would greatly appreciate it.

**Comment by Russell2259** [comment]
@SomeMiddleSchooler Please provide a link for this issue to be valid.

**Comment by DapperLS-Bot-Dev** [comment]
It is a paid game, and one that does not have a WebGL version. It would be hard to add the game, so I have to close this ticket.
