### ISSUE TITLE
The CDN is blocked

### ISSUE THREAD

**Issue by Gamerboy199** [3kh0/3kh0.github.io#233]
### Check these boxes to make sure you did everything right!

- [X] I have made sure that this issue does not already exist
- [X] I have submitted screenshots of the error
- [X] You are not using the website on any clones (you are using 3kh0.github.io and nothing else)
- [X] I just checked all of these boxes without reading the labels

### What browser are you using?

Google Chrome

### What device are you using?

Chromebook

### Please explain the issue

Your cdn raw.githack.com/3kh0/3kh0-Assets/main got blocked can you make a new one or make it so I can change the cdn to my version of  raw.githack.com/3kh0/3kh0-Assets/main

**Comment by Russell2259** [comment]
@Gamerboy199  You can use my [3kh0-CDN](https://github.com/Russell2259/3kh0-CDN) to host your own CDN server or you can update your fork  of 3kh0 because new CDN's were added today.
