### ISSUE TITLE
Add Backrooms 2D

### ISSUE THREAD

**Issue by CraftProductions** [3kh0/3kh0.github.io#235]
### What is this request?

New game

### Please describe the new feature here

Backrooms 2D is a 2D Backrooms Unity game.
I really think you should add it! It is really fun, especially with the new update!
Here is what the description is:

"The Backrooms is an internet creepypasta unsettling millions of viewers around the world, where you noclip out of reality into a liminal space with nothing but millions of miles of rooms. Since many Backrooms games already exist, I decided to take a spin with making the game 2D instead of the usual 3D."

There is WebGL build available in the [itch.io page](https://jujuprodgames.itch.io/backrooms-2d).

Please add it!

(Also, can you please fix "Monster Tracks" when you die (the car collapses) sometimes the options to continue or take a look at the shop don't work and make the player softlocked.)

**Comment by Russell2259** [comment]
@CraftProductions We should be able to add this. Thanks for your suggestion!

**Comment by CraftProductions** [comment]
Your welcome! :)

**Comment by Russell2259** [comment]
@3kh0 Do you have time to do this?

**Comment by CraftProductions** [comment]
? Do what?

**Comment by Russell2259** [comment]
Can someone upload this [zip file](https://nowtransfer.de/3fcd54545efa)? I can't upload it to the assets repo because its so big.

**Comment by 3kh0** [comment]
Done

**Comment by CraftProductions** [comment]
?
![image](https://user-images.githubusercontent.com/126298358/226772281-9ec1809c-e8df-421c-874a-1b9b025611ed.png)

I meant this lol
![image](https://user-images.githubusercontent.com/126298358/226772443-051e7f49-f041-458d-b576-6c119d22c633.png)
