### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by 123345666777777777777777777777777** [3kh0/3kh0.github.io#236]
### Check these boxes to make sure you did everything right!

- [X] I have made sure that this issue does not already exist
- [X] I have submitted screenshots of the error
- [X] You are not using the website on any clones (you are using 3kh0.github.io and nothing else)
- [X] I just checked all of these boxes without reading the labels

### What browser are you using?

Apple Safari

### Please explain the issue

All proxies and vpns are blocked for me

**Comment by 123345666777777777777777777777777** [comment]
Lol

**Comment by 123345666777777777777777777777777** [comment]
Purposeful checked them all

**Comment by 123345666777777777777777777777777** [comment]
Also there is this blocker called relay smart agent which blocks all of these.You can ask any person who uses the blocker relay smart agent.

**Comment by 3kh0** [comment]
Join the discord for unblocked links:
- https://discord.gg/6d2MNXWVmV
