### ISSUE TITLE
This is like me

### ISSUE THREAD

**Issue by AdenSulit** [3kh0/3kh0.github.io#239]
### Name

AdenSulit

### Review

Yaknow, I am extremely proud that this page is 1,000,000 times longer than my you-know-what. These games take so long to load though, but I'm fine with it since I can make some milk while I'm waiting. I get no girls though, so that's how desperate I am.

### Profile picture

![aden](https://user-images.githubusercontent.com/117232512/199352944-62004cba-192c-4ea7-b29d-cd46d55abba1.png)

**Comment by 3kh0** [comment]
I will do this

**Comment by YeeticusPrimed** [comment]
That is so bootylicous
