### ISSUE TITLE
[Bug] idiot-idiot-idiot.vercel.app returns 404

### ISSUE THREAD

**Issue by Bbmonkey8463** [3kh0/3kh0.github.io#24]
### Check these boxes to make sure you did everything right!

- [X] I have made sure that this issue does not already exist
- [X] I have submitted screenshots of the error
- [X] You are not using the website on any clones (you are using 3kh0.github.io and nothing else)
- [ ] I just checked all of these boxes without reading the labels

### What browser are you using?

Google Chrome

### What device are you using?

Chromebook

### Please explain the issue

https://idiot-idiot-idiot.vercel.app
gives error code 404 and sometimes 402.
![Screenshot 2022-09-01 8 36 02 AM](https://user-images.githubusercontent.com/112577825/187929951-b12702d2-c8e3-45b5-8f68-c7f8ad86e899.png)
![Screenshot 2022-09-01 8 47 37 AM](https://user-images.githubusercontent.com/112577825/187930125-ae500bf5-06a9-46ee-96b7-844413a34c45.png)

**Comment by 3kh0** [comment]
Hmmm, it works for me, try a different link, or deploy your own copy using this guide:

https://github.com/3kh0/3kh0.github.io/wiki/Guide:-Deploying-a-site-with-GitHub

![Screenshot 2022-09-01 2 47 28 PM](https://user-images.githubusercontent.com/58097612/187990032-a1295ae5-10bb-404f-aed6-03303da54ab0.png)

**Comment by Piplup7575** [comment]
Yep, this url was disabled when my vercill account was disabled, if you csn still see it it is because your cashe was not updated.
But join the discord for more links!
