### ISSUE TITLE
goog

### ISSUE THREAD

**Issue by AdenSulit** [3kh0/3kh0.github.io#240]
### Name

Aden Sulit

### Review

I am Aden SUlit. I am a registered offender. Hahaha, and I bet you can't beat my 1 millimeter defeater.

### Profile picture

![aden](https://user-images.githubusercontent.com/117232512/199353921-3058865c-5626-4998-8696-5a05dbd3c1b8.png)

**Comment by AdenSulit** [comment]
I like goog

**Comment by 3kh0** [comment]
@AdenSulit Please revise your review to be not suggestive
