### ISSUE TITLE
soundboard

### ISSUE THREAD

**Issue by waynesworldfan** [3kh0/3kh0.github.io#241]
### Name

aggravated person

### Review

7/10 the only bad thing is that the soundboard doesn't work for me

### Profile picture

![image](https://user-images.githubusercontent.com/117196697/199483734-e021e79d-33c2-471a-88c5-fd88cfda71bc.png)

**Comment by 3kh0** [comment]
@waynesworldfan the link you are using is outdated, try going to 6kh0.github.io

**Comment by 3kh0** [comment]
@waynesworldfan Please file a bug report
