### ISSUE TITLE
Retro Bowl keep freezing

### ISSUE THREAD

**Issue by 6942-0** [3kh0/3kh0.github.io#242]
### Check these boxes to make sure you did everything right!

- [X] I have made sure that this issue does not already exist
- [X] I have submitted screenshots of the error
- [X] You are not using the website on any clones (you are using 3kh0.github.io and nothing else)
- [ ] I just checked all of these boxes without reading the labels

### What browser are you using?

Apple Safari

### What device are you using?

iPad

### Please explain the issue

After some games, retro bowl just freezes and I have to reload the page and have to replay the game.

**Comment by 3kh0** [comment]
I will see if I can reproduce this bug

**Comment by 1mBounty** [comment]
@6942-0 is the bug that if you play some games then when the game ends it freezes?

**Comment by 3kh0** [comment]
@3kh0 I am unable to reproduce this bug, could you please elaborate

**Comment by 1mBounty** [comment]
I’ll submit a screen recording later today then.

**Comment by 1mBounty** [comment]
I’ll submit a screen recording later today then.

**Comment by 6942-0** [comment]
@1mBounty you mean when I play a game of retro bowl? In that case, yes it freezes about once every 1-2 games.

**Comment by 1mBounty** [comment]
can you submit video recordings? If not I can do it.

**Comment by 3kh0** [comment]
@1mBounty @6942-0 If you can submit any recordings, console logs or browser logs please do

**Comment by 3kh0** [comment]
Stale
