### ISSUE TITLE
[Bug] Grindcraft not working

### ISSUE THREAD

**Issue by smileman52** [3kh0/3kh0.github.io#245]
### Check these boxes to make sure you did everything right!

- [X] I have made sure that this issue does not already exist
- [X] I have submitted screenshots of the error
- [X] You are not using the website on any clones (you are using 3kh0.github.io and nothing else)
- [ ] I just checked all of these boxes without reading the labels

### What browser are you using?

Google Chrome

### What device are you using?

Chromebook

### Please explain the issue

Grindcraft isn't working for me I don't know if it's a problem with my computer or something wrong with the website. Grindcraft just gets stuck on that screen forever. btw I'm using a clone of the website only because the original is blocked the website is the same as the original

https://user-images.githubusercontent.com/104168698/168117901-cb81238f-aad3-4fbe-b52f-eab77827f019.mp4

.

**Comment by RuralAnemone** [comment]
Works fine for me

**Comment by smileman52** [comment]
Could you send a video of it?

**Comment by RuralAnemone** [comment]
nah it's good now
I think it might have been the commit in progress

**Comment by RuralAnemone** [comment]
oh wait wrong issue lol sorry

**Comment by RuralAnemone** [comment]
[Screen recording 2022-05-12 12.02.19.zip](https://github.com/3kh0/3kh0.github.io/files/8681210/Screen.recording.2022-05-12.12.02.19.zip)
on second thought it might be a bit iffy
I've only gotten it to works once (on my first try)

**Comment by smileman52** [comment]
oh

**Comment by RuralAnemone** [comment]
[Screen recording 2022-05-19 12.33.07.zip](https://github.com/3kh0/3kh0.github.io/files/8732521/Screen.recording.2022-05-19.12.33.07.zip)
seems to be working just fine for me now...
maybe try again...?
idk

**Comment by 3kh0** [comment]
@smileman52 This error happens a-lot, all I can say is refresh the page :(

**Comment by smileman52** [comment]
@3kh0 alright thanks!
