### ISSUE TITLE
All Previously Forked Repos Have Been Disabled

### ISSUE THREAD

**Issue by aeiea** [3kh0/3kh0.github.io#245]
![image](https://user-images.githubusercontent.com/118844761/226446832-fb1b9c77-a71a-423c-89b8-4bbfbda8e898.png)
![image](https://user-images.githubusercontent.com/118844761/226446955-59fb6b22-c47e-4951-a4eb-c9b9a895d1b2.png)
Only the latest forks exist
![image](https://user-images.githubusercontent.com/118844761/226447323-66505408-793b-447a-858d-6514bec0299d.png)

**Comment by mc201288813** [comment]
anyone know why this happened?

**Comment by Russell2259** [comment]
We can't fix this issue, but we are trying to contact github support and staff to try and figure out what happened. It seems that every fork of the 3kh0.github.io and 3kh0-Assets repositories got DMCAed.

**Comment by 3kh0** [comment]
You can look at the status of the sites here: https://uptime.example-youtube.repl.co/status/3kh0

We also list some domains there.

**Comment by DapperLS-Bot-Dev** [comment]
whats so wrong with flappy plane lol
