### ISSUE TITLE
404...?

### ISSUE THREAD

**Issue by RuralAnemone** [3kh0/3kh0.github.io#246]
### Check these boxes to make sure you did everything right!

- [x] I have made sure that this issue does not already exist
- [x] I have submitted screenshots of the error
- [x] You are not using the website on any clones (you are using 3kh0.github.io and nothing else)
- [ ] I just checked all of these boxes without reading the labels

### What browser are you using?

Mozilla Firefox

### What device are you using?

Chromebook

### Please explain the issue

site down? gave me an unsafe warning (I thought just because of certificate + my vpn) but then
![image](https://user-images.githubusercontent.com/64103005/168119625-74ff58ae-5084-4cd3-90ed-0fba42efdb55.png)

**Comment by RuralAnemone** [comment]
though I just noticed that a push just recently happened so..

yeah I'll try again :)

**Comment by smileman52** [comment]
👍

**Comment by RuralAnemone** [comment]
oh wait

**Comment by RuralAnemone** [comment]
*closed*
