### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by RobertW4sTaken** [3kh0/3kh0.github.io#250]
### What is this request?

New game

### Please describe the new feature here

Drift Hunters: https://v6p9d9t4.ssl.hwcdn.net/html/1792221/ItchIO/index.html?v=1574649458

**Comment by RuralAnemone** [comment]
already a thing!
[github file](https://github.com/3kh0/3kh0.github.io/tree/4034117c7f47cdc804b4227c26e52728d9806e3f/projects/drift-hunters
)
[link](https://3kh0.github.io/projects/drift-hunters)

**Comment by u4pak** [comment]
as RuralAnemone said, this has already been added to the site :D
