### ISSUE TITLE
Ad-Blocker detector triggering false positive

### ISSUE THREAD

**Issue by Rlockzo** [3kh0/3kh0.github.io#251]
### Check these boxes to make sure you did everything right!

- [X] I have made sure that this issue does not already exist
- [X] I have submitted screenshots of the error
- [X] You are not using the website on any clones (you are using 3kh0.github.io and nothing else)
- [ ] I just checked all of these boxes without reading the labels

### What browser are you using?

Apple Safari

### What device are you using?

Other (please note in text field below)

### If you said other above, please specify which device you use

iPad Air 2

### Please explain the issue

bruh this pop up is preventing me from using the website
![674A3002-E710-4930-ABBB-BE69A975571D](https://user-images.githubusercontent.com/121692782/226770040-a0c7141d-f221-40f6-bb0f-a369750a3453.png)

**Comment by Russell2259** [comment]
@Rlockzo I probably shouldn't be saying this, but I made an anti anti adblock. You can use it here https://github.com/Russell2259/3kh0-Anti-Adblock.

**Comment by Russell2259** [comment]
Re-open this if the problem continues
