### ISSUE TITLE
Games fail to load because of anti adblocker

### ISSUE THREAD

**Issue by Russell2259** [3kh0/3kh0.github.io#252]
Remove adblocker on the game.html page.

**Comment by aeiea** [comment]
addressed by #248

**Comment by THATBOICOLD** [comment]
it keep saying ad blocker STOP IT PLEASE BTW CAN YOU SHOW ME HOW TO ADD CHAT ROOM PLEASE

**Comment by THATBOICOLD** [comment]
ON my website

**Comment by THATBOICOLD** [comment]
[https://sites.google.com/stu.cfisd.net/fab1anmath/home](https://sites.google.com/stu.cfisd.net/fab1anmath/home)

**Comment by Rahib777-7** [comment]
> it keep saying ad blocker STOP IT PLEASE BTW CAN YOU SHOW ME HOW TO ADD CHAT ROOM PLEASE

stop using an adblocker then also https://widgetbot.io/

**Comment by aeiea** [comment]
he isnt using a adblock his skool dnsblocks it
