### ISSUE TITLE
Add a review

### ISSUE THREAD

**Issue by SupahStalin** [3kh0/3kh0.github.io#253]
### Name

My Goguardian Addicted Special Ed Teacher

### Review

0/10 OMFG WHY MEh Studnt Watchimg big BlaCk mEn kiSSinG On Ornge YouTuBe!

### Profile picture

![image](https://user-images.githubusercontent.com/117240000/199846643-6835caf8-eb92-4f84-bdd2-feaab7bb28b5.png)

**Comment by 3kh0** [comment]
@SupahStalin Please write a review that is more clean
