### ISSUE TITLE
Add a review

### ISSUE THREAD

**Issue by apexfinity** [3kh0/3kh0.github.io#254]
### Name

4school

### Review

4school.vercel.app better

:)

### Profile picture

![](view-source:https://4school.vercel.app/store/images/favicon.png)

**Comment by 3kh0** [comment]
![image](https://user-images.githubusercontent.com/58097612/199986007-1a027da8-dddd-48fa-8b3b-bf237e5034c5.png)

haha nice, what profile picture do you want me to use anyway?

**Comment by 3kh0** [comment]
Stale

**Comment by apexfinity** [comment]
lol i had to shut down the site 

nice site tho 3kh0

also check ur twitter dms
