### ISSUE TITLE
Bloons TD 5 does not load

### ISSUE THREAD

**Issue by Wildtick** [3kh0/3kh0.github.io#255]
### Check these boxes to make sure you did everything right!

- [X] I have made sure that this issue does not already exist
- [X] I have submitted screenshots of the error
- [X] You are not using the website on any clones (you are using 3kh0.github.io and nothing else)
- [X] I just checked all of these boxes without reading the labels

### What browser are you using?

Google Chrome

### What device are you using?

Chromebook

### Please explain the issue

When loading into BTD 5 it loads then it's just a white screen. Nothing else after that.
![Screenshot 2023-03-22 5 15 16 PM](https://user-images.githubusercontent.com/110534522/227055132-1d4a98b0-c422-48c8-834b-5b9002f302f4.png)

**Comment by aeiea** [comment]
as3 compat issue not our problem

**Comment by aeiea** [comment]
russell pls close

**Comment by DapperLS-Bot-Dev** [comment]
k
