### ISSUE TITLE
Roblox does not work

### ISSUE THREAD

**Issue by Isaac-8917** [3kh0/3kh0.github.io#256]
### Check these boxes to make sure you did everything right!

- [X] I have made sure that this issue does not already exist
- [X] I have submitted screenshots of the error
- [X] You are not using the website on any clones (you are using 3kh0.github.io and nothing else)
- [X] I just checked all of these boxes without reading the labels

### What browser are you using?

Google Chrome

### What device are you using?

Chromebook

### Please explain the issue

roblox doesnt work
![image](https://user-images.githubusercontent.com/103591767/227268476-e433c3e5-7bcf-49be-a282-ba72cfeed3af.png)

**Comment by Russell2259** [comment]
Its not actually Roblox.

**Comment by 3kh0** [comment]
Dont know why it did not work, I also notice you have your adblocker on, it would be nice if you turned it off
