### ISSUE TITLE
server wont work again for chrone

### ISSUE THREAD

**Issue by Hunter2023gg** [3kh0/3kh0.github.io#257]
### Check these boxes to make sure you did everything right!

- [X] I have made sure that this issue does not already exist
- [X] I have submitted screenshots of the error
- [ ] You are not using the website on any clones (you are using 3kh0.github.io and nothing else)
- [ ] I just checked all of these boxes without reading the labels

### What browser are you using?

Google Chrome

### What device are you using?

Chromebook

### Please explain the issue

chrome wont load
![image](https://user-images.githubusercontent.com/127138609/227295698-265c5f5e-d52d-43ab-8830-e52e84905f32.png)

**Comment by Russell2259** [comment]
What are you talking about, and why are you using a proxy? I will have to close this issue because of a lack of information.

**Comment by Hunter2023gg** [comment]
if i dont use a proxy then it will be blocked

**Comment by Russell2259** [comment]
There is no server for 3kh0

**Comment by Hunter2023gg** [comment]
im talking about the website

**Comment by Russell2259** [comment]
wdym?

**Comment by Hunter2023gg** [comment]
send me the link

**Comment by Russell2259** [comment]
discord.gg/3kh0

**Comment by Hunter2023gg** [comment]
i joined my user is pappylongstockin#0830
