### ISSUE TITLE
[Bug] Ad block

### ISSUE THREAD

**Issue by BountyInfinity** [3kh0/3kh0.github.io#258]
### Check these boxes to make sure you did everything right!

- [X] I have made sure that this issue does not already exist
- [X] I have submitted screenshots of the error
- [X] You are not using the website on any clones (you are using 3kh0.github.io and nothing else)
- [ ] I just checked all of these boxes without reading the labels

### What browser are you using?

Apple Safari

### What device are you using?

iPad

### Please explain the issue

I don't know if the the anti-adblock is activating because I am playing on a deployments and deployments don't have ads, my school installs a mandatory adblock or something else.

Can you only have the anti-adblock active when the web is 3kh0.github.io because otherwise my whole school can't access 3kh0 and there are are no ads on deployments anyways.

**Comment by 3kh0** [comment]
Fixed, by removing it 👍🏻
