### ISSUE TITLE
Add Super Mario Construct

### ISSUE THREAD

**Issue by boomboomaladirt** [3kh0/3kh0.github.io#26]
### What is this request?

New game

### Please describe the new feature here

Super mario construct is a really good mario maker web game and i hope you guys could do your magic to add this game, heres the link,
[Super mario Construct](https://luigibonus.com/games/supermarioconstruct/)
![Screenshot 2022-09-01 171837](https://user-images.githubusercontent.com/99102801/188033649-47ac8238-4b57-4d4c-94a4-6afe7c9a4cb5.png)

**Comment by Piplup7575** [comment]
Will look into it!

**Comment by nicolasog12** [comment]
Dang this is old looking...

**Comment by RobertW4sTaken** [comment]
Idk if this helps but here is a replit link “https://replit.com/@robertsgames/smc”

**Comment by Piplup7575** [comment]
On it!

**Comment by Piplup7575** [comment]
Thanks @RobertW4sTaken!
Adding right now!
