### ISSUE TITLE
Even More Bookmarklets

### ISSUE THREAD

**Issue by venstillia** [3kh0/3kh0.github.io#260]
### What is this request?

Something else

### If you said other in the dropdown above, please specify what below

Even More Bookmarklets

### Please describe the new feature here

ok lol these might actually break the page for real lmfao

TURN THE PAGE INTO STAR WARS -
javascript:(function(c){var a=c.body.style;c.documentElement.style.background=a.background='black';a.color='yellow';a.height=a.width='100%';a.position='fixed';a.overflowY='scroll';a.top='-15%';a.webkitTransform=a.MozTransform=a.transform='matrix3d(1,0,0,0,0,1,0,-0.0015,0,0,1,0,0,0,0,1)';for(var a=c.body.children,b=0;b<a.length;b++)'SCRIPT'!=a[b].nodeName&&(a[b].style.overflowY='scroll',a[b].style.maxHeight='100%');var b=new Audio();b.src='https://archive.org/download/StarWarsThemeSongByJohnWilliams/Star Wars Theme Song By John Williams.mp3';var f=function(){for(var a,b=0;a=c.body.children[b];b++)'SCRIPT'!=a.nodeName&&(a.scrollTop+=2);setTimeout(f,50)};setTimeout(f,1000);b.load();b.play()})(document)

THE MATRIX -
javascript:(function(){var wn=window,w,h,o={},m,dc,b,c='ABCDEFGHIJKLM1234567890nopqrstuvwxyz',y=setInterval,z=clearInterval,t=1;function x(){dc=document;b=dc.body;b.innerHTML='';bs=b.style;w=wn.innerWidth;h=wn.innerHeight;bs.backgroundColor='black';bs.overflow='hidden';m=y(n,25);dc.addEventListener('keydown',function(e){if(e.keyCode==83){if(t)z(m);else m=y(n,25);t=!t}},0)}function g(i){return dc.getElementById(i)}function r(d,m){return Math.floor(Math.random()*d)+m}function a(i){var d=g(i),ds=d.style,t=parseInt(ds.top),k=o[i];if(t<h){ds.top=(t+10)+'px'}else{z(k);b.removeChild(d);delete k}}function n(){var d=dc.createElement('div'),dt=new Date(),i='m_'+dt.getTime(),ds=d.style,v=ds.visibility,j=0,u=[],l=r(21,4),q=c.length,p;d.id=i;ds.width='5px';ds.opacity=r(.3,.7);ds.fontSize=r(8,8)+'px';ds.lineHeight='8px';ds.color='green';ds.position='absolute';ds.left=r(w,0)+'px';v='hidden';while(j<l){p=r(q,0);u[j]=c.substring(p,p+1);j++}d.innerHTML=u.join("\n");b.appendChild(d);ds.top=-d.offsetHeight+'px';v='visible';o[i]=y(function(){a(i)},r(20,40))}x();})()

SPAM ALERTS - 
javascript: (function() {  function annoy() {    alert('annoy');    annoy();  }  annoy();})();

**Comment by venstillia** [comment]
ok lol echo i hope you don't hate me for putting 3 issues in all bookmarklets lmfao

**Comment by 3kh0** [comment]
its fine

**Comment by 3kh0** [comment]
@RuralAnemone add these

**Comment by RuralAnemone** [comment]
ok :)

**Comment by RuralAnemone** [comment]
I should get around to it sometime today
