### ISSUE TITLE
Actually Add Backrooms 2D

### ISSUE THREAD

**Issue by ghost** [3kh0/3kh0.github.io#261]
### What is this request?

New game

### Please describe the new feature here

As I've mentioned in my last post, I'd like to add Backrooms 2D. The Link is [HERE](https://jujuprodgames.itch.io/backrooms-2d).

FYI this is what the game looks like:
![Screenshot 2023-03-21 5 38 01 PM](https://user-images.githubusercontent.com/126298358/227652322-ddaf787b-e076-44e5-a0d9-0e5766c9c776.png)

**Comment by Russell2259** [comment]
I added that already

**Comment by CraftProductions** [comment]
I don't think it's supposed to look like this
![image](https://user-images.githubusercontent.com/126298358/227695441-eed4ff6b-97c7-40c9-8f23-c7714c4d2143.png)

**Comment by CraftProductions** [comment]
![2](https://user-images.githubusercontent.com/126298358/227695997-29e3cd16-4c39-4f9b-a6ab-f833dc5b6a31.jpg)

**Comment by Rahib777-7** [comment]
> I don't think it's supposed to look like this
> ![image](https://user-images.githubusercontent.com/126298358/227695441-eed4ff6b-97c7-40c9-8f23-c7714c4d2143.png)
dont expect it to be exact

**Comment by Rahib777-7** [comment]
> I don't think it's supposed to look like this
> ![image](https://user-images.githubusercontent.com/126298358/227695441-eed4ff6b-97c7-40c9-8f23-c7714c4d2143.png)

thats backrooms 2d?

**Comment by aeiea** [comment]
sorry but the devs dont provide a html5 build of the game.

**Comment by Rahib777-7** [comment]
> sorry but the devs dont provide a html5 build of the game.

i added  the html5 build
