### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by TheRealDigitalMaster** [3kh0/3kh0.github.io#261]
### Name

-DigitalMaster-

### Review

Is this illegal publishing? Because sm64 you have to purchase, same with sonic, temple run 2, and others. I can't find the report button, but please consider my concern because if you don't, there are digital fingerprints hidden in the code so its easy to track down. Please think about this.

### Profile picture

![25231](https://user-images.githubusercontent.com/112659665/200308840-53b6db37-4512-41d6-b458-1b29167e4624.png)

**Comment by 3kh0** [comment]
Temple Run 2 is free, and I have removed most if not all of the tracking beacons, (thanks uBlock for getting those), pixel trackers, all of that fun stuff. If you find any, let me know!

**Comment by TheRealDigitalMaster** [comment]
Then please remove sm64 and sonic because those are licensed and cost money (look up if you don't believe me). And if the whole world knows about this, you might get in trouble. I am just letting you know before things get chaotic.

**Comment by 3kh0** [comment]
![image](https://user-images.githubusercontent.com/58097612/200341720-ce5bdef3-dbf0-4c7a-9827-4ad39145ca40.png)

**Comment by TheRealDigitalMaster** [comment]
Exactly I am going to report you for this. I forked the repository and deleted the games that were pirated.

**Comment by RuralAnemone** [comment]
💀

**Comment by TheRealDigitalMaster** [comment]
What do you want @RuralAnemone

**Comment by TheRealDigitalMaster** [comment]
@RuralAnemone I was just saying to them that they shouldn't pirate video games because they put in hidden digital fingerprints that could not be found by anyone but them.

**Comment by RuralAnemone** [comment]
I appreciate your concerns, 

but like

the roms are all over the internet, no?
technically it would be best to just have users upload their own roms, but nintendo won't sue 3kh0 (unless he makes any decent amount of money off this, afaik) (as well as others who have contributed to "illegal activity") and even if they did, you wouldn't get in trouble just for using the pirated software


<br><br><br><br>
"remember, it's only illegal if you get caught"

**Comment by RuralAnemone** [comment]
...which isn't the best quote to live by, _but it's worked so far 👀_

**Comment by RuralAnemone** [comment]
so yeah
uh


<br>have fun :)

**Comment by TheRealDigitalMaster** [comment]
Thats why im reporting this to the police

**Comment by TheRealDigitalMaster** [comment]
*of the internet

**Comment by 3kh0** [comment]
*ohno*

**Comment by TheRealDigitalMaster** [comment]
i am going to let the whole internet know about this

**Comment by TheRealDigitalMaster** [comment]
through facebook youtube instagram pinterest twitter scratch wikipedia and github and more

**Comment by 3kh0** [comment]
wikipedia, ong

**Comment by TheRealDigitalMaster** [comment]
there is a talk section

**Comment by TheRealDigitalMaster** [comment]
i will also make an article uneditable
