### ISSUE TITLE
Soundboard managers

### ISSUE THREAD

**Issue by 3kh0** [3kh0/3kh0.github.io#262]
Ok so I was a goofy and forgot that the soundboard suggestions form exists so the suggestions piled up.

![image](https://user-images.githubusercontent.com/58097612/200390784-5753edaf-115b-45fd-a5fd-30297af5df09.png)

So I am looking for people that will help to add these sounds with pull requests, delete the NSFW sounds, all of that fun stuff. Comment your Google email so I can add you!

**Comment by RuralAnemone** [comment]
ruralanemone@gmail.com
💀 this'll be fun
