### ISSUE TITLE
Hacker Typer Not Working

### ISSUE THREAD

**Issue by DapperLS-Bot-Dev** [3kh0/3kh0.github.io#264]
### Check these boxes to make sure you did everything right!

- [X] I have made sure that this issue does not already exist
- [X] I have submitted screenshots of the error
- [X] You are not using the website on any clones (you are using 3kh0.github.io and nothing else)
- [ ] I just checked all of these boxes without reading the labels

### What browser are you using?

Google Chrome

### If you said other above, please specify which browser you use

I am using chrome on chromebook and opera on PC.

### What device are you using?

Chromebook

### Please explain the issue

Hacker Typer is not registering keystrokes. I will self-assign this to fix it.
![image](https://user-images.githubusercontent.com/75214924/227717318-ee0f0c78-d956-41c3-ab04-a349065d15b0.png)

**Comment by Russell2259** [comment]
It might be because of the iframe.

**Comment by DapperLS-Bot-Dev** [comment]
No, i ran a local version and a file was missing.
