### ISSUE TITLE
Move Non-Games to /dump Suggestion

### ISSUE THREAD

**Issue by Bountylnfinity** [3kh0/3kh0.github.io#265]
### What is this request?

New feature

### Please describe the new feature here

I think that “games” like chill radio, fake virus, and hacker typer should be moved to /dump because currently they are in the games category and are contributing to the current game count on index.html. I think that the games tab should only have games on it and not “fun gadgets”. 

Just a suggestion.
-Bountylnfinity

Also I keep having to change my name because my school keeps blocking my other account names.

**Comment by 3kh0** [comment]
I see your point but, the folder is `/projects`, and not `/games`, so I would think that they do fit in there, the `/dump` folder is mostly only for small things

**Comment by Bountylnfinity** [comment]
![A343E3DA-C919-4A1B-B23C-8CA29AEE415C](https://user-images.githubusercontent.com/105021032/200868582-279b1905-577a-4450-bc79-56b67943a359.jpeg)

**Comment by 3kh0** [comment]
Stale
