### ISSUE TITLE
[Bug] Favicon.ico not changing with Tab Cloaker

### ISSUE THREAD

**Issue by Bountylnfinity** [3kh0/3kh0.github.io#266]
### Check these boxes to make sure you did everything right!

- [X] I have made sure that this issue does not already exist
- [X] I have submitted screenshots of the error
- [X] You are not using the website on any clones (you are using 3kh0.github.io and nothing else)
- [ ] I just checked all of these boxes without reading the labels

### What browser are you using?

Apple Safari

### What device are you using?

iPad

### Please explain the issue

The Tab Cloaker doesn’t assign the favicon.ico, but I don’t know if it is intentional. I think it kinda defeats the purpose of the Tab Cloaker when the favicon.ico is 3kh0. 
![A547C4BB-DA2F-413A-9BAB-F3EC2177E4A4](https://user-images.githubusercontent.com/105021032/200856759-823b132f-3747-4781-8e54-b72125e0da3b.jpeg)

**Comment by 3kh0** [comment]
Which page is this on? can you send the link?

**Comment by Bountylnfinity** [comment]
https://3kh0.github.io/dump/settings.html

**Comment by 3kh0** [comment]
I will try and reproduce this bug

**Comment by 3kh0** [comment]
Fixed
