### ISSUE TITLE
Add review for Mollomm1

### ISSUE THREAD

**Issue by Mollomm1** [3kh0/3kh0.github.io#267]
### Name

Mollomm1

### Review

10/10 best website for education, I learned the right way how to use school computers! I especially love Roblox, it's running really well (120fps 4k, the best game on 3kh0 game library) and now I can't wait for ForTNite support.

### Profile picture

![image](https://user-images.githubusercontent.com/68751598/227729814-5504964e-4ee2-4594-a952-9c86a9f62521.png)

**Comment by DapperLS-Bot-Dev** [comment]
i call dibs on this one

**Comment by DapperLS-Bot-Dev** [comment]
Done, now you have to wait for Echo to accept my pull request.
