### ISSUE TITLE
Add Friday night funkin

### ISSUE THREAD

**Issue by Proph3t-3036** [3kh0/3kh0.github.io#269]
### What is this request?

New game

### Please describe the new feature here

The game regular game, no extra BS needed

https://ninja-muffin24.itch.io/funkin

I thought the source was on GitHub once

**Comment by RetroWonder** [comment]
https://github.com/28klotlucas2/Funkin-Html5

**Comment by RetroWonder** [comment]
@3kh0

**Comment by RetroWonder** [comment]
My pull request adds it!

**Comment by 3kh0** [comment]
Done in #324
