### ISSUE TITLE
Add Some FNAF Games

### ISSUE THREAD

**Issue by CraftProductions** [3kh0/3kh0.github.io#269]
### What is this request?

New game

### Please describe the new feature here

I'd like you guys to add(at least)

- FNAF 1
- FNAF 2
- FNAF 3
- FNAF 4
- FNAF UCN (Ultimate Custom Night)

(The Rest is optional)

- FNAF 5 (Sister Location)
- FNAF 6 (Pizza Simulator)

**Comment by aeiea** [comment]
the reason no unblocked game sites with fnaf exist bec of copyright

we already had the repo taken down

**Comment by Rahib777-7** [comment]
> ### What is this request?
> New game
> 
> ### If you said other in the dropdown above, please specify what below
> _No response_
> 
> ### Please describe the new feature here
> I'd like you guys to add(at least)
> 
> * FNAF 1
> * FNAF 2
> * FNAF 3
> * FNAF 4
> * FNAF UCN (Ultimate Custom Night)
> 
> (The Rest is optional)
> 
> * FNAF 5 (Sister Location)
> * FNAF 6 (Pizza Simulator)

links?
