### ISSUE TITLE
Add Yoshis Fabrication Station

### ISSUE THREAD

**Issue by boomboomaladirt** [3kh0/3kh0.github.io#27]
### What is this request?

New game

### Please describe the new feature here

this game is basically mario maker, but yoshis island. its rlly good and I have a link [here it is](https://luigibonus.com/files/games/YoshisFabricationStation/)
![image](https://user-images.githubusercontent.com/99102801/188062200-a9648038-f93a-4914-8cb2-9c877947bb26.png)

**Comment by Piplup7575** [comment]
Will look into it!

**Comment by nicolasog12** [comment]
Darn it looks real retro

**Comment by Piplup7575** [comment]
On it right now!

**Comment by Piplup7575** [comment]
see #155
