### ISSUE TITLE
Add spinningrat.online

### ISSUE THREAD

**Issue by 3kh0** [3kh0/3kh0.github.io#275]
### What is this request?

New game

### Please describe the new feature here

https://spinningrat.online/

bro it spins

**Comment by 3kh0** [comment]
I think i can do this

**Comment by MasterFish999** [comment]
![image](https://user-images.githubusercontent.com/113552694/201718684-db30e7d1-5935-411f-9d9b-aae7ee6b787d.png)

**Comment by 3kh0** [comment]
Can someone else do this? I think I am doing it wrong

**Comment by SipSup3314** [comment]
@3kh0 dude i think i got it no cap. i tested it without wifi and it still works completely. i had to make some changes to the main.js file so it can work without being the root folder, and so it doesn't try to ping the actual site. i also had to download humanize-duration.min.js.
I will make a pull with the files.

**Comment by SipSup3314** [comment]
@3kh0 Close issue
