### ISSUE TITLE
Feature Request: Pirated Shows and Movies

### ISSUE THREAD

**Issue by Rahib777-7** [3kh0/3kh0.github.io#275]
### What is this request?

Something else

### If you said other in the dropdown above, please specify what below

pirated movies

### Please describe the new feature here

pirated movies are nice to watch at school

**Comment by Rahib777-7** [comment]
actually nvm we dont need it

**Comment by Rahib777-7** [comment]
i can contribute some if you want

**Comment by 3kh0** [comment]
That violates github's ToS

**Comment by Rahib777-7** [comment]
but wait doesnt game piracy also?
