### ISSUE TITLE
Ice Age Baby 2 not working

### ISSUE THREAD

**Issue by jefferysonn** [3kh0/3kh0.github.io#276]
### Check these boxes to make sure you did everything right!

- [X] I have made sure that this issue does not already exist
- [X] I have submitted screenshots of the error
- [X] You are not using the website on any clones (you are using 3kh0.github.io and nothing else)
- [ ] I just checked all of these boxes without reading the labels

### What browser are you using?

Google Chrome

### What device are you using?

Chromebook

### Please explain the issue

![Screenshot 2023-03-28 10 38 50 AM](https://user-images.githubusercontent.com/120418290/228274329-4945944d-4a08-407c-bfa3-855622b88599.png)

file doesnt exist for some reason

**Comment by Russell2259** [comment]
The file does exist, but because of strict mime types it won't load it. Nothing we can fix as it is also an issue an a few other games.

**Comment by aeiea** [comment]
I think it's bec of the file being too big, but this could be solved by being able to switch CDNs...

at the cost of echo's aws bill.

YOu could host ur own cdn using Russell2259/3kh0-CDN but u need a buff af server.

**Comment by Russell2259** [comment]
> I think it's bec of the file being too big, but this could be solved by being able to switch CDNs...
> 
> at the cost of echo's aws bill.
> 
> YOu could host ur own cdn using Russell2259/3kh0-CDN but u need a buff af server.

You can host the server for free on https://render.com

**Comment by aeiea** [comment]
the 98.99 mb of unity framework will take ur useable data like stealing candy from a baby
