### ISSUE TITLE
Add Rift v2

### ISSUE THREAD

**Issue by jefferysonn** [3kh0/3kh0.github.io#277]
### What is this request?

Something else

### If you said other in the dropdown above, please specify what below

Bringing back The Rift

### Please describe the new feature here

Bring back the rift, but make it harder and longer

**Comment by Russell2259** [comment]
You need a link for this issue to be valid.

**Comment by 3kh0** [comment]
Not going to happen

**Comment by jefferysonn** [comment]
y

**Comment by aeiea** [comment]
did you read the [guidelines?](https://github.com/3kh0/3kh0.github.io/issues/274)
