### ISSUE TITLE
UPDATE THE WEBSITE

### ISSUE THREAD

**Issue by wearebuilders1233** [3kh0/3kh0.github.io#28]
### What is this request?

Something else

### If you said other in the dropdown above, please specify what below

The website is not being updated

### Please describe the new feature here

You get the point

**Comment by wearebuilders1233** [comment]
Oh yeah and the netlify version is outdated

**Comment by wearebuilders1233** [comment]
Thats what I meant by update it

**Comment by wearebuilders1233** [comment]
Also a few more things, there are WAY too many ads, and we are missing a bunch of features from the v2 so.. yeah

**Comment by wearebuilders1233** [comment]
I mean there was an about, the cookies notification can't be closed because of the ads, and the proxies and about:blank thing are gone, please add them back

**Comment by 3kh0** [comment]
They are still there

![image](https://user-images.githubusercontent.com/58097612/188269630-68b52a95-89e6-4a25-a216-9cc118156b3f.png)

**Comment by nicolasog12** [comment]
I think he means that the netlify version is outdated, it still uses the v2 website

**Comment by nicolasog12** [comment]
Just take this site's new ZIP file and import it to your 3kh0.netlify.app
