### ISSUE TITLE
Anti-tab-close

### ISSUE THREAD

**Issue by aeiea** [3kh0/3kh0.github.io#281]
### What is this request?

New feature

### Check these boxes to make sure you did everything right!

- [X] I have made sure that this feature request does not already exist
- [ ] I have submitted a link for the game
- [X] I have read(and will comply to) the issues guideline(which can be found here)
- [ ] I just checked all of these boxes without reading the labels

### Please describe the new feature here

Anti-tab-close. A real mouthful, but it is extremely useful. I think there is a demo on TGCoffcial.github.io, and it uses the `beforeunload` event to send an `alert()` with `Unsaved changes` prompt.

**Comment by aeiea** [comment]
Found the code for it!
```javascript
  <script>
  function anticlose() {
  window.onbeforeunload = confirmExit;
  function confirmExit() {
  return "Anti-Close";
  }}
  </script>
```

**Comment by Russell2259** [comment]
Painfully annoying for the user, as it shows up every time you go to a new page.

**Comment by DapperLS-Bot-Dev** [comment]
Wont fix, closing issue
