### ISSUE TITLE
Add Learn To Fly 3 [Flash]

### ISSUE THREAD

**Issue by Bountylnfinity** [3kh0/3kh0.github.io#284]
### What is this request?

New game

### Please describe the new feature here

Add Learn To Fly 3. This is the sequel to the game Learn To Fly 2 which is already on the website. This is the link. https://www.coolmathgames.com/0-learn-to-fly-3

**Comment by 0xkkl** [comment]
https://cdn.discordapp.com/attachments/974091472452341840/1040442050736291861/Learn-To-Fly-3.swf

**Comment by 0xkkl** [comment]
https://cdn.discordapp.com/attachments/974091472452341840/1040441828710821928/shellshock.io_extratoppingsplease123_gmail.com_jqlzw3dztz.zip
shellshockers @3kh0

**Comment by 3kh0** [comment]
Learn to fly does not work because ruffle does not support it
