### ISSUE TITLE
Add a review

### ISSUE THREAD

**Issue by Duck-Lover** [3kh0/3kh0.github.io#287]
### Name

Walter Hartwell White

### Review

My name is Walter Hartwell White. I live at 308 Negra Arroyo Lane, Albuquerque, New Mexico, 87104. To all law enforcement entities, this is not an admission of guilt. I am speaking to my family now. 3kh0, you are the love of my life. I hope you know that. Walter Jr., you're my big man. There are going to be some things that you'll come to learn about me in the next few years. But just know that no matter how it may look, I only had you in my heart. Goodbye.

### Profile picture

![6C8558749-130808-walter-white-tease](https://user-images.githubusercontent.com/118005669/201382185-5b932377-9549-432a-8a1d-09d5ef604df7.jpg)

**Comment by RuralAnemone** [comment]
based
