### ISSUE TITLE
PLEASE UPDATE THE NETLIFY.APP VERSION!

### ISSUE THREAD

**Issue by nicolasog12** [3kh0/3kh0.github.io#29]
### What is this request?

Something else

### If you said other in the dropdown above, please specify what below

netlify.app update

### Please describe the new feature here

# Update the netlify.app version
- When you go to 3kh0.netlify.app, it still uses the old v2 site with "have a good summer," so please update that!

**Comment by 3kh0** [comment]
I do not own that site, so I can not do anything about that
