### ISSUE TITLE
404 page

### ISSUE THREAD

**Issue by boomboomaladirt** [3kh0/3kh0.github.io#3]
### Check these boxes to make sure you did everything right!

- [X] I have made sure that this issue does not already exist
- [X] I have submitted screenshots of the error
- [X] You are not using the website on any clones (you are using 3kh0.github.io and nothing else)
- [ ] I just checked all of these boxes without reading the labels

### What browser are you using?

Google Chrome

### What device are you using?

Chromebook

### Please explain the issue

when you try to load up the site, it shows a 404 page.
![Screenshot 2022-08-28 12 01 23 PM](https://user-images.githubusercontent.com/99102801/187090383-5cb70a34-607c-4ac5-b07c-2f83e6726af1.png)
 also, **FIRST ISSUE YEAHHHHHH**

**Comment by 3kh0** [comment]
This has been fixed
