### ISSUE TITLE
[Bug] Bad Ice Cream 1, 2, and 3 not working

### ISSUE THREAD

**Issue by Bountylnfinity** [3kh0/3kh0.github.io#306]
### Check these boxes to make sure you did everything right!

- [X] I have made sure that this issue does not already exist
- [X] I have submitted screenshots of the error
- [X] You are not using the website on any clones (you are using 3kh0.github.io and nothing else)
- [ ] I just checked all of these boxes without reading the labels

### What browser are you using?

Apple Safari

### What device are you using?

iPad

### Please explain the issue

Bad Ice Cream 1, 2, and 3 have broken links because the lots of the file names have spaces. I can not do it for 6 days because I am on the iPad.
![42B3C43B-F2E9-4289-9D65-523456E7F071](https://user-images.githubusercontent.com/105021032/201706363-46111327-3289-402c-9ea9-8ffc95bbefe2.png)
![3FB6FD1F-94A2-437D-B3E6-B66E184C16DA](https://user-images.githubusercontent.com/105021032/201706367-546eb408-276d-42a1-a8f2-5e6c3e9e7b8a.png)

**Comment by 3kh0** [comment]
ok i will fix this

**Comment by RetroWonder** [comment]
My pull request fixes it!

**Comment by 3kh0** [comment]
Fixed in #324
