### ISSUE TITLE
Add Space Company

### ISSUE THREAD

**Issue by Bountylnfinity** [3kh0/3kh0.github.io#309]
### What is this request?

New game

### Please describe the new feature here

Add Space Company. I can add it on the weekend if no one can do it before. This is the link. https://github.com/sparticle999/SpaceCompany

**Comment by Proph3t-3036** [comment]
Ok this is kinda easy, just download and upload

**Comment by Proph3t-3036** [comment]
@Bountylnfinity see if you can do it yourself (if possible)

**Comment by Bountylnfinity** [comment]
Yeah I have to do it on the weekend though because the school gives out iPads and not Chomebooks/Computers. I can do it on the weekend when I can log on to the computer.

**Comment by 3kh0** [comment]
@Bountylnfinity alr, you can do it
