### ISSUE TITLE
[Bug] 1v1.lol going to the App Store

### ISSUE THREAD

**Issue by Bountylnfinity** [3kh0/3kh0.github.io#314]
### Check these boxes to make sure you did everything right!

- [X] I have made sure that this issue does not already exist
- [X] I have submitted screenshots of the error
- [X] You are not using the website on any clones (you are using 3kh0.github.io and nothing else)
- [ ] I just checked all of these boxes without reading the labels

### What browser are you using?

Apple Safari

### What device are you using?

iPad

### Please explain the issue

1v1.lol goes to the App Store.

**Comment by RuralAnemone** [comment]
how is this a bug...?

**Comment by Bountylnfinity** [comment]
![5B061510-88E3-42BF-8E13-CC95A60EF56A](https://user-images.githubusercontent.com/105021032/201982286-0b9a058e-74d1-47e9-a0c4-b9594a570b62.jpeg)

**Comment by Bountylnfinity** [comment]
![C88FC8EE-4CA2-4D10-8E86-034820AB0D8A](https://user-images.githubusercontent.com/105021032/201983603-5882a986-4595-40c7-af55-1955f8492764.jpeg)
Does it take all of this to redirect?

**Comment by Bountylnfinity** [comment]
All you need to do
window.open(‘https://apps.apple.com/app/id1508620125’, ‘_self’);

**Comment by Bennebotix** [comment]
```JavaScript
var userAgent = navigator.userAgent || navigator.vendor || window.opera;

if (/bot|crawler|spider|crawling/i.test(userAgent)) {
    // do nothing
}

// Windows Phone
else if (/windows phone/i.test(userAgent)) {
    window.location.replace("/mobile");
}

// Android
else if (/android/i.test(userAgent)) {
    window.location.replace("https://play.google.com/store/apps/details?id=lol.onevone");
}

// iOS
else if ((/iPad|iPhone|iPod/.test(userAgent) && !window.MSStream)
|| (navigator.maxTouchPoints && navigator.maxTouchPoints > 2 && /MacIntel/.test(navigator.platform))) {
    window.location.replace("https://apps.apple.com/app/id1508620125");
}
```

This Is Probaly Why.

**Comment by Bennebotix** [comment]
[3kh0.github.io](https://github.com/3kh0/3kh0.github.io/tree/main/) / [projects](https://github.com/3kh0/3kh0.github.io/tree/main/projects) / [1v1lol](https://github.com/3kh0/3kh0.github.io/tree/main/projects/1v1lol) / [js](https://github.com/3kh0/3kh0.github.io/tree/main/projects/1v1lol/js) / [mobileRedirect.js](https://github.com/3kh0/3kh0.github.io/tree/main/projects/1v1lol/js/mobileRedirect.js)

**Comment by 3kh0** [comment]
Ok I can fix this
