### ISSUE TITLE
Add Vex 7

### ISSUE THREAD

**Issue by 3kh0** [3kh0/3kh0.github.io#320]
### What is this request?

New game

### Please describe the new feature here

Another one!

### Links
https://www.crazygames.com/game/vex-7
https://vex-7.com/

**Comment by RuralAnemone** [comment]
ayo?
there's a vex 7??? 😳

**Comment by 3kh0** [comment]
@RuralAnemone ikr?

**Comment by RetroWonder** [comment]
My pull request adds it!

**Comment by 3kh0** [comment]
Done in #324
