### ISSUE TITLE
Add Super Stacker

### ISSUE THREAD

**Issue by Dual-stars** [3kh0/3kh0.github.io#322]
### What is this request?

New game

### Please describe the new feature here

Hello! I was a little surprised to not see Super Stacker on the site considering it is a very popular flash game. It would be nice to stack those blocks while having free time in class.. so can you add Super Stacker (both 1 and 2 if available) to the site? Very appreciated !

**Comment by 3kh0** [comment]
@Dual-stars Can you find any links to this game? Poki, crazy games, anything like that

**Comment by Dual-stars** [comment]
Sure thing ^-^
Super Stacker 2: http://m.arcadethunder.com/play/super-stacker-2 (HTML5)
Super Stacker 1: https://www.kongregate.com/games/inxile_ent/super-stacker (Flash-ruffle)

Strangely enough, 1 was nearly impossible to find, while 2 came up in the first few results

**Comment by 3kh0** [comment]
Low quality
