### ISSUE TITLE
Add setting for particles

### ISSUE THREAD

**Issue by RetroWonder** [3kh0/3kh0.github.io#325]
### What is this request?

Something else

### If you said other in the dropdown above, please specify what below

Bring the particles back!

### Please describe the new feature here

Bring the particles back. We need them.

**Comment by 3kh0** [comment]
@RetroWonder I do like the idea, should I just have a particle playground where you can play with them? Since I want the homepage to be fast, and the render of the particles slow it down.

**Comment by Pepperoni-png** [comment]
i think you should add an option in settings for if you want particles or not (disabled by default) @3kh0

**Comment by 3kh0** [comment]
@Pepperoni-png Ahh, that is a good idea, I will see what I can do with that

**Comment by Pepperoni-png** [comment]
thanks

**Comment by RetroWonder** [comment]
> @RetroWonder I do like the idea, should I just have a particle playground where you can play with them? Since I want the homepage to be fast, and the render of the particles slow it down.

If you want the homepage to be fast, why is there so many ads? 💀

**Comment by 3kh0** [comment]
@RetroWonder The ads slow it down, so I want everything else as fast as possible
