### ISSUE TITLE
Add linux vm

### ISSUE THREAD

**Issue by 3kh0** [3kh0/3kh0.github.io#328]
### What is this request?

New game

### Please describe the new feature here

Linkie here: https://github.com/ruochenjia/vmlinux

I will work on this

**Comment by 3kh0** [comment]
i cant get it to work, see if you can do it

**Comment by 3kh0** [comment]
only allows up to 25mb, the zip file is 74mb.

**Comment by SipSup3314** [comment]
@3kh0 if you use git from the command line or github desktop, you can upload files up to 100mb, and if you configure git-lfs, you can have up to 5gb.

**Comment by 3kh0** [comment]
@SipSup3314 I was trying to upload the zip file of the code I got but it was too big

**Comment by 3kh0** [comment]
Does not seem to work
