### ISSUE TITLE
idea: load `/projects.html` the same way that `/projects/webretro/roms.html` does

### ISSUE THREAD

**Issue by RuralAnemone** [3kh0/3kh0.github.io#332]
### What is this request?

New feature

### Please describe the new feature here

I could do a pr but I'm wondering what the implications of switching over to this method of adding games would be,
like,
would it be easier to add games this way? how would it impact load speed? (for better or worse?) etc

**Comment by 3kh0** [comment]
It could be easier, see what you can do.

**Comment by RuralAnemone** [comment]
it should work just fine
though it'll take lots of tedious effort I think

unless I can automate it 👀

**Comment by RuralAnemone** [comment]
also, are the hot/new labels manually added or are they dynamically loaded by some js that I'm not aware of?

**Comment by RetroWonder** [comment]
> also, are the hot/new labels manually added or are they dynamically loaded by some js that I'm not aware of?

Manually added, just a div element

**Comment by RuralAnemone** [comment]
ah ok good to know :)

**Comment by 3kh0** [comment]
Done in v4
