### ISSUE TITLE
ITS BLOCKED!!

### ISSUE THREAD

**Issue by Dom914** [3kh0/3kh0.github.io#34]
**Describe the Vulnerability** 
they blocked it pls help me
**To Reproduce**

Go to '...'
Click on '....'
Scroll down to '....'
See error

**Additional context**

**Comment by 3kh0** [comment]
Please let me know what links are blocked, is replit, vercel, or netify blocked?

**Comment by 3kh0** [comment]
Closed to due to inactivity
