### ISSUE TITLE
Add Drive Mad

### ISSUE THREAD

**Issue by RobertW4sTaken** [3kh0/3kh0.github.io#34]
### What is this request?

New game

### Please describe the new feature here

Can you add ¨drive mad¨ heres the link: https://play.fancade.com/5F084A0BCE06B710

**Comment by 3kh0** [comment]
I will work on this, damn this is a fun game!

**Comment by RobertW4sTaken** [comment]
Would it help if I gave you a poki link?

**Comment by RobertW4sTaken** [comment]
If so here https://poki.com/en/g/drive-mad#fullscreen

**Comment by RobertW4sTaken** [comment]
Still there?

**Comment by 3kh0** [comment]
I am, this game is very hard to get but I will keep on working on it!

**Comment by RobertW4sTaken** [comment]
Ok. Thank you

**Comment by 3kh0** [comment]
I can not get the actual game onto GitHub due it being really, really weird. I am now just doing a simple iframe, it might be blocked, it might not, this is only because of Fancade making it hard to get the games off their website

**Comment by 3kh0** [comment]
I will close this for now but if it does not work make a new issue
