### ISSUE TITLE
Add a review

### ISSUE THREAD

**Issue by Duck-Lover** [3kh0/3kh0.github.io#342]
### Name

Skyler White

### Review

Well, my name is Skyler White yo 🤨💥
My husband is 3kh0 yo 🤨💥
Uh huh🤨💥
He told me everything🤨💥

### Profile picture

![artworks-1mYz6WX9TGrQhzN7-zZ44VA-t500x500](https://user-images.githubusercontent.com/118005669/202463320-a6d981bc-2e0d-4537-a8ed-a5b6e779d77d.jpg)

**Comment by Pepperoni-png** [comment]
i like this one, lol
