### ISSUE TITLE
Transition to Material Design

### ISSUE THREAD

**Issue by 3kh0** [3kh0/3kh0.github.io#345]
Material Design is a very nice looking library made to make things look soon.

Installing: https://m3.material.io/develop/web
Coming soon

This is for version 2, the current one is version 3, we are waiting on them to make it work for web

**Comment by fo-od** [comment]
ooh im interested in this

**Comment by fo-od** [comment]
but i think that  you shouldnt switch and the site should have its own style (i might do some concepts on figma)

**Comment by fo-od** [comment]
nvm not doing figma at all i hate it just gonna test things through github pages

**Comment by 3kh0** [comment]
lol

**Comment by kurbus** [comment]
look material's framework is used for building new web apps instead of refactoring old ones. i think our best option here would be to just overhaul most of the frontend and then call it a day, instead of refactoring for material design

**Comment by 3kh0** [comment]
Yeah mostly for just the frontend, nothing on the back end, this will still stay a static site

**Comment by kurbus** [comment]
> Yeah mostly for just the frontend, nothing on the back end, this will still stay a static site

i don't do frontend, that's your job
so are we using material design or not

**Comment by 3kh0** [comment]
Yeah, we will do it, but we are not doing anything server side

**Comment by 3kh0** [comment]
Got some screenshots form @Nebelung-Dev that might sway me towards something else

![image](https://user-images.githubusercontent.com/58097612/211124741-e67488df-dd6e-4f6f-9212-654fd8dcdbeb.png)
![image](https://user-images.githubusercontent.com/58097612/211124746-46b6e89d-a913-4a21-96e5-1d993d64464f.png)
