### ISSUE TITLE
Add Wall smash

### ISSUE THREAD

**Issue by Repsitechcoder** [3kh0/3kh0.github.io#347]
### What is this request?

New game

### Please describe the new feature here

Wallsmash

This is the link:
http://wallsmash.com/

**Comment by 3kh0** [comment]
Gotta love some of those usernames 😏

**Comment by SipSup3314** [comment]
@Repsicoder I have the code for Wall Smash. I will create a pull request for it once my other one gets merged.

**Comment by Repsicoder** [comment]
Got it.

**Comment by Bountylnfinity** [comment]
Done

**Comment by SipSup3314** [comment]
Close this issue?

**Comment by Bennebotix** [comment]
I Got The Code Then Created My Private Server With My Friends.
I Can Create One For 3kh0.

**Comment by 3kh0** [comment]
@Bennebotix If you can do that, that would be pretty epic, I am going to close this for now
