### ISSUE TITLE
this is a message you need to see

### ISSUE THREAD

**Issue by doixer** [3kh0/3kh0.github.io#35]
### What is this request?

Something else

### If you said other in the dropdown above, please specify what below

smileman.github.io got blocked for me and a BUNCH of my friends 

### Please describe the new feature here

##READme

if you have a way of changing the URL or something but the games are blocked not the homepage, it's blocked once you click on it. Or if there is a way I can access it by getting around the block wall.

*Thanks

sincerely doixer

p.s. get back to me once you have a solution_

**Comment by fo-od** [comment]
just deploy your own, use netlify its free and probably not blocked, it isnt for me, but idrk, or you could fork the repo and deploy it with github pages

**Comment by fo-od** [comment]
use this site if you want https://3kh-05.netlify.app/

**Comment by 3kh0** [comment]
You can also look at this guide to deploy with GitHub pages: https://github.com/3kh0/3kh0.github.io/wiki/Guide:-Deploying-a-site-with-GitHub

**Comment by doixer** [comment]
Hey thanks A BUNCH
I will try this out and get back to you
