### ISSUE TITLE
FInd a better way to display projects

### ISSUE THREAD

**Issue by 3kh0** [3kh0/3kh0.github.io#35]
I am looking for better ways to display projects under the projects tab, leave any suggestions here!

**Comment by nicolasog12** [comment]
Maybe turn it into a sperate webpage or make the popup bigger? It does help that they are in alphabetical order (pls dont change that).

**Comment by nicolasog12** [comment]
> It does help that they are in alphabetical order (pls dont change that).
**Commenting on myself, you should probably add something that changes the order
(newest, oldest, a-z, z-a, etc..)**

**Comment by boomboomaladirt** [comment]
maybe when you hover over the play button, screenshots of gameplay can appear from behind the icon of the game.

**Comment by Piplup7575** [comment]
#91
there

**Comment by kenken277** [comment]
> I am looking for better ways to display projects under the projects tab, leave any suggestions here!

Please fix Bitlife maybe?

**Comment by mookie22** [comment]
how does echo put projects on his his 3kh0

**Comment by 3kh0** [comment]
@mookie22 what do you mean?

**Comment by RuralAnemone** [comment]
also one gripe I have is that I can't ctrl+click the buttons

**Comment by 3kh0** [comment]
i see

**Comment by fo-od** [comment]
button to look for games in category (like the icons but you can click for games with a specific icon) or just make it easier to find offline support games
