### ISSUE TITLE
Add a review

### ISSUE THREAD

**Issue by 3xionDevelopment** [3kh0/3kh0.github.io#352]
### Name

3xion

### Review

Nah bro, we know this is the real you. I've known you since last year (Discord), it's me, nolaneo. This is the real Echo, people.

### Profile picture

![untitled (1)](https://user-images.githubusercontent.com/88562716/203061114-bb0488b9-685f-43bd-b502-ec44b4d01ca4.png)

**Comment by 3kh0** [comment]
You have already made a review, sorry!
