### ISSUE TITLE
[Bug] Learn to fly 2 is not supported by ruffle

### ISSUE THREAD

**Issue by BluePotato102** [3kh0/3kh0.github.io#357]
### Check these boxes to make sure you did everything right!

- [X] I have made sure that this issue does not already exist
- [X] I have submitted screenshots of the error
- [X] You are not using the website on any clones (you are using 3kh0.github.io and nothing else)
- [ ] I just checked all of these boxes without reading the labels

### What browser are you using?

Google Chrome

### What device are you using?

Windows Laptop (or any device running Windows)

### Please explain the issue

![image](https://user-images.githubusercontent.com/105396427/203652770-c8f54146-6666-4600-9874-10094b69784e.png)

Learn to fly 2 is not playable,  I don't think its supported by ruffle. When you actually start playing the game the penguin dummy just hovers.

**Comment by 3kh0** [comment]
Learn to fly is not officially supported, I will add a alert saying that it might be buggy or unplayable
