### ISSUE TITLE
Very Nice And Good 100000/10

### ISSUE THREAD

**Issue by liutristan** [3kh0/3kh0.github.io#359]
### Name

shuttle

### Review

As the owner of https://shuttle.cf/ i say the site is great! super duper funnnnnnnnn! i love it so much <333

### Profile picture

https://cdn.discordapp.com/attachments/1011754727433834586/1042974307845951488/5E74F4B7-8117-4DCB-9E58-295B64892857.jpg

**Comment by 3kh0** [comment]
![image](https://user-images.githubusercontent.com/58097612/203888355-086a4896-967f-4289-8760-e637550b06e9.png)
