### ISSUE TITLE
Add Awesome Pirates

### ISSUE THREAD

**Issue by 3kh0** [3kh0/3kh0.github.io#375]
### What is this request?

New game

### Please describe the new feature here

I found the .swf file, now you just gotta get ruffle setup and thats it

https://bigdino.com/games/awesome-pirates.swf

**Comment by OceanicCelery** [comment]
i might be stupid but i just added it into the ruffle "add swf" and it says it doesnt work

**Comment by OceanicCelery** [comment]
it doesnt support actionscript3

**Comment by 3kh0** [comment]
Ahhh thanks for the update!
