### ISSUE TITLE
Feature Request - Game Recommendation Page

### ISSUE THREAD

**Issue by MasterFish999** [3kh0/3kh0.github.io#377]
### What is this request?

New feature

### Please describe the new feature here

A Game Recommendation Page where users can leave reviews for games, this would help me find new games. I can also leave reviews for games I think are really cool. Maybe even consider categories for games to help find things you like easier. This will all help people stay on your site longer because they find a game they like much easier and don't have to scroll through the hundreds of games in hopes of finding a good one.

**Comment by 3kh0** [comment]
This would need some server side process with AI, I do not think we would be able to do something like this, sorry!
