### ISSUE TITLE
[Bug]  CSS on about:blank embedder is broken

### ISSUE THREAD

**Issue by 3kh0** [3kh0/3kh0.github.io#38]
### Check these boxes to make sure you did everything right!

- [X] I have made sure that this issue does not already exist
- [X] I have submitted screenshots of the error
- [X] You are not using the website on any clones (you are using 3kh0.github.io and nothing else)
- [ ] I just checked all of these boxes without reading the labels

### What browser are you using?

Google Chrome

### What device are you using?

Chromebook

### Please explain the issue

CSS on the about:blank embedder is broken

![image](https://user-images.githubusercontent.com/58097612/189350728-55ebe035-7f3b-41f1-8d4a-f64785438ef4.png)

**Comment by ARandomPenguin** [comment]
You deleted the CSS file. 
![image](https://user-images.githubusercontent.com/103593185/189467169-321880b6-5293-4671-a0f5-138dbc63042e.png)
You call the CSS file, but it does not exist. 
![image](https://user-images.githubusercontent.com/103593185/189467186-a26da980-43ab-4477-a11d-7d546622c053.png)
