### ISSUE TITLE
Add base ruffle

### ISSUE THREAD

**Issue by 3kh0** [3kh0/3kh0.github.io#384]
### What is this request?

New game

### Please describe the new feature here

GitHub Source: https://github.com/ruffle-rs/demo

Download: https://github.com/ruffle-rs/demo/archive/refs/heads/master.zip

This is so people can upload their own swf files

**Comment by OceanicCelery** [comment]
no
bozo

**Comment by Bountylnfinity** [comment]
@OceanicCelery please do not uselessly comment messages because they take up space in issues, and notifications. If you have anything to say that is contributing to the topic and/or conversation feel free to go ahead.
