### ISSUE TITLE
Cleaner Pathnames

### ISSUE THREAD

**Issue by Bountylnfinity** [3kh0/3kh0.github.io#386]
### What is this request?

New feature

### If you said other in the dropdown above, please specify what below

Making Pathnames Shorter

### Please describe the new feature here

I think a good feature for 3kh0.Github.io is moving projects.html to /projects/index.html because then if all the redirects are pointing to 3kh0.Github.io/projects then that is a lot cleaner 3kh0.Github.io/projects.html.

Another suggestion is having all the game redirects change from 3kh0.Github.io/projects/GameGoesHere/index.html to 3kh0.Github.io/projects/GameGoesHere

**Comment by Bountylnfinity** [comment]
I can do it as soon as possible if you assign me. I might be able to do it tonight.

**Comment by 3kh0** [comment]
Some games require that you reference to the index.html, and for apache servers, if you leave out the .html it will not work

**Comment by Bountylnfinity** [comment]
Ok, what is an example?

**Comment by 3kh0** [comment]
I cant think of them off the top of my head, it is also if you forget the slash, because then it will look for something like cookie-clicker.html in the projects directory, not index.html in the cookie-clicker directory. Having the index.html just ensures that this does not happen.

**Comment by Bountylnfinity** [comment]
Ok I understand, how about moving projects.html to projects/index.html?

**Comment by 3kh0** [comment]
You can open a pull to just add a simple redirect when someone visits projects/index.html, they will just be sent to projects.html

**Comment by Bountylnfinity** [comment]
Ok on it.

**Comment by Bountylnfinity** [comment]
Done (It was easy but I might have done it wrong lol)
