### ISSUE TITLE
3DS emulator

### ISSUE THREAD

**Issue by googoogaga42** [3kh0/3kh0.github.io#388]
### What is this request?

New feature

### Please describe the new feature here

emailed u before, would be great to have a working 3ds emulator

**Comment by 3kh0** [comment]
@googoogaga42 any links to this?

**Comment by googoogaga42** [comment]
https://www.retroarch.com try this
RetroArch<https://www.retroarch.com/>
RetroArch is a frontend for emulators, game engines and media players. It enables you to run classic games on a wide range of computers and consoles through its slick graphical interface. Settings are also unified so configuration is done once and for all.
www.retroarch.com

________________________________

**Comment by 3kh0** [comment]
I believe that retro arch already does this, take a look at it on the website!

**Comment by googoogaga42** [comment]
i think you have to download it tho, and my school blocks it all
________________________________

**Comment by SipSup3314** [comment]
https://github.com/binbashbanana/webretro
not a 3ds emulator but similar. has many retroarch cores and i believe you could add more to source code and recompile

**Comment by RuralAnemone** [comment]
...which has also been skidded onto [3kh0.github.io/projects/webretro](https://3kh0.github.io/projects/webretro)
:)

**Comment by SipSup3314** [comment]
i can try to add the 3ds core if you want. no promises that it will work tho

**Comment by googoogaga42** [comment]
that would be great thanks.
________________________________

**Comment by RuralAnemone** [comment]
although probably see [this](https://github.com/BinBashBanana/webretro/issues/27), especially since almost everyone who uses this is on a chromebook

**Comment by googoogaga42** [comment]
im on a higher end school laptop so i think it should run fine.
________________________________

**Comment by 3kh0** [comment]
Can I close this?

**Comment by JEFFERYBAZOES** [comment]
my shcool blocked it to

**Comment by googoogaga42** [comment]
yeah, doesn't look like much can be done about it so go ahead. thanks anyway
________________________________
