### ISSUE TITLE
Add a review

### ISSUE THREAD

**Issue by 3kh0Guy11** [3kh0/3kh0.github.io#391]
### Name

3kh0

### Review

Я Эхо и я русский шпион, который живет на Аляске, потому что там холодно и в России тоже холодно. Прекратите использовать программное обеспечение для перевода!

### Profile picture

![984AF12B-8622-456A-BACF-C527FF8A6A5F](https://user-images.githubusercontent.com/119551849/204951515-b06f97df-3acf-403e-8663-e8121814af5b.jpeg)

**Comment by 3kh0Guy11** [comment]
Могу ли я иметь админку на вашем основном сайте?

**Comment by 3kh0Guy11** [comment]
Я большой фанат, можно мне особое эхо нфт?

**Comment by 3kh0** [comment]
Нет, админ, извините, и нет nfts, я не собираюсь так продаваться, перестаньте использовать гугл-переводчик, ха-ха
