### ISSUE TITLE
Make all ruffle games use one file

### ISSUE THREAD

**Issue by SipSup3314** [3kh0/3kh0.github.io#393]
### What is this request?

Something else

### If you said other in the dropdown above, please specify what below

Optimization

### Please describe the new feature here

Make all flash games use a single Ruffle folder so that you can easily update ruffle on every game at once. Games can embed the Ruffle script using `../ruffle-core` or whatever directory it is in.

**Comment by SipSup3314** [comment]
Ruffle may come with optimizations and security updates for some games. Also some games might be slightly broken and ruffle updates might fix that.

**Comment by 3kh0** [comment]
Ok that does make sense, can you make a pull for it?

**Comment by SipSup3314** [comment]
Once I get access to my laptop in about an hour, I'll make one

**Comment by 3kh0** [comment]
Alright, cool!

**Comment by SipSup3314** [comment]
GitHub is blocked from my location because I am not at home. I will start on it later this afternoon or tomorrow.

**Comment by SipSup3314** [comment]
Sorry, I was not able to do this for a week. I had three midterm exams. I will try to work on it today.

**Comment by 3kh0** [comment]
Pull request closed
