### ISSUE TITLE
Remove Black Knight

### ISSUE THREAD

**Issue by Bountylnfinity** [3kh0/3kh0.github.io#395]
### What is this request?

Something else

### If you said other in the dropdown above, please specify what below

Remove Black Knight

### Please describe the new feature here

I think that we should remove Black Knight because it might be bad because of racism. This might be fine but I would rather be safe than sorry. I can remove it if you want tomorrow.

**Comment by 3kh0** [comment]
I think games should be preserved, even if it is racist. This game is not that racist.
