### ISSUE TITLE
Change Changlog Stuff

### ISSUE THREAD

**Issue by Bountylnfinity** [3kh0/3kh0.github.io#397]
### What is this request?

Something else

### If you said other in the dropdown above, please specify what below

Down

### Please describe the new feature here

While reading the whole change log (lol I read that), I saw that some times it said “added more reviews” have a “^” before them and other times they have a “+” before. This is a minor thing but I can fix it tomorrow. But which is right, the “^” or the “+”?

**Comment by 3kh0** [comment]
The ^

**Comment by Bountylnfinity** [comment]
#399

**Comment by Bountylnfinity** [comment]
Done
