### ISSUE TITLE
This site is SO GOOD. 

### ISSUE THREAD

**Issue by Eclypl3** [3kh0/3kh0.github.io#4]
This site is good enough for me to make 10 copies of it and deploying them ( I actually did that ).

**Comment by 3kh0** [comment]
ty

**Comment by IvanHoll101** [comment]
I'm slightly retarded. How do I make a copy of the website with my own URL.

**Comment by Eclypl3** [comment]
you cant. you have to fork it

**Comment by IvanHoll101** [comment]
Ok so when I fork it can I make a new version of the site under a different URL or change the URL.

**Comment by IvanHoll101** [comment]
Ok so how do I do that?
