### ISSUE TITLE
Cluster Rush crashing!

### ISSUE THREAD

**Issue by BumbleFuzzz** [3kh0/3kh0.github.io#401]
Cluster Rush is actually called Cluster Truck, but either way it does not work and keeps crashing.

**Comment by 3kh0** [comment]
@BumbleFuzzz can you provide any screenshots or videos?

**Comment by BumbleFuzzz** [comment]
> @BumbleFuzzz can you provide any screenshots or videos?

i can not, my device wont take screenshots

**Comment by 3kh0** [comment]
what kind of device is it?

**Comment by JEFFERYBAZOES** [comment]
my device can take screen shots

**Comment by BumbleFuzzz** [comment]
> what kind of device is it?

it is a chromebook, but the school has disabled camera and screenshots.

**Comment by BumbleFuzzz** [comment]
but what is happening, is that the page just stays blank.

**Comment by 3kh0** [comment]
@BumbleFuzzz Hmm, interesting, I am not able to reproduce this at all. Just as a note, cluster rush does take quite some to load, try it again, and wait 5 minutes, see if that helps.

**Comment by 3kh0** [comment]
Stale
