### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by JEFFERYBAZOES** [3kh0/3kh0.github.io#409]
### Check these boxes to make sure you did everything right!

- [X] I have made sure that this issue does not already exist
- [X] I have submitted screenshots of the error
- [X] You are not using the website on any clones (you are using 3kh0.github.io and nothing else)
- [X] I just checked all of these boxes without reading the labels

### What browser are you using?

Google Chrome

### What device are you using?

Chromebook

### Please explain the issue

so when i open eaglercraft l [3kh0](file:///home/chronos/u-514d6c1d17c4d5971369c366d1c472bf130004a4/MyFiles/Downloads/Screenshot%202022-12-03%202.10.35%20PM.png) it says 404 error and idk why

**Comment by JEFFERYBAZOES** [comment]
same for me

**Comment by JEFFERYBAZOES** [comment]
ok ty

**Comment by JEFFERYBAZOES** [comment]
if any has any advice pls let me know

**Comment by JEFFERYBAZOES** [comment]
![Screenshot 2022-12-03 2 10 34 PM](https://user-images.githubusercontent.com/119757924/205458705-ca17903c-975e-4229-8473-017c35c85fc7.png)

**Comment by JEFFERYBAZOES** [comment]
its weird

**Comment by 3kh0** [comment]
delete the bookmark, and go thorugh the website again

the link for eaglercraft has changed

**Comment by 3kh0** [comment]
I was able to reproduce this

**Comment by JEFFERYBAZOES** [comment]
whats the new link

**Comment by JEFFERYBAZOES** [comment]
can u put a url

**Comment by JEFFERYBAZOES** [comment]
or tell me whats the new url

**Comment by JEFFERYBAZOES** [comment]
pls and ty

**Comment by JEFFERYBAZOES** [comment]
um 3kh0 can you put a link or tell me the url

**Comment by 3kh0** [comment]
https://3kh0.github.io/projects/minecraft-15/index.html

**Comment by 3kh0** [comment]
https://3kh0.github.io/projects/minecraft-18/index.html for 1.8

**Comment by JEFFERYBAZOES** [comment]
which one is better?

**Comment by 3kh0** [comment]
the first one

**Comment by 3kh0** [comment]
close this when you are done

**Comment by JEFFERYBAZOES** [comment]
ok ty

**Comment by JEFFERYBAZOES** [comment]
wait close?

**Comment by JEFFERYBAZOES** [comment]
how

**Comment by Snuff655** [comment]
hello sorry for bothering I only have 1 question eaglercraft could you upload the update that is 1.18, 1.19
