### ISSUE TITLE
[Bug] Can't get in.

### ISSUE THREAD

**Issue by 1tsJustQ** [3kh0/3kh0.github.io#412]
### Check these boxes to make sure you did everything right!

- [X] I have made sure that this issue does not already exist
- [X] I have submitted screenshots of the error
- [X] You are not using the website on any clones (you are using 3kh0.github.io and nothing else)
- [ ] I just checked all of these boxes without reading the labels

### What browser are you using?

Google Chrome

### What device are you using?

Chromebook

### Please explain the issue

I'm on a **chromebook** (not a mobile device or tablet or anything). I tried getting in 3kh0 to play in my friends minecraft server. We both quickly realize that we can't get in the website. Why, we have no idea. (He also uses a chromebook and I think he also filed a complaint his username is Yaran799). 
![Screenshot 2022-12-03 23 00 22](https://user-images.githubusercontent.com/119763284/205463843-628b4b65-e3ea-410b-aa5a-c64298fb8ff7.png)

**Comment by JEFFERYBAZOES** [comment]
ye this happened to me to

**Comment by JEFFERYBAZOES** [comment]
this is the new link https://3kh0.github.io/projects/minecraft-15/index.html

**Comment by JEFFERYBAZOES** [comment]
hope this helps
