### ISSUE TITLE
Sandboxels mods

### ISSUE THREAD

**Issue by m1kecraf** [3kh0/3kh0.github.io#419]
### Check these boxes to make sure you did everything right!

- [x] I have made sure that this issue does not already exist
- [X] I have submitted screenshots of the error
- [X] You are not using the website on any clones (you are using 3kh0.github.io and nothing else)
- [ ] I just checked all of these boxes without reading the labels

### What browser are you using?

Google Chrome

### What device are you using?

Chromebook

### Please explain the issue

Because of filters in my Chromebook, the mods for sandboxes won't work
Also, I'm not sure if this should be a bug or a feature request
And I selected "I have submitted screenshots of the error", even though I didn't (because I do not know what to screenshot)

**Comment by 3kh0** [comment]
Look up how to do screenshots

**Comment by RuralAnemone** [comment]
dry toast
oh joy
inside joke

anyways try this bookmarklet and copy+paste the image into a comment:
https://github.com/ruralanemone/screenshot

**Comment by MikecraftTheCoder** [comment]
Bookmarklets are blocked
Inspect is also blocked

**Comment by MikecraftTheCoder** [comment]
Github has been acting strange recently for me
It won't let me create repositories, it won't let me rename myself, and it won't let me upload images.

**Comment by MikecraftTheCoder** [comment]
It won't let me edit my comments either.

**Comment by M1k3craft** [comment]
"Something went really wrong, and we can't process that file Try again."

**Comment by M1k3craft** [comment]
![Screenshot 2022-12-05 8 54 58 AM](https://user-images.githubusercontent.com/95430990/206241250-9743c926-6065-45d1-b9dc-b2724d7eb226.png)

**Comment by m1kecraft** [comment]
Is this not going to be fixed?

**Comment by 3kh0** [comment]
It might, just leave it open for now

**Comment by 3kh0** [comment]
Stale, not going to be fixed
