### ISSUE TITLE
[Bug]  It wont let me load into the game :(

### ISSUE THREAD

**Issue by Lando2202** [3kh0/3kh0.github.io#421]
### Check these boxes to make sure you did everything right!

- [X] I have made sure that this issue does not already exist
- [X] I have submitted screenshots of the error
- [X] You are not using the website on any clones (you are using 3kh0.github.io and nothing else)
- [ ] I just checked all of these boxes without reading the labels

### What browser are you using?

Google Chrome

### What device are you using?

Chromebook

### Please explain the issue

When i try to load into the game it says error 404

**Comment by ibrahimisthebest** [comment]
so there is a code that is missing it up
