### ISSUE TITLE
cant play eaglercraft [Bug] 

### ISSUE THREAD

**Issue by heavyhunter506** [3kh0/3kh0.github.io#422]
### Check these boxes to make sure you did everything right!

- [X] I have made sure that this issue does not already exist
- [X] I have submitted screenshots of the error
- [X] You are not using the website on any clones (you are using 3kh0.github.io and nothing else)
- [X] I just checked all of these boxes without reading the labels

### What browser are you using?

Google Chrome

### What device are you using?

Chromebook

### Please explain the issue

bug

**Comment by 3kh0** [comment]
Duplicate #409
