### ISSUE TITLE
my discord server

### ISSUE THREAD

**Issue by JEFFERYBAZOES** [3kh0/3kh0.github.io#423]
the first three ppl  to join my discord server gets mod heres the link https://discord.gg/Xbgp9Q2H8v

**Comment by JEFFERYBAZOES** [comment]
the first three ppl  to join my discord server gets mod heres the link https://discord.gg/Xbgp9Q2H8v

**Comment by JEFFERYBAZOES** [comment]
the first three ppl  to join my discord server gets mod heres the link https://discord.gg/Xbgp9Q2H8v

**Comment by RuralAnemone** [comment]
y'roue mothrer!!!

**Comment by RuralAnemone** [comment]
🤡

**Comment by 3kh0** [comment]
This is why your dad left
