### ISSUE TITLE
A chat box

### ISSUE THREAD

**Issue by 69aaa** [3kh0/3kh0.github.io#437]
### What is this request?

New feature

### Please describe the new feature here

A chatting feature (with filter ofc). You can also show the progress you made in the chat as a way to flex.

**Comment by 3kh0** [comment]
Yeah I will try this out, thanks for the idea!

**Comment by 69aaa** [comment]
You welcome

**Comment by 3kh0** [comment]
Well we have widgetbot so that works for now
