### ISSUE TITLE
[Bug] MotoX3M2 freezes after the 1st level

### ISSUE THREAD

**Issue by smileman55** [3kh0/3kh0.github.io#439]
### Check these boxes to make sure you did everything right!

- [X] I have made sure that this issue does not already exist
- [X] I have submitted screenshots of the error
- [X] You are not using the website on any clones (you are using 3kh0.github.io and nothing else)
- [ ] I just checked all of these boxes without reading the labels

### What browser are you using?

Google Chrome

### What device are you using?

Chromebook

### Please explain the issue

After almost finishing the first level of MotoX3M2 the game freezes. Nothing will work, the tab becomes unresponsive.
![Screenshot 2022-12-07 2 45 21 PM](https://user-images.githubusercontent.com/104168698/206516140-2773e410-b545-436f-be47-a560b6487821.png)

**Comment by 3kh0** [comment]
Stale, not able to reproduce
