### ISSUE TITLE
Question PLEASE READ

### ISSUE THREAD

**Issue by Hackerboykid** [3kh0/3kh0.github.io#44]
### Check these boxes to make sure you did everything right!

- [X] I have made sure that this issue does not already exist
- [X] I have submitted screenshots of the error
- [X] You are not using the website on any clones (you are using 3kh0.github.io and nothing else)
- [ ] I just checked all of these boxes without reading the labels

### What browser are you using?

Google Chrome

### What device are you using?

Chromebook

### Please explain the issue

Ok, so how do I edit your website to fit me better on the copy site I made with netlify?

**Comment by 3kh0** [comment]
Why are you trying to edit it?

**Comment by Hackerboykid** [comment]
I like customizing things to fit me better. does it affect your website?

**Comment by 3kh0** [comment]
How are you going to customize?

**Comment by Hackerboykid** [comment]
I mean, I don't really know, but I like messing around with things and learning how to make stuff like this. So I would just kind of test around.

**Comment by 3kh0** [comment]
fork this repo, then edit that fork, then deploy THAT FORK with netify

**Comment by Hackerboykid** [comment]
Thank you so much, I am very sorry if this wasted your time.

**Comment by 3kh0** [comment]
No problem!
