### ISSUE TITLE
Eaglercraft buttons not lining up properly

### ISSUE THREAD

**Issue by Lando2202** [3kh0/3kh0.github.io#441]
### Check these boxes to make sure you did everything right!

- [X] I have made sure that this issue does not already exist
- [X] I have submitted screenshots of the error
- [X] You are not using the website on any clones (you are using 3kh0.github.io and nothing else)
- [X] I just checked all of these boxes without reading the labels

### What browser are you using?

Google Chrome

### What device are you using?

Chromebook

### Please explain the issue

whenever I want to create a new world I have to put my mouse cursor way to far above in order to click the options

**Comment by Bountylnfinity** [comment]
Lol you checked all the boxes, look at the fourth.

**Comment by Lando2202** [comment]
I know I clicked all the boxes -_-

**Comment by Bountylnfinity** [comment]
Can you give more details, like the name of the game?

**Comment by Lando2202** [comment]
https://3kh0.github.io/projects/minecraft-15/index.html

**Comment by Lando2202** [comment]
that's the link

**Comment by Lando2202** [comment]
I have a video I can comment to show you

**Comment by Lando2202** [comment]
[Screen recording 2022-12-08 2.37.58 PM.webm](https://user-images.githubusercontent.com/118776990/206562802-e92e0a42-cb16-4856-9054-ef25495086c4.webm)

**Comment by Lando2202** [comment]
@Bountylnfinity

**Comment by RuralAnemone** [comment]
ah I see

it's probably an issue with either your screen resolution (or something to that effect) or with how that version of eaglercraft handles mouse inputs

I'll see if I can find something out

**Comment by RuralAnemone** [comment]
in the meantime I'd suggest saving any work you have open and going to [`chrome://restart`](chrome://restart)

**Comment by RuralAnemone** [comment]
or just restarting lol

**Comment by RuralAnemone** [comment]
ok nevermind I'm getting that too you don't have to restart :)

**Comment by RuralAnemone** [comment]
looking in to it...

**Comment by 3kh0** [comment]
Stale, not able to reproduce
