### ISSUE TITLE
Add a review

### ISSUE THREAD

**Issue by filostudy** [3kh0/3kh0.github.io#443]
### Name

Real One

### Review

You can’t add ads to a site hosted on github. You don’t even have a domain! Also, I bought the domains 3kh0.lol, 3kh0.me, 3kh0.io and 3kh0.games out of spite!

### Profile picture

![B3219B47-CC59-4F10-8252-576342D29B9B](https://user-images.githubusercontent.com/116910891/206586764-f51545ba-87a3-45a9-a681-16647912c0a6.jpeg)

**Comment by RuralAnemone** [comment]
> You can’t add ads to a site hosted on github.

???
![image](https://user-images.githubusercontent.com/64103005/206588275-d163cee2-8e38-4ae4-babf-d2666f47bade.png)

<hr>
is it more of a moral issue or a technical issue?
because the ads are showing up just fine lol

**Comment by 3kh0** [comment]
I am not planning on buying domains, plus, in most schools, the work 3kh0 is banned so it makes it pointless. Have fun with the domains i guess
