### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by Poggersbutnotpog** [3kh0/3kh0.github.io#447]
### What is this request?

Something else

### If you said other in the dropdown above, please specify what below

A proxy

### Please describe the new feature here

Can you add a womginx proxy to the 3kh0 site? Thanks

**Comment by RuralAnemone** [comment]
unfortunately not as this would require a backend, and github sites can only do stgatic frontend sites.
ultraviolet is much better and (I believe) only requires service workers to run, so it might be (more) possible

**Comment by 3kh0** [comment]
^^^ Just use Nebula, or this: https://www.youtube.com/watch?v=6CpsZPWTqxk
