### ISSUE TITLE
Update eaglercraft

### ISSUE THREAD

**Issue by Snuff655** [3kh0/3kh0.github.io#448]
### What is this request?

Something else

### If you said other in the dropdown above, please specify what below

Something else

### Please describe the new feature here

I just wanted to know if you could update the game because the game is very outdated and the new versions are 1.19 and eaglecraft is 1.15 I would say

**Comment by 3kh0** [comment]
It is 1.5, and I do not maintain that, so we need to wait on the others to add support, you can play the current version of minecraft with this video https://www.youtube.com/watch?v=6CpsZPWTqxk
