### ISSUE TITLE
[Bug] minecraft site isnt working

### ISSUE THREAD

**Issue by sStarlightGlimmerr** [3kh0/3kh0.github.io#455]
### Check these boxes to make sure you did everything right!

- [ ] I have made sure that this issue does not already exist
- [ ] I have submitted screenshots of the error
- [ ] You are not using the website on any clones (you are using 3kh0.github.io and nothing else)
- [ ] I just checked all of these boxes without reading the labels

### What browser are you using?

Google Chrome

### What device are you using?

Windows Laptop (or any device running Windows)

### Please explain the issue

minecraft site don't work anymore

**Comment by 3kh0** [comment]
Did not submit any device logs, screenshots , did not even check the boxes, possible troll
