### ISSUE TITLE
[Bug] 404 Error

### ISSUE THREAD

**Issue by infinitey1** [3kh0/3kh0.github.io#458]
### Check these boxes to make sure you did everything right!

- [X] I have made sure that this issue does not already exist
- [X] I have submitted screenshots of the error
- [X] You are not using the website on any clones (you are using 3kh0.github.io and nothing else)
- [ ] I just checked all of these boxes without reading the labels

### What browser are you using?

Google Chrome

### What device are you using?

Chromebook

### Please explain the issue

![Screenshot 2022-12-12 2 31 46 PM](https://user-images.githubusercontent.com/119757711/207137097-2308dd26-a595-45b0-a759-31b7bbb1d7ec.png) 

the discord is not working for me

**Comment by 3kh0** [comment]
Click on the more info button and take a screenshot of it
