### ISSUE TITLE
[Bug]  Typo in factory balls forever name (VERY IMPORTANT VERY VERY 😢 LOOK AT THIS)

### ISSUE THREAD

**Issue by fo-od** [3kh0/3kh0.github.io#46]
### Check these boxes to make sure you did everything right!

- [x] I have made sure that this issue does not already exist
- [X] I have submitted screenshots of the error
- [X] You are not using the website on any clones (you are using 3kh0.github.io and nothing else)
- [ ] I just checked all of these boxes without reading the labels

### What browser are you using?

Google Chrome

### What device are you using?

Chromebook

### Please explain the issue

guys 😢 😢 😢  i found a horrible thing 😢 😢 😢  i found  TYPO 😱 😱 😱  "Facotry balls forever" 😭 😭 im rolling on the floor crying because of this please fix pl0x!1!!
![image](https://user-images.githubusercontent.com/99752044/189995198-f7ee2351-c4ed-4590-a19d-8e2e5e9fe781.png)

**Comment by fo-od** [comment]
![image](https://user-images.githubusercontent.com/99752044/189995030-bb89fcaf-e810-4199-8792-a6d6aa58ec5d.png)

**Comment by 3kh0** [comment]
Ok on it (Grammarly failed me)

**Comment by fo-od** [comment]
btw why is SHADRYT in the splashes

**Comment by 3kh0** [comment]
> btw why is SHADRYT in the splashes

Replied in commit

**Comment by Aspaceman527** [comment]
that's Grammarly for you
