### ISSUE TITLE
Add Subway Surfers New York

### ISSUE THREAD

**Issue by hilfig3r** [3kh0/3kh0.github.io#468]
### What is this request?

New game

### If you said other in the dropdown above, please specify what below

Subway surfers new york

### Please describe the new feature here

can u please add subway surfers new york is a good map for no coins

**Comment by 3kh0** [comment]
Can you provide some links

**Comment by hilfig3r** [comment]
yeah https://html5.gamemonetize.co/h3qpnts7bced08e98vip63yqs83m9wzy/
