### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by Astrall9** [3kh0/3kh0.github.io#469]
### What is this request?

New game

### If you said other in the dropdown above, please specify what below

some new games to add

### Please describe the new feature here

Add the game Awsome Tanks 2 that is on cool math games and tiny fishing also on cool math games and YoHoHo.io, it would be nice if you added a multiplayer section because there are I believe enough players to make it fun if you do end up adding that the games I would suggest are mk48.io moomoo.io and deeeep.io.

**Comment by B0UNTYINFINITY** [comment]
Dupe Awesome Tanks #164 
Dupe YoHoHo.io #462 
Dupe mk48.io #166 

Also no online games, and definitely no Terraria. Do you even know how this works? Terraria costs money, it’s on steam, probably to complicated for the web and it would be a violation of copyright.

**Comment by B0UNTYINFINITY** [comment]
Pretty much all the requests are not possible, already done, or illegal.
