### ISSUE TITLE
Update Web Retro local to V6.5

### ISSUE THREAD

**Issue by PhDPigeon** [3kh0/3kh0.github.io#47]
### What is this request?

New feature

### Please describe the new feature here

Please just update it

**Comment by PhDPigeon** [comment]
also is the a version of the website v.3 that is on a different thing than github.io (just want to play it at school since they blocked github.io websites)

**Comment by 3kh0** [comment]
What emulator

**Comment by 3kh0** [comment]
@RuralAnemone can you work on this?

**Comment by PhDPigeon** [comment]
thank you please tell me if you do it @RuralAnemone

**Comment by 3kh0** [comment]
@PhDPigeon If you really want you can make a pull (idk how web retro works)

**Comment by PhDPigeon** [comment]
what is a pull request?

**Comment by PhDPigeon** [comment]
nvm its fine

**Comment by RuralAnemone** [comment]
hi

**Comment by RuralAnemone** [comment]
ok so
the thing is
I did this all manually because git is a baby and doesn't allow cloning more than like 1GB

**Comment by RuralAnemone** [comment]
and I really don't feel like doing it all again especially with the ~19 more cores added

**Comment by RuralAnemone** [comment]
my thoughts are as follows:
1. have everyone who is hosting it also host webretro and iframe to a subdomain or something like that (for hosters, hard; for me, easy; for blocking, hard)
2. update the page to one iframe which might get blocked (for hosters, easy; for me, easy; for blocking, easy)
3. I'll do it manually for a *small fee* (for hosters, easy; for me, hard; for blocking, hard)

**Comment by RuralAnemone** [comment]
:)

**Comment by PhDPigeon** [comment]
i see ty for telling me this

**Comment by RuralAnemone** [comment]
it is finished
I was an idiot and realized I could just upload the built (release) version lol

creating a pull request rn :)
