### ISSUE TITLE
Add ice age baby game

### ISSUE THREAD

**Issue by 3kh0** [3kh0/3kh0.github.io#47]
### What is this request?

New game

### Please describe the new feature here

Linked issue: https://github.com/3kh0/website-v3/issues/613

the best game ever with out a doubt. it is a beautiful game about the struggle between good and evil. The ice age baby is the major villain of our time and the world needs to band together. the ice age baby is the main antagonist of the series and has done numerous war crimes according to [Bernie Sanders] when he almost died, he escaped trough an open window. in kill the ice age baby adventure 2, he gets killed for real by gas. in the second mission he made an ghost base on mars as a ghost himself, with [Sid] protecting him. this is the link [https://kypello.itch.io/kill-the-ice-age-baby-adventure-the-game](https://github.com/3kh0/website-v3/issues/url)

thanks

[v6p9d9t4.ssl.hwcdn.net/html/2001097/Kill%20the%20Ice%20Age%20Baby%20Adventure%20The%20Game/index.html?v=1583444390](https://v6p9d9t4.ssl.hwcdn.net/html/2001097/Kill%20the%20Ice%20Age%20Baby%20Adventure%20The%20Game/index.html?v=1583444390)

![image](https://user-images.githubusercontent.com/58097612/216798634-b20ca449-1547-4543-a1eb-513c99e29b3d.png)

**Comment by Russell2259** [comment]
#138
