### ISSUE TITLE
Add Terraria

### ISSUE THREAD

**Issue by 283463296497263462364862438264687724103** [3kh0/3kh0.github.io#470]
### What is this request?

New game

### If you said other in the dropdown above, please specify what below

Big game to add

### Please describe the new feature here

(If you can it is a really big game) add Terraria (calamity mod if possible)

**Comment by 3kh0** [comment]
Any links?

**Comment by Astrall9** [comment]
I’m trying to get a link for terraria right now but I haven’t yet

YoHoHo.io: https://yohoho.io/
Tiny Fishing: https://www.coolmathgames.com/0-tiny-fishing
Awsome Tanks 2: https://www.coolmathgames.com/0-awesome-tanks-2

**Comment by Astrall9** [comment]
Online games that are fun (if GitHub is able to make online games)

http://mk48.io/
http://moomoo.io/
http://deeeep.io/

**Comment by B0UNTYINFINITY** [comment]
Online games might be possible with an i frame, but it will be hard. Terraria is out if the question and illegal, and Yohoho.io #462, mk48.io #166, and Awesome Tanks #164 are dupes. Tiny Fishing is the only one we can do easily.

**Comment by Astrall9** [comment]
What about scratch terraria

**Comment by B0UNTYINFINITY** [comment]
You implied that it was the real Terraria because you said “calamity mod if possible”. I think that the scratch versions are going to not be up to standard with the website.

**Comment by Astrall9** [comment]
Fair but still would you be able to add that or a random one that is online not steam

**Comment by B0UNTYINFINITY** [comment]
If you can add it, do it, but if you can’t I doubt that we will add it.
