### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by Garfeed33** [3kh0/3kh0.github.io#471]
### Check these boxes to make sure you did everything right!

- [X] I have made sure that this issue does not already exist
- [X] I have submitted screenshots of the error
- [X] You are not using the website on any clones (you are using 3kh0.github.io and nothing else)
- [ ] I just checked all of these boxes without reading the labels

### What browser are you using?

Google Chrome

### What device are you using?

Chromebook

### Please explain the issue

I open this game and just find that it says error 404 or whatever. It was working this morning, and just suddenly happened. The game was MineCraft (Eaglercraft I think or something like that). 
here's the link to it: [https://3kho.github.io/projects/minecraft/index.html](url)
#458 
![Error](https://user-images.githubusercontent.com/120594508/207679613-71f40540-9597-4ec2-ad2c-72b505b2d06d.PNG)

**Comment by 3kh0** [comment]
The link has changed: https://3kho.github.io/projects/minecraft-15/index.html
