### ISSUE TITLE
Review

### ISSUE THREAD

**Issue by thePrxy** [3kh0/3kh0.github.io#472]
### Name

ThePrxy

### Review

very good website and good code, do not take credit of this website, the creator and the website deservers its true credit. anyways subscribe to Foxy Proxy on youtube.

### Profile picture

![image](https://user-images.githubusercontent.com/120335986/207770426-0dd77af5-d426-4996-9cce-44a33f681b49.png)

**Comment by Piplup7575** [comment]
added review 👍
