### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by TheR0b0tMan** [3kh0/3kh0.github.io#475]
### Check these boxes to make sure you did everything right!

- [X] I have made sure that this issue does not already exist
- [X] I have submitted screenshots of the error
- [X] You are not using the website on any clones (you are using 3kh0.github.io and nothing else)
- [ ] I just checked all of these boxes without reading the labels

### What browser are you using?

Google Chrome

### What device are you using?

Chromebook

### Please explain the issue

The site just changed into an error. I'm not sure if other people have this error. 
![Screenshot 2022-12-15 12 12 39 PM](https://user-images.githubusercontent.com/120661339/207936610-26b56ac0-a17b-48d8-b427-7f397521190a.png)

**Comment by 3kh0** [comment]
https://3kh0-help.github.io/projects/minecraft-15/index.html
