### ISSUE TITLE
tank trouble

### ISSUE THREAD

**Issue by ItCameFr0mMars** [3kh0/3kh0.github.io#48]
its a rly fun and cool game, would be nice if you add it. (also how do you get the games?)

**Comment by 3kh0** [comment]
@ItCameFr0mMars can you send me a link to a site that already has it? Thank you!

**Comment by ItCameFr0mMars** [comment]
https://tanktrouble-2old.netlify.app/ , https://tanktrouble-2old.netlify.app/ , https://tanktrouble.pro/

**Comment by ItCameFr0mMars** [comment]
@3kh0

**Comment by 3kh0** [comment]
Thank you @ItCameFr0mMars, I will add this as soon as I can! 

*Also thank you for following the github guide* 😄

**Comment by 3kh0** [comment]
Ok, and that should be it! You can play the game [here](https://3kh0.github.io/projects/tank-trouble-2/).

Also, as something to brag to your friends, [here is something](https://3kh0.github.io/projects/tank-trouble-2/ItCameFr0mMars.txt).

**Comment by ItCameFr0mMars** [comment]
https://3kh0.github.io/projects/tank-trouble-2/ It shows  ```
Hello gamers! Please go [here](https://3kh0.github.io/) for better games.
Site-owners, if you are confused on why [this](https://github.com/3kh0/3kh0.github.io/wiki/Note-to-people-stealing-my-games) happened, please read this.
```

**Comment by ItCameFr0mMars** [comment]
@3kh0

**Comment by 3kh0** [comment]
Hmmm,it is not showing that for me, are you using inspect? that is the only reason that would show

**Comment by ItCameFr0mMars** [comment]
I am not using inspect. annnnnd its fixed!

**Comment by 3kh0** [comment]
> I am not using inspect. annnnnd its fixed!

great! have fun! :)
