### ISSUE TITLE
PLZ feature this

### ISSUE THREAD

**Issue by viperbot2000** [3kh0/3kh0.github.io#480]
### Name

Viperbot2000

### Review

1000/10 Echo is the best!!! back in the good old days when bookmarklets worked, he made me immune to GoGuardian!!! I love his scripts!!!

### Profile picture

https://sites.google.com/stu.palmbeachschools.org/free-tsunami/home
Is my website, echo's games saved My website!

**Comment by 3kh0** [comment]
Hey man, can you not use my games?

**Comment by RuralAnemone** [comment]
your games?!?! 😲 💀 💀 💀 
<hr>

![nahh](https://media.tenor.com/MP7OFYF41ZoAAAAC/skull-bruh.gif)

<hr>

skid alert!!!1!1

![me fr](https://media.tenor.com/unYK_P5gI-gAAAAC/bleh-meme-bleh.gif)

<hr>

hehe 😈 

but actually though don't even put a license like that on things you clearly don't own

**Comment by Piplup7575** [comment]
added review 👍
