### ISSUE TITLE
Add Hidden Page

### ISSUE THREAD

**Issue by B0UNTYINFINITY** [3kh0/3kh0.github.io#483]
### What is this request?

New game

### Please describe the new feature here

I stumbled across this cool website that looks legit, but if you click “student login” then it gives you a list of games. https://ssoportal.gq/ I was wondering if you could add that to 3kh0. I think maybe you could do 
`var hiddenPage = true (disabled by default)`
`if (hiddenPage == true) { //code here }`

Just thinking that would make certain websites harder to block.

**Comment by 3kh0** [comment]
I do not think this will be within the scope of the project, someone else can make a fork of this, but I will not be doing this.
