### ISSUE TITLE
False positive for TMS

### ISSUE THREAD

**Issue by Ash-Riot** [3kh0/3kh0.github.io#51]
3kh0.github.io blocked me from all it's games and brings me to the for the people stealing my games thing. Even though I didn't do anything I have not even posted a project.

**Comment by 3kh0** [comment]
@Ash-Riot this was me testing a new anti-steal system, it is on me for messing the site up, try refreshing the page.

**Comment by Yoshibuildercoder** [comment]
Ash-riot, this happened to me to

**Comment by 3kh0** [comment]
Closing because the issue has been fixed. Please create a new one if the issue occurs again.
