### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by makingstuffup** [3kh0/3kh0.github.io#52]
### Check these boxes to make sure you did everything right!

- [X] I have made sure that this issue does not already exist
- [X] I have submitted screenshots of the error
- [X] You are not using the website on any clones (you are using 3kh0.github.io and nothing else)
- [ ] I just checked all of these boxes without reading the labels

### What browser are you using?

Google Chrome

### What device are you using?

Chromebook

### Please explain the issue

Can't deploy to Netlify
![Screenshot 2023-02-05 10 45 50 AM](https://user-images.githubusercontent.com/105230283/216832552-ee75a91c-b0eb-4e1f-9ad6-9164c6096c50.png)

**Comment by 3kh0** [comment]
I will fix this

**Comment by 3kh0** [comment]
Fixed

**Comment by makingstuffup** [comment]
Thanks
