### ISSUE TITLE
Tetris does not start properly

### ISSUE THREAD

**Issue by u4pak** [3kh0/3kh0.github.io#54]
**Describe the bug**
The game of Tetris will not start properly.

**To Reproduce**
1. Go to [the Tetris game page](https://3kh0.github.io/projects/tetris/)
2. The game will not start.

**Expected behavior**
The game starts properly and blocks fall.

**Screenshots**
![image](https://user-images.githubusercontent.com/71219957/154540342-75a17d30-06e4-4e17-abbb-5e29cd4f238e.png)

**System information**

Operating system (eg ChromeOS or Windows): Windows 10
Browser: Chrome

**Additional context**
Started having this issue a couple of days ago, I have zero clue why it is doing this.

**Comment by Piplup7575** [comment]
can confirm, it is broken, not sure why

![image](https://user-images.githubusercontent.com/88395302/154699329-0fbc953d-5b43-4692-a01a-252176a1ee3b.png)

**Comment by u4pak** [comment]
Quick little update, I attempted to play using a fork I made a few days ago, and the game played fine.

The latest commit the fork had was ae07f87, so maybe somebody with a bit more knowledge than me could check any further commits and attempt to pinpoint the issue.

**Comment by 3kh0** [comment]
Should be fixed, try now.

https://3kh0.github.io/projects/tetris/index.html

**Comment by Piplup7575** [comment]
yep, it works, but blocks spawn outside the border

![image](https://user-images.githubusercontent.com/88395302/154997495-4753aae1-67a5-4db3-a2b8-5b258d7af936.png)

**Comment by 3kh0** [comment]
@Piplup7575 that has always been a problem and I am too lazy to fix lol
