### ISSUE TITLE
Privacy Error (ChromeOS)

### ISSUE THREAD

**Issue by Gitry305** [3kh0/3kh0.github.io#54]
### What is this request?

Something else

### If you said other in the dropdown above, please specify what below

Can you get this unblocked

### Please describe the new feature here

It says privacy error every time i open this. I am on a school chromebook

**Comment by 3kh0** [comment]
Can you send a screenshot

**Comment by RuralAnemone** [comment]
1. try clicking the triangle and typing `thisisunsafe`
2. if that doesn't work then use a vpn|phone hotspot (if you have one)
3. if none of those work then just use a different site

**Comment by RuralAnemone** [comment]
@Gitry305 does this help?

**Comment by RuralAnemone** [comment]
@Gitry305 hi have you had any luck with this?

**Comment by 3kh0** [comment]
Closing because stale
