### ISSUE TITLE
Add a review

### ISSUE THREAD

**Issue by jefferysonn** [3kh0/3kh0.github.io#55]
### Name

♡ ｃｘｒｘｍｅｌ_ｂｘｂａ ♡'s mother

### Review

website lets me play at work (i work for macrohard incorporated TM) and gives me an excuse to not talk to my child! 10/10 will use again, just please add a notification blocker so i dont have to ready what my discombobulated philosophical half eaten crawfish of a child messages me while im play- i mean working haha

### Profile picture

![download](https://user-images.githubusercontent.com/120418290/216845021-6971d620-4db0-4a57-b607-3d6c42322dea.jpg)

**Comment by kurbus** [comment]
y'all are a different breed 
3kh0 please close for cringe

**Comment by 3kh0** [comment]
No im gonna add it anyway lol

**Comment by jefferysonn** [comment]
LMAO u thought u could remove the purposeful cringe L fail bogo

**Comment by kurbus** [comment]
> LMAO u thought u could remove the purposeful cringe L fail bogo

67.101.203.98

**Comment by jefferysonn** [comment]
> 67.101.203.98

oh nooooo not an ip grabbed from pressing random numbers or getting some random 4 string of numbers seperated by a period from some website noooooo whatever will i dooooooooo waaaaaaaa im gonna cry abt it now im telling on you waaaaaaa
