### ISSUE TITLE
Blocked, How to make a copy

### ISSUE THREAD

**Issue by Hackerboykid** [3kh0/3kh0.github.io#55]
So my school has finally blocked your site, is there a way for me to update the copy of your site I made, or do I have to delete it and make another one?

**Comment by 3kh0** [comment]
You can use 2kh0.github.io, are all github domains blocked for you?

**Comment by Hackerboykid** [comment]
don't know all of the domains, but I don't think so. I got blocked just today.

**Comment by 3kh0** [comment]
try 2kh0.github.io, 1kh0.github.io

**Comment by Hackerboykid** [comment]
ok thanks
