### ISSUE TITLE
IMagine getting your account disabled smh

### ISSUE THREAD

**Issue by Piplup7575** [3kh0/3kh0.github.io#559]
[https://twitter.com/3kh0_/status/1606821806924595200](https://twitter.com/3kh0_/status/1606821806924595200)

![image](https://user-images.githubusercontent.com/88395302/209469295-f537bf9a-610a-49a3-b969-382caa95174d.png)

Hope you get it back soon before we destroy the server :)

**Comment by Piplup7575** [comment]
merry christmas am i right

**Comment by 3kh0** [comment]
lol
