### ISSUE TITLE
Add Jacksmith

### ISSUE THREAD

**Issue by PhDPigeon** [3kh0/3kh0.github.io#56]
### What is this request?

New game

### Please describe the new feature here

Please add the most goated flash game

**Comment by 3kh0** [comment]
Can you send any links?

**Comment by PhDPigeon** [comment]
oh sorry i kinda forgot i left a message here but sure

**Comment by PhDPigeon** [comment]
i think this will show you i'm not sure its blocked for me
[jacksmith](https://www.gameflare.com/online-game/jacksmith/)

**Comment by 3kh0** [comment]
alr ty

**Comment by 3kh0** [comment]
Stale, and uses action script 3
