### ISSUE TITLE
Very concerning bug with github.

### ISSUE THREAD

**Issue by Hackerboykid** [3kh0/3kh0.github.io#568]
### Check these boxes to make sure you did everything right!

- [X] I have made sure that this issue does not already exist
- [X] I have submitted screenshots of the error
- [X] You are not using the website on any clones (you are using 3kh0.github.io and nothing else)
- [ ] I just checked all of these boxes without reading the labels

### What browser are you using?

Google Chrome

### What device are you using?

Chromebook

### Please explain the issue

I keep getting @hackerboykid by random repositories, and when I see what it is, its normaly very inapropriate. but when I go to check it on github not my email, it just dissapears. I was wondering if there was a way these people could stop finding  my name, because the things that they post have all been about nudes.![Screenshot 2022-12-29 7 25 48 AM](https://user-images.githubusercontent.com/113061538/209959575-ec9d313f-8beb-4c79-9c19-20687f04b646.png)

**Comment by 3kh0** [comment]
Report this to Github, not our problem. Seems like you commented or subscribed to a post

**Comment by Hackerboykid** [comment]
thanks, just didn't know who else to ask, thanks for help though.
