### ISSUE TITLE
track how many times each game is played

### ISSUE THREAD

**Issue by RuralAnemone** [3kh0/3kh0.github.io#57]
### What is this request?

New feature

### Please describe the new feature here

...so that you can prune games that aren't ever played and save space

say a dev needs to clone another github repo into here (instead of manually uploading every single hecking file one by one)
git doesn't allow cloning more than 1GB (which this repo is well over, see screenshot)
![image](https://user-images.githubusercontent.com/64103005/191813700-5dc8167c-1e86-428e-b9fa-d7e1d5eef2ed.png)
it would be really nice to actually be able to use git is all I'm saying

**Comment by 3kh0** [comment]
YOu can still use this repo with git, I always do that with VSCode, try cloning with GitHub Desktop or Git command line

**Comment by Piplup7575** [comment]
I've been using github.dev because i don't feel like downloading vscode 
The main project I've been working on for a while is reducing the number of ruffle file duplicates we have, so hopefully that can reduce the file size.
