### ISSUE TITLE
[Bug] Stick Merge Not Working

### ISSUE THREAD

**Issue by B0UNTYINFINITY** [3kh0/3kh0.github.io#577]
### Check these boxes to make sure you did everything right!

- [X] I have made sure that this issue does not already exist
- [X] I have submitted screenshots of the error
- [X] You are not using the website on any clones (you are using 3kh0.github.io and nothing else)
- [ ] I just checked all of these boxes without reading the labels

### What browser are you using?

Apple Safari

### What device are you using?

iPad

### Please explain the issue

The first round goes fine then the loading screen is frozen. I think it has to do with the ads because the original would let you get free ads.
![A6DF17FA-0A97-4985-AADD-68E64FB2088C](https://user-images.githubusercontent.com/105021032/210261331-0a9dc98d-bb45-444e-9137-66462e3790a6.jpeg)

**Comment by 3kh0** [comment]
I am not able to reproduce this, this might be a issue with blocking, I will keep on digging

**Comment by B0UNTYINFINITY** [comment]
It might be the device, are you using an iPad?

**Comment by B0UNTYINFINITY** [comment]
I’m assuming that you are using an chromebook.

**Comment by 3kh0** [comment]
Yeah I am on a chromebook

**Comment by 3kh0** [comment]
Not able to reproduce, might be just based on device, idk
