### ISSUE TITLE
Add Santy is Home

### ISSUE THREAD

**Issue by jefferysonn** [3kh0/3kh0.github.io#578]
### What is this request?

New game

### If you said other in the dropdown above, please specify what below

https://kulurc.itch.io/santy-is-home

### Please describe the new feature here

Please add Santy is home by kulu

**Comment by jefferysonn** [comment]
Cool little horror christmas game on itch.io

**Comment by 3kh0** [comment]
Haha imagine not staring the repo lol anyway
