### ISSUE TITLE
404 ERROR

### ISSUE THREAD

**Issue by RangerCode** [3kh0/3kh0.github.io#58]
The website/game website is not working and says  404 ERROR not found when i open it i think the game got deleted or removed from the files.

**Comment by 3kh0** [comment]
Which game is this?

**Comment by RangerCode** [comment]
it is idle breakout when i open it it says 404 error i used a different
device aswell as mine and it still didnt work

**Comment by 3kh0** [comment]
Hmm what link are you using, the one that you should be using is https://3kh0.github.io/projects/idle-breakout/

**Comment by RangerCode** [comment]
no it was this one https://3kh0.github.io/idle-breakout/

**Comment by 3kh0** [comment]
@RangerCode that version has been removed. please use this one: https://3kh0.github.io/projects/idle-breakout/

**Comment by RangerCode** [comment]
i lost all my progress tho

**Comment by RangerCode** [comment]
1 more thing do you have one for friday night funkin?

**Comment by 3kh0** [comment]
Sorry, but there is the import code generator so you can get to where you left off
