### ISSUE TITLE
School Chromebook compatibility

### ISSUE THREAD

**Issue by MikecraftTheCoder** [3kh0/3kh0.github.io#58]
### What is this request?

New feature

### Please describe the new feature here

It would be a good idea to add a client that can be downloaded on a school Chromebook so kids can play on it.  (BTW it has to be a file size less than (I think) 500MB otherwise school Chromebooks will have a scan limit.)

**Comment by 3kh0** [comment]
What client do you mean?

**Comment by MikecraftTheCoder** [comment]
LIke a downloadable version

**Comment by 3kh0** [comment]
Go to the homepage, click on code, and download as zip

**Comment by wearebuilders1233** [comment]
Try just downloading a single file. Go to the page/folder you want to download in github, switch the url from github.com to github.dev (do not change the /3kh0/3kh0.github.io...) and then right click the file/folder name, then select download

**Comment by 3kh0** [comment]
^ make sure you download the whole folder as some of the game files are not all in the index.html file

**Comment by wearebuilders1233** [comment]
Also if you are downloading the entire website it takes about 5-15 minnutes (based on internet speeds) and it's 2+ GB 😨

**Comment by Piplup7575** [comment]
You can also check out https://download-directory.github.io/ it is the easiest thing I have found for downloading a specific folder from a repo
Uploading is a different story on chromebook lol

**Comment by MikecraftTheCoder** [comment]
Thank You
