### ISSUE TITLE
[Bug] Search Bar Not Working After Revert Winter Theme

### ISSUE THREAD

**Issue by B0UNTYINFINITY** [3kh0/3kh0.github.io#580]
### Check these boxes to make sure you did everything right!

- [X] I have made sure that this issue does not already exist
- [X] I have submitted screenshots of the error
- [X] You are not using the website on any clones (you are using 3kh0.github.io and nothing else)
- [ ] I just checked all of these boxes without reading the labels

### What browser are you using?

Apple Safari

### What device are you using?

iPad

### Please explain the issue

![87EC07EB-BA33-48B9-9BD7-42B779449B6F](https://user-images.githubusercontent.com/105021032/210395253-5b6abfd7-0d92-489a-be8a-3e0a2d16dfd9.jpeg)

**Comment by 3kh0** [comment]
Fixed
