### ISSUE TITLE
[Bug] Eaglercraft buttons offset

### ISSUE THREAD

**Issue by Garfeed33** [3kh0/3kh0.github.io#581]
![b](https://user-images.githubusercontent.com/120594508/210399892-9b8f5a16-e185-481a-b6d4-9b3347825160.PNG)
### Check these boxes to make sure you did everything right!

- [X] I have made sure that this issue does not already exist
- [X] I have submitted screenshots of the error
- [X] You are not using the website on any clones (you are using 3kh0.github.io and nothing else)
- [ ] I just checked all of these boxes without reading the labels

### What browser are you using?

Google Chrome

### What device are you using?

Chromebook

### Please explain the issue

I'm not quite sure if this is a bug, but there's no tab that says: "feature removal". So I load up the game (Eaglercraft), and the screen is stretched. Stuff happening would be (ex:) the mouse not lining up where it should be, and the assets not fitting correctly. I believe this is due to the fact that there is an ad that is at the bottom of the screen. You can make it drop down, but that does not fix the problem. Can you just remove this? It makes the game unplayable and it was never there before. (although, I haven't been on this game for 2 weeks so idk what happened since then)
![a](https://user-images.githubusercontent.com/120594508/210399580-37c19c82-7b4a-4aed-a5fa-6d8faa3a278b.PNG)

**Comment by 3kh0** [comment]
Alright I think I know how to fix this
