### ISSUE TITLE
[Bug] Escaping the Prison page just returns with a page saying "Not Found - Request ID: (random string)

### ISSUE THREAD

**Issue by Los-3r** [3kh0/3kh0.github.io#582]
### Check these boxes to make sure you did everything right!

- [X] I have made sure that this issue does not already exist
- [X] I have submitted screenshots of the error
- [X] You are not using the website on any clones (you are using 3kh0.github.io and nothing else)
- [ ] I just checked all of these boxes without reading the labels

### What browser are you using?

Mozilla Firefox

### What device are you using?

Windows Laptop (or any device running Windows)

### Please explain the issue

Whenever you go to the game page for Escaping the prison, it simply shows text says Not Found - Request ID: (random string)
![image](https://user-images.githubusercontent.com/66935939/210460646-e76efd8c-cb5e-45be-83a6-595b47f7b3da.png)

**Comment by kurbus** [comment]
Whatever site Echo was using to play this is gone now.
https://answers.netlify.com/t/not-found-request-id-xxx/51211/4

**Comment by Piplup7575** [comment]
looking into it rn

**Comment by Piplup7575** [comment]
see that pull for updates
