### ISSUE TITLE
Add a review

### ISSUE THREAD

**Issue by Haxnstuff** [3kh0/3kh0.github.io#587]
### Name

Haxnstuff

### Review

99 Shrimp Tempura out of 56 Bánh Xèo. Would eat at again!
[bible.txt](https://github.com/3kh0/3kh0.github.io/files/10349518/bible.txt)

### Profile picture

![S L A](https://user-images.githubusercontent.com/76791182/210707834-c90fbd29-2aef-4cb8-a1b9-33b405a05ee3.png)

**Comment by 3kh0** [comment]
Your review has a external text file, please retry your review
