### ISSUE TITLE
could you make a proxy and either make itits own thing or add it to the site

### ISSUE THREAD

**Issue by PhDPigeon** [3kh0/3kh0.github.io#59]
### What is this request?

Something else

### If you said other in the dropdown above, please specify what below

proxy

### Please describe the new feature here

not much of anything just at wanted to ask since every other proxy on the list (at least for me) is blocked

**Comment by 3kh0** [comment]
There are already many proxies, I suggest rammerhead. I do not need to make yet another one

**Comment by wearebuilders1233** [comment]
https://googlecalendar.gq - <- try this
