### ISSUE TITLE
Soccer Skills Euro Cup Not working

### ISSUE THREAD

**Issue by makingstuffup** [3kh0/3kh0.github.io#59]
### Check these boxes to make sure you did everything right!

- [X] I have made sure that this issue does not already exist
- [X] I have submitted screenshots of the error
- [X] You are not using the website on any clones (you are using 3kh0.github.io and nothing else)
- [ ] I just checked all of these boxes without reading the labels

### What browser are you using?

Google Chrome

### What device are you using?

Chromebook

### Please explain the issue

![image](https://user-images.githubusercontent.com/105230283/217099665-71e6636b-7eb3-43a9-a6ac-96a317dd18ee.png)
The game is stuck on this screen when you try to play

**Comment by 3kh0** [comment]
Oh fun, I am trying to figure out how to fix this

**Comment by 3kh0** [comment]
@makingstuffup Thank you for reporting this issue. In order to help us better understand and resolve the problem, could you please provide us with the console logs? The logs will give us valuable information about any errors or warning messages that may be related to the issue you're encountering.

**Comment by makingstuffup** [comment]
Could you do it on the original 3kh0 because I think it doesn't work there either?

**Comment by 3kh0** [comment]
no, you have to do it

**Comment by makingstuffup** [comment]
![image](https://user-images.githubusercontent.com/105230283/218146637-30b78283-d4d6-4911-9879-253db865028f.png)

**Comment by makingstuffup** [comment]
Is that right?

**Comment by 3kh0** [comment]
@makingstuffup Thanks for the screenshot, it is good.

@Russell2259 Can you see if this is still a issue, I think I have fixed the CORS errors

**Comment by Russell2259** [comment]
@3kh0 kk

**Comment by Russell2259** [comment]
Looks like it's fixed.
