### ISSUE TITLE
[Bug] Friday Night Funkin' Not Working

### ISSUE THREAD

**Issue by WhoIsEv** [3kh0/3kh0.github.io#593]
### Check these boxes to make sure you did everything right!

- [X] I have made sure that this issue does not already exist
- [X] I have submitted screenshots of the error
- [X] You are not using the website on any clones (you are using 3kh0.github.io and nothing else)
- [ ] I just checked all of these boxes without reading the labels

### What browser are you using?

Google Chrome

### What device are you using?

Windows Laptop (or any device running Windows)

### Please explain the issue

Whenever you press Enter to get into the game, the text just flashes and doesn't do anything. I tried restarting and clearing caches and stuff but nothing works. 
<img width="960" alt="doesnt load" src="https://user-images.githubusercontent.com/115486108/211041287-d357bf18-4b9b-4e28-9907-c42805d478e9.PNG">

**Comment by WhoIsEv** [comment]
https://user-images.githubusercontent.com/115486108/211041860-8572ffbf-d5e5-4cca-9fc1-7af0cb525684.mp4

Here is a video as well.

**Comment by 3kh0** [comment]
Can you try to open console or anything like that?

**Comment by 3kh0** [comment]
No errors, works fine, also tried this on a clean browser, so idk


https://user-images.githubusercontent.com/58097612/211157122-9d332aa1-4226-47a7-ae81-b61a41fb692a.mp4

**Comment by RetroWonder** [comment]
> No errors, works fine, also tried this on a clean browser, so idk
> 
>  2023-01-07.10-00-27.mp4

Weird, idk, could just be due to extentions.

**Comment by WhoIsEv** [comment]
> > No errors, works fine, also tried this on a clean browser, so idk
> > 2023-01-07.10-00-27.mp4
> 
> Weird, idk, could just be due to extentions.

You might be right. I opened console and this is what I saw: 
![image](https://user-images.githubusercontent.com/115486108/211327593-ad62bc9d-7edc-44d2-ba43-03088866f7a4.png)

**Comment by 3kh0** [comment]
Check your network, that is something on your end

**Comment by WhoIsEv** [comment]
> Check your network, that is something on your end

I figured it out, the network I was on has blocked newgrounds.com so yeah I just connect to a different network. My bad.
