### ISSUE TITLE
Add a review

### ISSUE THREAD

**Issue by videoconsole** [3kh0/3kh0.github.io#594]
### Name

Videoconsole best idiot

### Review

uhhh this website very good it has the buttons so inf/10 for me very very good makes me want mcdonald

### Profile picture

![Screenshot 2023-01-06 11 53 59 AM](https://user-images.githubusercontent.com/75755629/211059442-737422ca-612b-451f-94d3-2f74836cf994.png)

**Comment by Nebelung-Dev** [comment]
Done in v4
