### ISSUE TITLE
HI MY NAME IS JAY LOVE THE WEBSITE ngl

### ISSUE THREAD

**Issue by Jaydennnnnnnnnvdfgtyuiuytrew** [3kh0/3kh0.github.io#595]
### Name

3kh0

### Review

best website for gaming

### Profile picture

hi

**Comment by 3kh0** [comment]
Please choose a actual profile picture

**Comment by B0UNTYINFINITY** [comment]
Please enter a profile picture, or 3kh0 will pick one for you, or decline the review.
