### ISSUE TITLE
Add Contributors and Collaborators Page

### ISSUE THREAD

**Issue by B0UNTYINFINITY** [3kh0/3kh0.github.io#596]
### What is this request?

New game

### Please describe the new feature here

At least at my school lots of people are claiming that they helped create 3kh0, so I think a contributors page would be good.

**Comment by 3kh0** [comment]
Lol, tell them show you their github account, but ok

**Comment by B0UNTYINFINITY** [comment]
what’s with the “revert-winter” branch? I thought that was done.

**Comment by 3kh0** [comment]
Should be done, I will delete it

**Comment by 3kh0** [comment]
Will be added in v4
