### ISSUE TITLE
3kh0 v4

### ISSUE THREAD

**Issue by Nebelung-Dev** [3kh0/3kh0.github.io#597]
Version 4 is being developed by me. Approved by 3kh0!

Screenshots below. Source and demo soon :)

![image](https://user-images.githubusercontent.com/81875430/211124725-655e5e00-8b2f-4246-85a9-aa9065f5dfce.png)
![image](https://user-images.githubusercontent.com/81875430/211124727-9b6be88e-810b-4d13-ae68-d8aa06680187.png)

**Comment by 3kh0** [comment]
Closes #345 lol

**Comment by B0UNTYINFINITY** [comment]
Cool, I like the visual design, it looks more professional.
![2F385689-FB68-4256-B03A-8A40BBB617E7](https://user-images.githubusercontent.com/105021032/211124972-5fca4a34-4816-441d-9dca-9ef9b56248ca.jpeg)

**Comment by B0UNTYINFINITY** [comment]
Not the photo I mean.
