### ISSUE TITLE
[Bug]  when i try to go to the website using this proxy: https://sites.google.com/view/artclass-site/utilities/tunnel it says This embed was blocked by Unframed.

### ISSUE THREAD

**Issue by ReecePlayzyoutube** [3kh0/3kh0.github.io#604]
### Check these boxes to make sure you did everything right!

- [X] I have made sure that this issue does not already exist
- [X] I have submitted screenshots of the error
- [X] You are not using the website on any clones (you are using 3kh0.github.io and nothing else)
- [ ] I just checked all of these boxes without reading the labels

### What browser are you using?

Google Chrome

### What device are you using?

Chromebook

### Please explain the issue

the title kid of explains it all.

**Comment by 3kh0** [comment]
Simple fix, use the regular site, not some crappy google site

**Comment by ReecePlayzyoutube** [comment]
see that's the problem, my school blocked it using goguardian.

**Comment by 3kh0** [comment]
use a different link

**Comment by ReecePlayzyoutube** [comment]
I was not aware of alternate links.Could you provide some of the links? As
it is my school likes to block any and all alternate access links, so it
could all be for naught. It is worth a try though.

**Comment by 3kh0** [comment]
- https://discord.gg/3kh0

**Comment by ReecePlayzyoutube** [comment]
My school blocked discord. My school is an absolute nightmare when it comes
to online freedom. Every time we find a way around their system, they just
block whatever we've found. it's gotten to the point where if you find a
website, it can only be used between you and a couple friends otherwise you
risk compromising the website.

**Comment by 3kh0** [comment]
Ok use your phone or something

**Comment by ReecePlayzyoutube** [comment]
i don't have a phone

**Comment by ReecePlayzyoutube** [comment]
and the family desktop is windows xp

**Comment by 3kh0** [comment]
Ok use your desktop or a proxy
