### ISSUE TITLE
Add a review

### ISSUE THREAD

**Issue by kurbus** [3kh0/3kh0.github.io#608]
### Name

kurbus

### Review

10/10, best website, cured my diseases, i definitely am not contributing to this not at all 

### Profile picture

![download](https://user-images.githubusercontent.com/119330240/211185097-e4154942-4958-49a5-924c-34be47148c0c.jpg)

**Comment by kurbus** [comment]
I had to at some point okay

**Comment by Nebelung-Dev** [comment]
Done in v4
