### ISSUE TITLE
Please add My Singing Monsters

### ISSUE THREAD

**Issue by ReecePlayzyoutube** [3kh0/3kh0.github.io#611]
### What is this request?

New game

### Please describe the new feature here

I've tried to find an online alternative to the mobile application, but i have found nothing. i don't have any links the latest version that the website can handle will do.

**Comment by kurbus** [comment]
we can't. it's not a web app, never has been a web app. unless you can find the entire game's source code, and compile it in emscripten, no can do

**Comment by ReecePlayzyoutube** [comment]
understood, unfortunately i have zero experience with coding.
