### ISSUE TITLE
[Bug] Vex 7 Not working

### ISSUE THREAD

**Issue by BluePotato102** [3kh0/3kh0.github.io#618]
### Check these boxes to make sure you did everything right!

- [X] I have made sure that this issue does not already exist
- [X] I have submitted screenshots of the error
- [X] You are not using the website on any clones (you are using 3kh0.github.io and nothing else)
- [ ] I just checked all of these boxes without reading the labels

### What browser are you using?

Google Chrome

### What device are you using?

Chromebook

### Please explain the issue

After you beat level 1 the game freezes to see the screen attached below

![image](https://user-images.githubusercontent.com/105396427/211690505-33550d36-a113-4410-aed8-2cea83b72251.png)

**Comment by RetroWonder** [comment]
> ### Check these boxes to make sure you did everything right!
> * [x]  I have made sure that this issue does not already exist
> * [x]  I have submitted screenshots of the error
> * [x]  You are not using the website on any clones (you are using 3kh0.github.io and nothing else)
> * [ ]  I just checked all of these boxes without reading the labels
> 
> ### What browser are you using?
> Google Chrome
> 
> ### If you said other above, please specify which browser you use
> _No response_
> 
> ### What device are you using?
> Chromebook
> 
> ### If you said other above, please specify which device you use
> _No response_
> 
> ### Please explain the issue
> After you beat level 1 the game freezes to see the screen attached below
> 
> ![image](https://user-images.githubusercontent.com/105396427/211690505-33550d36-a113-4410-aed8-2cea83b72251.png)

Weird, hasn't happened to me, could be a browser issue?

**Comment by 3kh0** [comment]
Stale, end user
