### ISSUE TITLE
Vex 5

### ISSUE THREAD

**Issue by nicolasog12** [3kh0/3kh0.github.io#62]
So, after the big update we've been waiting for, I see you added a new game called vex 5.
If you could find the other "vex" games, that would be cool too!

- nico

**Comment by Piplup7575** [comment]
I'll open a pull later with code for vex4 if you want that, I'll find the code for it

**Comment by Piplup7575** [comment]
pull req open @nicolasog12! #66 
should be playable, here is a temporary link until the pull is merged. [https://3kh0-git-fork-piplup7575-vex4-3kh0.vercel.app/projects/vex4/index.html](https://3kh0-git-fork-piplup7575-vex4-3kh0.vercel.app/projects/vex4/index.html)

**Comment by 3kh0** [comment]
It has been added, Vex 4 and 5.
