### ISSUE TITLE
Reduce Files for Ruffle/Update outdated files

### ISSUE THREAD

**Issue by Piplup7575** [3kh0/3kh0.github.io#62]
Tracking for reducing file size through reducing the number of ruffle files-
ToDo:
- [ ] Figure out how to import files through URL(think webretro)
- [ ] Update Ruffle version
- [ ] Condense all flash games into one folder
- [ ] Update the games page to reflect said change 

If any one is able to help let me know!

**Comment by 3kh0** [comment]
This can affect #58 btw

**Comment by 3kh0** [comment]
Stale, and won't happen

**Comment by Piplup7575** [comment]
#449 will affect this :)
