### ISSUE TITLE
Links!

### ISSUE THREAD

**Issue by TrickJoker312** [3kh0/3kh0.github.io#620]
Are there any more links for this site? if so, please link them below. I'd really appreciate it!

**Comment by 3kh0** [comment]
You can find them here: https://discord.gg/3kh0

**Comment by TrickJoker312** [comment]
Oh..... I dont have a laptop at home, and only use my school computer, therefore I don't have discord. Could you please send them through here? I'd really appreciate it!

**Comment by 3kh0** [comment]
I dont have the links here
