### ISSUE TITLE
Add a review

### ISSUE THREAD

**Issue by platformer-io** [3kh0/3kh0.github.io#621]
### Name

coolandcrazyandweird

### Review

10000000000000000/10 the site is very kool and it is also very krazy

### Profile picture

![Screenshot 2022-12-21 12 31 21](https://user-images.githubusercontent.com/120543332/211910685-0c7304e2-9b6a-4e4b-9452-7b34bc881d2a.png)

**Comment by Nebelung-Dev** [comment]
Done in v4
