### ISSUE TITLE
Resent Client is not working

### ISSUE THREAD

**Issue by leskar00** [3kh0/3kh0.github.io#63]
### Check these boxes to make sure you did everything right!

- [X] I have made sure that this issue does not already exist
- [ ] I have submitted screenshots of the error
- [X] You are not using the website on any clones (you are using 3kh0.github.io and nothing else)
- [x] I just checked all of these boxes without reading the labels

### What browser are you using?

Google Chrome

### What device are you using?

Windows Laptop (or any device running Windows)

### Please explain the issue

Resent Client single player not working as intended. Can you please fix it when I open the single player tab it goes to a text screen and says that it my first time opening it, has to do with 1.8 update I presume

**Comment by Russell2259** [comment]
@leskar00 Do you have a screenshot?

**Comment by 3kh0** [comment]
Not enough info to determine issue
