### ISSUE TITLE
Add surviv.io

### ISSUE THREAD

**Issue by ItCameFr0mMars** [3kh0/3kh0.github.io#63]
surviv is super fun, and also blocked for almost everyone

**Comment by 3kh0** [comment]
Does it have fake multiplayer? @ItCameFr0mMars

**Comment by ItCameFr0mMars** [comment]
no, only real multiplayer @3kh0

**Comment by nicolasog12** [comment]
Added a pull request to add surviv.io
Don't mind that it's just pure html 👍

**Comment by 3kh0** [comment]
@nicolasog12 you opened #81 but it was just a embed, that will not work for some people.
