### ISSUE TITLE
Add a review

### ISSUE THREAD

**Issue by airtag8892** [3kh0/3kh0.github.io#636]
### Name

airtag#8892

### Review

very good 100/10 is best game site trust me on this ok must trust?? ok you trust me yes ty very much ily echo no homo also yk you should really join discord.gg/3kh0

### Profile picture

![c54ea87f44719a2111115818217fb9cd](https://user-images.githubusercontent.com/120539605/212207686-9de1674a-d5a0-4d57-869d-c41e830da466.png)

**Comment by Nebelung-Dev** [comment]
Done in v4
