### ISSUE TITLE
PWA

### ISSUE THREAD

**Issue by slimehands** [3kh0/3kh0.github.io#639]
### What is this request?

New feature

### Please describe the new feature here

A  [progressive web app ](https://web.dev/progressive-web-apps/) (pwa) could  that you can play games offline and install the site
I tried to make 3kh0 a pwa, but I think it's too large to load everything and would be hard to keep updating the service worker
Maybe we should make each project an individual pwa?

**Comment by 3kh0** [comment]
Way to big, if you want you can try making some poplar projects a PWA

**Comment by 3kh0** [comment]
This might be in v4
