### ISSUE TITLE
Add Push Your Luck

### ISSUE THREAD

**Issue by nicolasog12** [3kh0/3kh0.github.io#64]
You should add Push Your Luck to the website.
(if you have no idea what it is its on coolmath games, which is blocked for me)
Sorry for the two posts super close together

**Comment by 3kh0** [comment]
Can you send me the link to the a example of this game? Thanks!

**Comment by 3kh0** [comment]
I have started adding this

**Comment by 3kh0** [comment]
Complete!

Link: https://3kh0.github.io/projects/push-your-luck/index.html

Let me know if there are any issues!

**Comment by nicolasog12** [comment]
Works perfectly! Saves and no lag. Thanks!
