### ISSUE TITLE
None of the servers are working [Bug] 

### ISSUE THREAD

**Issue by TheR0b0tMan** [3kh0/3kh0.github.io#649]
### Check these boxes to make sure you did everything right!

- [X] I have made sure that this issue does not already exist
- [X] I have submitted screenshots of the error
- [X] You are not using the website on any clones (you are using 3kh0.github.io and nothing else)
- [ ] I just checked all of these boxes without reading the labels

### What browser are you using?

Google Chrome

### What device are you using?

Chromebook

### Please explain the issue

Whenever I go to multiplayer none of the servers are ever up and when I try direct connect it says connection refused even though it is my server and I can see that it is running. I am running 1.8 Eaglercraft.
![Screenshot 2023-01-17 7 43 47 PM](https://user-images.githubusercontent.com/120661339/213060745-2be5532a-5b2e-4a6c-9f94-9270eef4e8f8.png)

**Comment by DuckMob** [comment]
Could possibly be that 1.8 is still new, and some servers cant be hosted 24/7

**Comment by TheR0b0tMan** [comment]
Also, the server I am hosting myself I can't join. It is a 1.8 server I am hosting.

**Comment by TheR0b0tMan** [comment]
It is the same with 1.5 eaglercraft.

**Comment by 3kh0** [comment]
tried both clients, was able to login normally, must be that your school is blocking the servers or the relay servers. we cant fix that

**Comment by TheR0b0tMan** [comment]
Thanks
