### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by SipSup3314** [3kh0/3kh0.github.io#65]
### What is this request?

New feature

### Please describe the new feature here

Idea: so we don't have to update the navbar on every page, make it part of the main.js file so if the URL doesn't have /files/ in it, then it will create the navbar element and prepend it to the body element

**Comment by Nebelung-Dev** [comment]
It is possible but it would create a weird lag where everything would load before the navbar

**Comment by Nebelung-Dev** [comment]
This is why people use React
