### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by Hackerboykid** [3kh0/3kh0.github.io#663]
Can you add an embed section where you can copy the code from games into our own websites?
I have been making my own site, I just can't find unblocked game codes.
My website is definitely in beta and is not the greatest, but I am working on it.
My site --> totally-games.webstarts.com

**Comment by kurbus** [comment]
see license section of readme

**Comment by Hackerboykid** [comment]
ok

**Comment by Hackerboykid** [comment]
ok makes sense
