### ISSUE TITLE
site[Bug] 

### ISSUE THREAD

**Issue by idcidkwhatever** [3kh0/3kh0.github.io#665]
### Check these boxes to make sure you did everything right!

- [X] I have made sure that this issue does not already exist
- [X] I have submitted screenshots of the error
- [X] You are not using the website on any clones (you are using 3kh0.github.io and nothing else)
- [X] I just checked all of these boxes without reading the labels

### What browser are you using?

Google Chrome

### What device are you using?

Chromebook

### Please explain the issue

the issue is when i open the site it does work but every single thing is gone it only says sponsor and no image

**Comment by 3kh0** [comment]
Fixed
