### ISSUE TITLE
[Bug] [Main Page]

### ISSUE THREAD

**Issue by UltraWyatt** [3kh0/3kh0.github.io#666]
### Check these boxes to make sure you did everything right!

- [X] I have made sure that this issue does not already exist
- [X] I have submitted screenshots of the error
- [X] You are not using the website on any clones (you are using 3kh0.github.io and nothing else)
- [ ] I just checked all of these boxes without reading the labels

### What browser are you using?

Google Chrome

### What device are you using?

Chromebook

### Please explain the issue

On the main page ( 3kh0.github.io ) it just has the sponsor and nothing else. 
![image](https://user-images.githubusercontent.com/100807663/213571517-ba969813-b09c-4648-b609-996ca7fe256f.png)

**Comment by 3kh0** [comment]
ok i am aware, a fix has been made
