### ISSUE TITLE
Github Pages Fails

### ISSUE THREAD

**Issue by B0UNTYINFINITY** [3kh0/3kh0.github.io#668]
### What is this request?

New game

### Please describe the new feature here

I think that 3kh0 is to big that when github pages deploys then if the timer reaches 10 min then it aborts. I don’t have an idea on how to fix it.

**Comment by B0UNTYINFINITY** [comment]
Read https://docs.github.com/en/pages/getting-started-with-github-pages/about-github-pages#usage-limits for more information

**Comment by 3kh0** [comment]
I have reached out to them about this
