### ISSUE TITLE
Zombs Royale Won't Load

### ISSUE THREAD

**Issue by Piplup7575** [3kh0/3kh0.github.io#67]
**Describe the bug**
Zombs Royale won't load (I'm on a Chromebook with 4 gigs of ram)

**To Reproduce**
1. Go to projects
2. Click on "Zombs Royale"
3. Sit on that screen for 20 min without loading

**Expected behavior**
Should load the game

**Screenshots**
![image](https://user-images.githubusercontent.com/88395302/155224592-30de430d-f016-4dd7-984d-e5a21ab7b4b9.png)
_20 min later_

**System information**
Operating System:
ChromeOS on Chromebook 3100 Education chromebook

Browser:
Chrome

**Additional context**
Might just be my crappy Chromebook lol

**Comment by 3kh0** [comment]
Hmmm, weird! I have tried it and it loaded fine, try reloading?

**Comment by nicolasog12** [comment]
Not working for me either. Might be a code issue?

**Comment by nicolasog12** [comment]
The problem might that since it's a multiplayer game, it needs more than 1 person at a time and it's not loading but waiting for players. I'm not an expert so can't guarantee that's the issue.
