### ISSUE TITLE
[Bug] Ruffle doesn't support action script 3

### ISSUE THREAD

**Issue by Alex-A137** [3kh0/3kh0.github.io#673]
### Check these boxes to make sure you did everything right!

- [X] I have made sure that this issue does not already exist
- [X] I have submitted screenshots of the error
- [X] You are not using the website on any clones (you are using 3kh0.github.io and nothing else)
- [ ] I just checked all of these boxes without reading the labels

### What browser are you using?

Google Chrome

### What device are you using?

Chromebook

### Please explain the issue

when i try to run papa's scooperia on ruffle it says action script 3 not supported?

please fix

![image](https://user-images.githubusercontent.com/96093036/213907463-e25d6ce5-dd00-4a66-bce0-5a96181468b7.png)
![image](https://user-images.githubusercontent.com/96093036/213907465-d118fab3-b9b4-4539-a4fd-1638af5e8277.png)

**Comment by kurbus** [comment]
this isnt an us problem, it's a ruffle problem
flashpoint supports as3 but doesn't have a wasm build
continue crying about it, collaborators pls close issue

**Comment by BoxYeety** [comment]
> this isnt an us problem, it's a ruffle problem flashpoint supports as3 but doesn't have a wasm build continue crying about it, collaborators pls close issue

bro how do people not know that 💀
