### ISSUE TITLE
Add a review

### ISSUE THREAD

**Issue by Rahib777-7** [3kh0/3kh0.github.io#678]
### Name

LEGALISE PIRACY

### Review

9000/10 best site ever i can play  minecraft for free with no virus!

### Profile picture

![C29D2E4B-19D4-4D43-9F08-F7D96A09535E](https://user-images.githubusercontent.com/74979271/213944826-ef8b8835-5ce8-40db-b0ba-9fd579b450df.png)

**Comment by Rahib777-7** [comment]
should i change this review to get rid of the pirated part

**Comment by Nebelung-Dev** [comment]
Done in v4
