### ISSUE TITLE
Add me to the reviews!!!!!

### ISSUE THREAD

**Issue by nicolasog12** [3kh0/3kh0.github.io#68]
### What is this request?

Something else

### If you said other in the dropdown above, please specify what below

Reviews section of ./index.html

### Please describe the new feature here

# review
"100 out 10 best site ever love the games love the easy interface and how there's so many proxies, also ummm echo why are people in your basement uhh ok :)"

**Comment by PhDPigeon** [comment]
This is the goofiest enhancement ever

**Comment by 3kh0** [comment]
can you send me a photo you want as the profile pic?

**Comment by nicolasog12** [comment]
![99337184](https://user-images.githubusercontent.com/99337184/192534088-8c33b066-1a64-406a-be09-d5ce1179864a.png)

**Comment by 3kh0** [comment]
Alr I will work on this!

**Comment by Piplup7575** [comment]
> Alr I will work on this!

Or @nicolasog12 you could make a pull :)

**Comment by nicolasog12** [comment]
I think hes gotten  close to finished so I'll just close this so it's not filling the whole issues screen

**Comment by 3kh0** [comment]
nah i need this open or i will forgor 💀

**Comment by nicolasog12** [comment]
**yells hooray**
