### ISSUE TITLE
the fitnessgram pacer is a multistage aerobic capacity test

### ISSUE THREAD

**Issue by Professional-Chaka-Tree** [3kh0/3kh0.github.io#688]
### Name

heisenburger

### Review

> Ummm...actually....mustard gas isn't the gas form of mustard

Diviance Shukla [🤓](https://emojipedia.org/nerd-face/), the greatest philosopher of all time.

### Profile picture

![maxresdefault](https://user-images.githubusercontent.com/123597807/214695262-0a80ec5e-0b75-48f2-9b21-b4bcc9f36488.jpg)

**Comment by Nebelung-Dev** [comment]
Done in v4
