### ISSUE TITLE
Proxy Creation Request

### ISSUE THREAD

**Issue by JellyGhost** [3kh0/3kh0.github.io#69]
### What is this request?

Something else

### If you said other in the dropdown above, please specify what below

New Proxy/Unblocker

### Please describe the new feature here

An unblocker for those who can't use certain sites because they are blocked.

**Comment by nicolasog12** [comment]
A pull request with new proxies is waiting approval, it should get approved soon.
For now, just try the ones on [the proxy page](https://3kh0.github.io/dump/proxies).

**Comment by 3kh0** [comment]
@JellyGhost This repo also exists: https://github.com/3kh0/proxy-list

**Comment by 3kh0** [comment]
hehe issue 69
