### ISSUE TITLE
[Bug] Redirects blocked

### ISSUE THREAD

**Issue by THEBEST1278** [3kh0/3kh0.github.io#70]
### Check these boxes to make sure you did everything right!

- [X] I have made sure that this issue does not already exist
- [X] I have submitted screenshots of the error
- [X] You are not using the website on any clones (you are using 3kh0.github.io and nothing else)
- [ ] I just checked all of these boxes without reading the labels

### What browser are you using?

Google Chrome

### What device are you using?

Chromebook

### If you said other above, please specify which device you use

School Chromebook

### Please explain the issue

if you try to go on more stuff you cant because my school blocks redirects so I cant go in. If i change the URL to /dump it works but if i wanna use the redirect generator i cant go to the website :(. I cant send a screenshot because my school blocked screenshots too lmao

**Comment by 3kh0** [comment]
*how the heck did they block screenshots* anyway, what blocker does your school use?

**Comment by Piplup7575** [comment]
> _how the heck did they block screenshots_ 

chrome://policy :)

**Comment by RuralAnemone** [comment]
and just out of spite I am now going to make a screenshot bookmarklet

**Comment by nicolasog12** [comment]
> and just out of spite I am now going to make a screenshot bookmarklet

*sighs loudly*
So why is the issue still open?

**Comment by RuralAnemone** [comment]
try https://github.com/ruralanemone/screenshot
also what do you mean by "it gets blocked"?

**Comment by nicolasog12** [comment]
Wait how do they block a redirect page, it just has a "continue button" theres nothing in like a meta tag or something 😖

**Comment by THEBEST1278** [comment]
district uses content keeper and they blocked the website now so nvm :(

**Comment by 3kh0** [comment]
use 2kh0.github.io?

**Comment by nicolasog12** [comment]
https://1kh0.github.io
https://2kh0.github.io
https://yologolosolo.github.io (not up to date)
