### ISSUE TITLE
In snow battle it does not allow me to gain stars

### ISSUE THREAD

**Issue by NCGamer118** [3kh0/3kh0.github.io#70]
When Playing Snow battle.io when ever I win It sometimes does not allow me to gain stars.

1. Go to Snowbattle.IO
2. Click on 'play'
3. Play game and wait for the Bug to occur

I was playing snow battle.Io and It took away my stars or just does not give me any.

Operating system Crome OS
Browser: Crome

**Comment by nicolasog12** [comment]
Might be a code issue in the embed, checking it out now!

**Comment by nicolasog12** [comment]
Try it again, it's working for me.

**Comment by 3kh0** [comment]
@NCGamer118 what link are you using? make sure it is 3kh0.github.io

**Comment by 3kh0** [comment]
For me it works...

**Comment by 3kh0** [comment]
This might be just with unity, when this happens just refresh the page.
