### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by tanay6464** [3kh0/3kh0.github.io#704]
### Check these boxes to make sure you did everything right!

- [X] I have made sure that this issue does not already exist
- [X] I have submitted screenshots of the error
- [X] You are not using the website on any clones (you are using 3kh0.github.io and nothing else)
- [ ] I just checked all of these boxes without reading the labels

### What browser are you using?

Google Chrome

### What device are you using?

Chromebook

### Please explain the issue

It is blocked for my school district

**Comment by SipSup3314** [comment]
Please stop making issues about this.  
Here are a few things you can do about this:  
1. Use an unblocker  
2. Use a different deployment of the site  
3. Deploy it yourself  
We do not have access to the filters at your school, so don't expect the site to always be unblocked. It is actually blocked at my school, but you don't hear me complaining. Do not make issues about the site being blocked.

**Comment by kurbus** [comment]
he was forced to review issues on 3kh0.github.io when he was 11
*gif of seal crying*

**Comment by SipSup3314** [comment]
i do this coz i like to. i rip games by request of 3kh0.github.io users in the issues. it gives me something to do when im bored
