### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by bnbscjyihny7lm** [3kh0/3kh0.github.io#709]
### Check these boxes to make sure you did everything right!

- [X] I have made sure that this issue does not already exist
- [X] I have submitted screenshots of the error
- [X] You are not using the website on any clones (you are using 3kh0.github.io and nothing else)
- [ ] I just checked all of these boxes without reading the labels

### What browser are you using?

Google Chrome

### What device are you using?

Chromebook

### Please explain the issue

![image](https://user-images.githubusercontent.com/112220402/216110925-cf1de33b-bf2b-4c66-9da6-3e8bdb69cad1.png)

**Comment by Rahib777-7** [comment]
are you using 3kh0.github.io?

**Comment by fartsindogs** [comment]
That's what I was gonna say

**Comment by 3kh0** [comment]
You are not using the official site, so we can not help you there

**Comment by bnbscjyihny7lm** [comment]
the original site got blocked, and it doesnt work even on the original site
