### ISSUE TITLE
Zombs Royal says it is Blocked

### ISSUE THREAD

**Issue by NCGamer118** [3kh0/3kh0.github.io#71]
Every thing else is fine but zombs is blocked

1. Go to Zombs Royal
2. Click on Zombs Royal

**Expected behavior**
It is blocked

**System information**

Operating system: Chrome OS
Browser: Chrome
![Screenshot 2022-02-23 9 49 16 AM](https://user-images.githubusercontent.com/94636556/155343642-5cead2b7-c677-4ff4-8456-7f073f06848c.png)

**Comment by nicolasog12** [comment]
New link
https://nicolasog12.github.io/3kh0.github.io

**Comment by 3kh0** [comment]
Changing labels due to the fact it is not a bug, it was just blocked.
