### ISSUE TITLE
Add Hyperbolica

### ISSUE THREAD

**Issue by RuralAnemone** [3kh0/3kh0.github.io#71]
### What is this request?

New game

### Please describe the new feature here

Hyperbolica, a fairly recently made game

[steamunlocked/windows unity build link](https://steamunlocked.net/6-hyperbolica-free-download/) (or [google drive link](https://drive.google.com/file/d/1nH9PYfvsW4HyEs_ETLdG-Kd2XyEr-tOY/view?usp=sharing) for speed)
also ["unbuild" unity project](https://github.com/mafaca/UtinyRipper) if you'd like to directly make a web build

kinda the same idea as superhot

**Comment by 3kh0** [comment]
Alr i will look into this!

**Comment by 3kh0** [comment]
Not possible

**Comment by RuralAnemone** [comment]
elaborate

**Comment by 3kh0** [comment]
I can not recompile unity files, unity on linux is very spotty

**Comment by RuralAnemone** [comment]
ah ok
