### ISSUE TITLE
Make the reviews a carousel

### ISSUE THREAD

**Issue by 3kh0** [3kh0/3kh0.github.io#72]
### What is this request?

New feature

### Please describe the new feature here

We should make the reviews on the home page use a carousel system so they don't take up so much space. We should try using [Owl](https://owlcarousel2.github.io/OwlCarousel2/)

**Comment by Piplup7575** [comment]
testing can be found at https://replit.com/@piplup7575/reviews-scroll

**Comment by nicolasog12** [comment]
https://www.w3schools.com/bootstrap4/bootstrap_carousel.asp

**Comment by Piplup7575** [comment]
implemented in #73
