### ISSUE TITLE
Add Monster Tracks

### ISSUE THREAD

**Issue by imsmartbutdumb** [3kh0/3kh0.github.io#72]
### What is this request?

New game

### If you said other in the dropdown above, please specify what below

monster tracks

### Please describe the new feature here

I love this game and i want it unblocked so i can play it at school

**Comment by 3kh0** [comment]
any links or anything?

**Comment by imsmartbutdumb** [comment]
https://sites.google.com/site/thegamecompilation/car-games/monster-tracks

**Comment by imsmartbutdumb** [comment]
that game
