### ISSUE TITLE
[Bug] DOMException: Failed to register a ServiceWorker

### ISSUE THREAD

**Issue by 3kh0** [3kh0/3kh0.github.io#73]
### Check these boxes to make sure you did everything right!

- [X] I have made sure that this issue does not already exist
- [X] I have submitted screenshots of the error
- [X] You are not using the website on any clones (you are using 3kh0.github.io and nothing else)
- [ ] I just checked all of these boxes without reading the labels

### What browser are you using?

Google Chrome

### What device are you using?

Chromebook

### Please explain the issue

Raw error message:

> index.js:1 Uncaught (in promise) DOMException: Failed to register a ServiceWorker: The origin of the provided scriptURL ('https://3kh0.github.io.') does not match the current origin ('https://3kh0.github.io').

![image](https://user-images.githubusercontent.com/58097612/217696051-e116d5c4-81ad-4a84-a1a2-d591b41b3e23.png)

Error at line 1 at [js/index.js](https://3kh0.github.io/js/index.js)
```js
navigator.serviceWorker.register(location.origin + "./sw.js");
```
![image](https://user-images.githubusercontent.com/58097612/217696098-948918aa-65a8-471b-b075-d2edd369d05f.png)

**Comment by 3kh0** [comment]
Possible fix, this is because it is not at the root, so this change might work:
```js
navigator.serviceWorker.register(location.origin + "./sw.js");
```
to this
```js
navigator.serviceWorker.register(location.origin + "/sw.js");
```

**Comment by 3kh0** [comment]
Fixed

**Comment by Russell2259** [comment]
my bad
