### ISSUE TITLE
Website blocked, using iboss cloud

### ISSUE THREAD

**Issue by derinpilge** [3kh0/3kh0.github.io#73]
**Please describe what happened**

A clear and concise description of what the problem is.

**How is the site being blocked?**

Is it through a extention of network? *if you dont know it ok!*

**Which of the websites are blocked for you?**

Put a x in the brackets if it is blocked, like this: [X]

- [x] https://3kh0.vercel.app/
- [x] https://3kh0.github.io
- [x] https://3kh0.netlify.app/

**Additional context**

Please add screenshots or links here if you can!

**Comment by nicolasog12** [comment]
What device are you using?

**Comment by Piplup7575** [comment]
Probably school computer
@derinpilge Download the site, most games should load when opened. 

heres how to download
https://user-images.githubusercontent.com/88395302/151993176-e6b912f0-4903-4fd6-b28a-1dd520640590.mp4

**Comment by nicolasog12** [comment]
That should work. If not, then get the croxyproxy (not lite) extension on https://chrome.google.com/webstore/detail/croxyproxy-free-web-proxy/lmmpgfjnchldhcieiiegcpdmaidkaanb?hl=en and it will do everything for you. After that just type 3kh0.github.io and hit enter.

**Comment by 3kh0** [comment]
@derinpilge you can also try forking the repo and depolying it with pages.

**Comment by coolman3289** [comment]
How do you deploy it with pages?

**Comment by derinpilge** [comment]
> What device are you using?

Chromebook

**Comment by derinpilge** [comment]
> That should work. If not, then get the croxyproxy (not lite) extension on https://chrome.google.com/webstore/detail/croxyproxy-free-web-proxy/lmmpgfjnchldhcieiiegcpdmaidkaanb?hl=en and it will do everything for you. After that just type 3kh0.github.io and hit enter.

My school has blocked all extensions and the keywords "unblocked, vpn, proxy/proxies/proxie"

**Comment by Piplup7575** [comment]
lmao
downloading the site seems to be your best bet then

**Comment by derinpilge** [comment]
...................

**Comment by Adithr123** [comment]
What file do I depoy pages with?
