### ISSUE TITLE
[Bug] Project images fail to load sometimes

### ISSUE THREAD

**Issue by 3kh0** [3kh0/3kh0.github.io#74]
### Check these boxes to make sure you did everything right!

- [X] I have made sure that this issue does not already exist
- [X] I have submitted screenshots of the error
- [X] You are not using the website on any clones (you are using 3kh0.github.io and nothing else)
- [ ] I just checked all of these boxes without reading the labels

### What browser are you using?

Google Chrome

### What device are you using?

Chromebook

### Please explain the issue

Like the title says, sometimes it works, sometimes it does not

![image](https://user-images.githubusercontent.com/58097612/217701374-8b932cee-2a04-4bd3-ac3c-3af374e19b75.png)

This is a screenshot of console, from page load, no errors until the images start failing to load

![image](https://user-images.githubusercontent.com/58097612/217701568-492c4708-f5d3-4781-8b42-781649366a3a.png)

Now I started to probe deeper, this might be a flaw with a service worker or something. So I opened up the network tab, went to one of the images, inspected the fetch, and on the preview tab, it is the site 404 page, going to it on a new tab gets a `ERR_FAILED` error.

![image](https://user-images.githubusercontent.com/58097612/217701864-4891f5b0-37e5-4fe4-bf76-ffbe6dbbb833.png)

Now here is the kicker, once I reload that page, it is just the image.

![image](https://user-images.githubusercontent.com/58097612/217701983-f88756b2-e9df-4e15-b179-5349ff5b5abe.png)

But then doing a ctrl+shift+r (reload and clear cache) gets a 404 error

![image](https://user-images.githubusercontent.com/58097612/217702076-a52ae97c-ed71-4d6c-9648-0391e39c3905.png)

I do not know much about what is going on here, it might be something with the service worker not being registered or something, I have no clue

**Comment by 3kh0** [comment]
This happens with the githack cdn, but not the AWS ones, so weird

**Comment by 3kh0** [comment]
![image](https://user-images.githubusercontent.com/58097612/217702553-d9daba7c-d1e3-4d9a-bc2c-5bc58e7f9762.png)

**Comment by Russell2259** [comment]
I have been using the ultraviolet service worker for one of my projects and if you hard reload and/or empty your cache it unregisters the service worker.

**Comment by 3kh0** [comment]
@Russell2259 Ahhh I see, can you see if you can add a script to the `js/index.js` file to see if you can first detect if the service worker is registered, if not, register it

**Comment by Russell2259** [comment]
I added something that should do the trick.

#83

**Comment by 3kh0** [comment]
@Russell2259 I can confirm the the fix does work. I unregistered the service worker, and on the reload, it readded it.
