### ISSUE TITLE
Small issue - Add a redirect to your github profile so I don't have to search/type it every time

### ISSUE THREAD

**Issue by nicolasog12** [3kh0/3kh0.github.io#75]
### What is this request?

New feature

### Please describe the new feature here

Bascially just add a button or url that shortens the link to your profile, or to the github repo (ex. [https://3kh0.github.io/gitprofile], [https://tinyurl.com/echos-github], 
[https://3kh0.github.io/dump/redirect.html?to=https%3A%2F%2Fgithub.com%2F3kh0&local=false] <- shorten that url )

**Comment by 3kh0** [comment]
it is only github.com/3kh0

**Comment by 3kh0** [comment]
it is not that long

**Comment by RuralAnemone** [comment]
wait

**Comment by RuralAnemone** [comment]
add a button where?

**Comment by nicolasog12** [comment]
> add a button where exactly?
Maybe on the bottom of the homepage or just a short url with a meta redirect code

**Comment by nicolasog12** [comment]
Nevermind tho
