### ISSUE TITLE
Add Plants vs Zombies

### ISSUE THREAD

**Issue by El-pesesito-Jowy** [3kh0/3kh0.github.io#76]
### What is this request?

New game

### Please describe the new feature here

I would like to play plants vs zombies 1 or 2 it's my favourite videogame.

**Comment by 3kh0** [comment]
Please provide some links

**Comment by Rahib777-7** [comment]
ill try to do this one

**Comment by Russell2259** [comment]
@Rahib777-7 added scratch version of plants vs zombies.
