### ISSUE TITLE
[Bug] Typo in redirect

### ISSUE THREAD

**Issue by nicolasog12** [3kh0/3kh0.github.io#76]
### Check these boxes to make sure you did everything right!

- [X] I have made sure that this issue does not already exist
- [X] I have submitted screenshots of the error
- [X] You are not using the website on any clones (you are using 3kh0.github.io and nothing else)
- [ ] I just checked all of these boxes without reading the labels

### What browser are you using?

Google Chrome

### If you said other above, please specify which browser you use

Does not matter browser

### What device are you using?

Chromebook

### If you said other above, please specify which device you use

Does not matter device

### Please explain the issue

In the redirect page it says "thanks for not using **a ad block**" I know this is small but it kind of looks bad for the site, it would look more professional to use "Thanks for not using an adblocker"

**Comment by Piplup7575** [comment]
fixed :)
