### ISSUE TITLE
Add Hill Climb racing + Drag Racing

### ISSUE THREAD

**Issue by EckBock** [3kh0/3kh0.github.io#78]
### What is this request?

New game

### Please describe the new feature here

please add hill climb racing and/or a drag racing game that is something like pixel car racer.

**Comment by 3kh0** [comment]
Please provide some links

**Comment by EckBock** [comment]
Provide a github link?

**Comment by EckBock** [comment]
would you like a github link?

**Comment by 3kh0** [comment]
Any link

**Comment by 3kh0** [comment]
notice how in the form it said to provide links and you did not do that at all

**Comment by EckBock** [comment]
so do you just need any link to the game?

**Comment by 3kh0** [comment]
yes, one where you can play it in your browser

**Comment by EckBock** [comment]
These are some decent ones I found, if you can add all of them, and if not
its ok.
https://www.agame.com/game/hill-racing-challenge
https://scratch.mit.edu/projects/65811674/
https://www.topspeed.com/car-games/drag-racing-rivals/

**Comment by EckBock** [comment]
have you added them?

**Comment by Russell2259** [comment]
I can add the scratch one using https://packager.turbowarp.org

**Comment by Russell2259** [comment]
I opened a pr in 3kh0/3kh0-Assets#16 which contains the scratch hill climb racing.
