### ISSUE TITLE
Want to help

### ISSUE THREAD

**Issue by nicolasog12** [3kh0/3kh0.github.io#78]
# I would love to help with the website!
I am very good with HTML, I'm learning CSS, and are soon going to learn JavaScript. (by the way, i am using the freecodecamp curriculum, so it could take a few days before i finish the css lessons)
If I could, I would definitely like to help with the website.
Time zone: EST (Eastern Standard Time) 5:00

**Comment by Piplup7575** [comment]
Make pull reqs like i am if you want to add things :)
