### ISSUE TITLE
Add a review

### ISSUE THREAD

**Issue by ihateni** [3kh0/3kh0.github.io#79]
### Name

ihateni

### Review

very cool and fun i would recommend also heres a proxy v4.wiki

### Profile picture

;)

**Comment by 3kh0** [comment]
No profile picture

**Comment by ihateni** [comment]
![image](https://user-images.githubusercontent.com/112515516/217950939-f205de39-3290-4c28-932d-9f96c9afab3e.png)
amazing site I'd recommend also heres a proxy v4.wiki
