### ISSUE TITLE
Add Rooftop Snipers 2

### ISSUE THREAD

**Issue by ItCameFr0mMars** [3kh0/3kh0.github.io#79]
Rooftop snipers 2 https://www.youtube.com/watch?v=bpv94je7kRs http://www.neweichgames.com https://poki.com/en/g/rooftop-snipers-2

**Comment by boomboomaladirt** [comment]
rts2 would be fire

**Comment by Piplup7575** [comment]
i cant find the github repo but here https://ubg100.github.io/rooftop-snipers

**Comment by 3kh0** [comment]
If anyone can do this that would be pog, just make a pr
