### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by Voltylolty** [3kh0/3kh0.github.io#80]
### What is this request?

New game

### If you said other in the dropdown above, please specify what below

Pokemon games

### Please describe the new feature here

Can you add some pokemon games?

**Comment by 3kh0** [comment]
Any links?

**Comment by Voltylolty** [comment]
what do you mean? like link for the games?

**Comment by 3kh0** [comment]
y3w

**Comment by Russell2259** [comment]
@Voltylolty yes

**Comment by 3kh0** [comment]
No links
