### ISSUE TITLE
Can you please add these games?

### ISSUE THREAD

**Issue by boomboomaladirt** [3kh0/3kh0.github.io#83]
Subway Surfers ([https://poki.com/en/g/subway-surfers](https://poki.com/en/g/subway-surfers) 
Crossy Road [https://poki.com/en/g/crossy-road](https://poki.com/en/g/crossy-road)
Clash of Vikings [https://lagged.com/play/608/](https://lagged.com/play/608/)
Hole.io [https://poki.com/en/g/hole-io](https://poki.com/en/g/hole-io)
Cut the Rope Experiments [https://poki.com/en/g/cut-the-rope-experiments](https://poki.com/en/g/cut-the-rope-experiments)
Parkour Race [https://poki.com/en/g/parkour-race](https://poki.com/en/g/parkour-race)

Thanks! Hopefully, your parents didn't find out you snuck ur laptop to school lol.

**Comment by 3kh0** [comment]
Thank you for this suggestion. And yes she did not find out @boomboomaladirt :)

**Comment by coolman3289** [comment]
Nice!

**Comment by boomboomaladirt** [comment]
> Thank you for this suggestion. And yes she did not find out @boomboomaladirt :)

Phew

**Comment by derinpilge** [comment]
> Subway Surfers (https://poki.com/en/g/subway-surfers Crossy Road https://poki.com/en/g/crossy-road Clash of Vikings https://lagged.com/play/608/ Hole.io https://poki.com/en/g/hole-io Cut the Rope Experiments https://poki.com/en/g/cut-the-rope-experiments Parkour Race https://poki.com/en/g/parkour-race
> 
> Thanks! Hopefully, your parents didn't find out you snuck ur laptop to school lol.

Here's a link for CROSSY ROAD
I'm a developer myself and would like to work with 3kh0 some day
Link: 
https://crossyroad.netlify.app/
