### ISSUE TITLE
Add BitLife

### ISSUE THREAD

**Issue by LugCentral** [3kh0/3kh0.github.io#84]
It would be amazing to play bitlife in class so can you or piplup7575 either find the source code and index the html into the site? If you can that would so awesome!

**Comment by 3kh0** [comment]
Do you have a site where it is? Like is there a website that already had this game?

**Comment by LugCentral** [comment]
Um Yeah... It uses some kind of android emulator[  Link](https://www.silvergames.com/en/bitlife)

**Comment by coolman3289** [comment]
This would be awesome! Count my vote on this!

**Comment by 3kh0** [comment]
done
