### ISSUE TITLE
The ultimate gaming website?

### ISSUE THREAD

**Issue by RatInChat** [3kh0/3kh0.github.io#86]
### Name

Is v3 worth it?

### Review

7/10. Honestly, I think v2 looked better but v3 is ok. The amount of ads this website has is a lot more than v2 so it takes a bit to load. Other than that I would recommend. (It would have been 5/10 but he added piplup so I had to add +2 social credit)

### Profile picture

![penguin](https://user-images.githubusercontent.com/98173006/194172156-30b315ff-54bb-48cf-bfe2-ab534f269173.jpeg)

**Comment by 3kh0** [comment]
xd i will add it

**Comment by Piplup7575** [comment]
ahahahaha
