### ISSUE TITLE
Where do I find the new games you add?

### ISSUE THREAD

**Issue by coolman3289** [3kh0/3kh0.github.io#87]
Where do I find them? Can you link it? If not, tell me.

**Comment by boomboomaladirt** [comment]
when you open the website, above echo's pfp there is a changelog link where you can see the games he/she adds.

**Comment by coolman3289** [comment]
Idk, but can you link them in the log?

**Comment by nicolasog12** [comment]
He might if he sees this issue...

**Comment by 3kh0** [comment]
Hey there @coolman3289, we will be working on a better designed projects list. For now, just scroll through the list and see if you can find whats new!
