### ISSUE TITLE
Zombs-royals gives 404 no found error

### ISSUE THREAD

**Issue by coolman3289** [3kh0/3kh0.github.io#88]
When I went to chrome on my 8th gen iPad running IOS 15.2.1 the game briefly flashed on screen before giving a bad getaway. This does not happen on safari.

**To Reproduce**
1. Go to 'Zombs royals on chrome on a 8th gen iPad running IOS 15.2.1 '
2. Get error.

**Expected behavior**
I excpect the game to pop up and load (although it does not even load on safari).

**Screenshots**
Attached

**System information**

Operating system (eg ChromeOS or Windows):IOS
Browser:Chrome

**Comment by coolman3289** [comment]
Image: https://ibb.co/2g0L8s3

**Comment by coolman3289** [comment]
?

**Comment by 3kh0** [comment]
Hmmm, it works for me. Try reloading and/or checking the URL. 

*If you could paste the url you are using here that would be nice*
