### ISSUE TITLE
plz add fnaf 

### ISSUE THREAD

**Issue by retrobro** [3kh0/3kh0.github.io#89]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Piplup7575** [comment]
just use this https://wellsousaaa.github.io/Five-Nights-at-Freddys-Web/

**Comment by Aspaceman527** [comment]
i think he means the actual game

**Comment by 3kh0** [comment]
> just use this https://wellsousaaa.github.io/Five-Nights-at-Freddys-Web/
