### ISSUE TITLE
"View more stuff" button should be changed

### ISSUE THREAD

**Issue by nicolasog12** [3kh0/3kh0.github.io#91]
The "View more stuff" button is not descriptive enough, you should change the name to something like "Proxies and more" or something like that.

**Comment by 3kh0** [comment]
I will agree with this but just making it Proxies and more is not good enough

**Comment by nicolasog12** [comment]
I will think about a good name for the button

**Comment by nicolasog12** [comment]
"Find my other projects here!"
^^^^^^^^^^^^^^^^^^^^^^^^^^^
First suggestion

**Comment by nicolasog12** [comment]
"Proxies, discord, and more..."
^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Second suggestion

You could also make a "perchance" system that will show random text on the button

**Comment by 3kh0** [comment]
Stale
