### ISSUE TITLE
Eaglercraft new version pog??

### ISSUE THREAD

**Issue by airtag8892** [3kh0/3kh0.github.io#91]
### What is this request?

New game

### Please describe the new feature here

so um does eaglercraft have versions above 1.8?? if they do can they be added to 3kh0?? ty!!

**Comment by Russell2259** [comment]
@airtag8892 Eaglercraft does have an update for 1.8 and it is included in the game files, but it has not been added to the GUI yet.

If you want to play it go to:
[https://3kh0.github.io/files/minecraft-18/index.html](https://3kh0.github.io/files/minecraft-18/index.html)

**Comment by airtag8892** [comment]
i'm aware there is 1.8, is there any versions higher than 1.8 tho?

**Comment by Russell2259** [comment]
lol. It's called Eaglercraft 1.8

No there are not current versions of Eaglercraft above v1.8.
