### ISSUE TITLE
Hex GL not starting

### ISSUE THREAD

**Issue by derinpilge** [3kh0/3kh0.github.io#92]
Ok, I've clicked onto HEX GL, im on the website where it says 
HEXGL 
By  Bkcore
Start
Controls: Keyboard
Quality: Very High
Hud: ON

Issue/Bug: I press start but its not starting for some reason; When i hover my mouse over it, it enlargens but when i click it does not start game

Pls help this is my favorite game

**Comment by nicolasog12** [comment]
It isn't working for me either.
It might be that it's the pure source code to unblock it, but there's an error.

**Comment by Piplup7575** [comment]
yep its broken

https://user-images.githubusercontent.com/88395302/156005660-07e6e28b-52e6-44fb-aa95-cc9a2d329f21.mp4

**Comment by 3kh0** [comment]
This issue has been fixed. Please reopen if any more errors occur!
