### ISSUE TITLE
Fix cookie accept popup

### ISSUE THREAD

**Issue by nicolasog12** [3kh0/3kh0.github.io#94]
When told to accept cookies you can see the popup but an ad in the bottom blocks the accept button from being visible.

Possible fix:
Justify the popup to the center
Add a z-index above the content (do 2 if you never use z-index) for the cookies div
Add a "Never show again box" so it won't continue

I am sure I'm not  the only one who gets bugged by this, and it would make a great fix.

**Comment by nicolasog12** [comment]
@3kh0 you could justify the popup to the center

**Comment by 3kh0** [comment]
@nicolasog12 try setting the z-index to something like 99999, make a pull and I will merge it

**Comment by 3kh0** [comment]
Fixed
