### ISSUE TITLE
add the henry stickman collection

### ISSUE THREAD

**Issue by Aspaceman527** [3kh0/3kh0.github.io#95]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Piplup7575** [comment]
This needs to be purchased on Steam, and 3kh0 might be sued if he puts that game on his site.
But you might be able to play it here https://henrystickmincollection.com/ but im not sure if this site is legal or not

**Comment by Aspaceman527** [comment]
at least make a game that is similer

**Comment by coolman3289** [comment]
So you expect him to script and draw a game…

**Comment by 3kh0** [comment]
Yes what @Piplup7575 said, but if there are any versions that are already online, you can open a new issue with the link.
