### ISSUE TITLE
Can you also add these games by any chance?

### ISSUE THREAD

**Issue by boomboomaladirt** [3kh0/3kh0.github.io#97]
Dadish! [poki link](https://poki.com/en/g/dadish)
Dadish! 2 [poki link](https://poki.com/en/g/dadish-2)
King of Thieves [poki link](https://poki.com/en/g/king-of-thieves)
Word city [poki link](https://poki.com/en/g/word-city-crossed)
Papa's Pizzaria [poki link](https://poki.com/en/g/papas-pizzeria)
Stickman Hook [poki link](https://poki.com/en/g/stickman-hook)
Fancy pants [poki link](https://poki.com/en/g/fancy-pants)
Fancy pants 2 [poki link](https://poki.com/en/g/fancy-pants-2)
Fancy pants 3 [poki link](https://poki.com/en/g/fancy-pants-3)

Thanks! this website is the only thing keeping me alive in school lol

**Comment by 3kh0** [comment]
@Piplup7575 if you could try porting these that would be amazing!

**Comment by Piplup7575** [comment]
Ok!

**Comment by Piplup7575** [comment]
I get an error whenever clicking on any of these links. Are you sure they are the correct links?
![image](https://user-images.githubusercontent.com/88395302/156944247-b3639ece-ecf1-4e65-8a23-b79fbc3c7f77.png)
