### ISSUE TITLE
plz add pokemon soulsilver

### ISSUE THREAD

**Issue by retrobro** [3kh0/3kh0.github.io#98]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Piplup7575** [comment]
i'll look into it

**Comment by ItCameFr0mMars** [comment]
@retrobro where are you getting the game from? any links?

**Comment by 3kh0** [comment]
Inactive
