### ISSUE TITLE
Game Request: FNAF Collection

### ISSUE THREAD

**Issue by TheEpicMainframe** [3kh0/3kh0.github.io#99]
Please add any possible FNAF games you may find!

**Comment by Aspaceman527** [comment]
like fnaf 2

**Comment by Piplup7575** [comment]
dupe of #89 
just use this https://wellsousaaa.github.io/Five-Nights-at-Freddys-Web/

**Comment by 3kh0** [comment]
What @Piplup7575 said,

**Comment by JonnyKKid** [comment]
Add any car game of your chouse
