### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by KrunchyKarrots** [3kh0/3kh0.github.io#99]
### What is this request?

New game

### Please describe the new feature here

Can you please add Spelunky?

**Comment by Russell2259** [comment]
Do you have a link?

**Comment by SipSup3314** [comment]
i have spelunky files. he doesn't need a link

**Comment by Russell2259** [comment]
oh ok

**Comment by 3kh0** [comment]
@SipSup3314 Make a pull request on the assets repo

**Comment by SipSup3314** [comment]
When I get home in an hour I will do it

**Comment by SipSup3314** [comment]
Close issue? @3kh0
